// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import type * as apiTypes from './dialog';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/DialogInputInfo",
    "definitions": {
        "DialogInputInfo": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "const": "file"
                },
                "fileExtension": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateDialogInputInfo(payload: unknown): apiTypes.DialogInputInfo {
  /** Schema is defined in {@link SCHEMA.definitions.DialogInputInfo } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/DialogInputInfo");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid DialogInputInfo: ' + ajv.errorsText(validator.errors, {dataVar: "DialogInputInfo"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isDialogInputInfo(payload: unknown): payload is apiTypes.DialogInputInfo {
  try {
    validateDialogInputInfo(payload);
    return true;
  } catch (error) {
    return false;
  }
}
