// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import type * as apiTypes from './generatorSettings';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "GeneratorSettingSpec": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/GeneratorSettingType"
                },
                "max": {
                    "type": "number"
                },
                "min": {
                    "type": "number"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GeneratorSettingValueSpec"
                    }
                },
                "valueTypes": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/GeneratorSettingValueType"
                    }
                },
                "defaultValue": {}
            },
            "required": [
                "id",
                "title",
                "type"
            ],
            "additionalProperties": false
        },
        "GeneratorSettingType": {
            "type": "string",
            "enum": [
                "boolean",
                "integer",
                "item",
                "array"
            ]
        },
        "GeneratorSettingValueSpec": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "name"
            ],
            "additionalProperties": false
        },
        "GeneratorSettingValueType": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "number"
                },
                "input": {
                    "$ref": "#/definitions/GeneratorSettingSpec"
                }
            },
            "additionalProperties": false
        },
        "GeneratorSetting": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "value": {}
            },
            "required": [
                "id",
                "value"
            ],
            "additionalProperties": false
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateGeneratorSettingSpec(payload: unknown): apiTypes.GeneratorSettingSpec {
  /** Schema is defined in {@link SCHEMA.definitions.GeneratorSettingSpec } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/GeneratorSettingSpec");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid GeneratorSettingSpec: ' + ajv.errorsText(validator.errors, {dataVar: "GeneratorSettingSpec"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isGeneratorSettingSpec(payload: unknown): payload is apiTypes.GeneratorSettingSpec {
  try {
    validateGeneratorSettingSpec(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateGeneratorSettingType(payload: unknown): apiTypes.GeneratorSettingType {
  /** Schema is defined in {@link SCHEMA.definitions.GeneratorSettingType } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/GeneratorSettingType");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid GeneratorSettingType: ' + ajv.errorsText(validator.errors, {dataVar: "GeneratorSettingType"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isGeneratorSettingType(payload: unknown): payload is apiTypes.GeneratorSettingType {
  try {
    validateGeneratorSettingType(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateGeneratorSettingValueSpec(payload: unknown): apiTypes.GeneratorSettingValueSpec {
  /** Schema is defined in {@link SCHEMA.definitions.GeneratorSettingValueSpec } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/GeneratorSettingValueSpec");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid GeneratorSettingValueSpec: ' + ajv.errorsText(validator.errors, {dataVar: "GeneratorSettingValueSpec"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isGeneratorSettingValueSpec(payload: unknown): payload is apiTypes.GeneratorSettingValueSpec {
  try {
    validateGeneratorSettingValueSpec(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateGeneratorSettingValueType(payload: unknown): apiTypes.GeneratorSettingValueType {
  /** Schema is defined in {@link SCHEMA.definitions.GeneratorSettingValueType } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/GeneratorSettingValueType");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid GeneratorSettingValueType: ' + ajv.errorsText(validator.errors, {dataVar: "GeneratorSettingValueType"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isGeneratorSettingValueType(payload: unknown): payload is apiTypes.GeneratorSettingValueType {
  try {
    validateGeneratorSettingValueType(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateGeneratorSetting(payload: unknown): apiTypes.GeneratorSetting {
  /** Schema is defined in {@link SCHEMA.definitions.GeneratorSetting } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/GeneratorSetting");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid GeneratorSetting: ' + ajv.errorsText(validator.errors, {dataVar: "GeneratorSetting"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isGeneratorSetting(payload: unknown): payload is apiTypes.GeneratorSetting {
  try {
    validateGeneratorSetting(payload);
    return true;
  } catch (error) {
    return false;
  }
}
