import type { AccessModifier } from "@shared/appData/accessRulesets"

export const flashForDarkAreas: AccessModifier[] = [
  {
    LOCATIONS: [
      "SILVER_CAVE_ROOM_1",
      "ROCK_TUNNEL_1F_CERULEAN_SIDE",
      "ROCK_TUNNEL_1F_LAVENDER_SIDE",
      "ROCK_TUNNEL_1F_INNER_AREA",
      "ROCK_TUNNEL_B1F_NW_AREA",
      "ROCK_TUNNEL_B1F_SE_AREA",
      "WHIRL_ISLAND_NW_ENTRANCE_AREA",
      "WHIRL_ISLAND_NW_ISOLATED_AREA",
      "WHIRL_ISLAND_NE_WEST_AREA",
      "WHIRL_ISLAND_CAVE",
      "WHIRL_ISLAND_SE",
      "WHIRL_ISLAND_B1F_NORTH_AREA",
      "WHIRL_ISLAND_B1F_NE_AREA",
      "WHIRL_ISLAND_B1F_SE_AREA",
      "WHIRL_ISLAND_B1F_CENTRAL_AREA",
      "WHIRL_ISLAND_B2F_ISOLATED_AREA",
      "WHIRL_ISLAND_LUGIA_CHAMBER",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "DARK_CAVE_VIOLET_ENTRANCE_WEST_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "ROUTE_31_CAVE_IN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "DARK_CAVE_VIOLET_ENTRANCE_NORTH_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "DARK_CAVE_BLACKTHORN_ENTRANCE_SW_AREA_CAVE_OUT",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "DARK_CAVE_VIOLET_ENTRANCE_SE_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "ROUTE_46_NORTH_AREA_CAVE_IN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "DARK_CAVE_BLACKTHORN_ENTRANCE_NE_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "ROUTE_45_CAVE_IN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "DARK_CAVE_BLACKTHORN_ENTRANCE_SW_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "DARK_CAVE_VIOLET_ENTRANCE_NORTH_AREA_CAVE_IN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_NE_TOP_LEDGE_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_B1F_NE_AREA_LADDER_UP",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_NE_BOTTOM_LEDGE_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_B1F_NORTH_AREA_EAST_LADDER_UP",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_SW_ENTRANCE_EAST_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_B1F_SE_AREA_LEFT_LADDER_UP",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_SW_ENTRANCE_WEST_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_B1F_SW_AREA_LADDER_UP",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_SW_ENTRANCE_WEST_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "ROUTE_41_SW_ISLAND_AREA_CAVE_IN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_SW_WEST_ISOLATED_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_NW_ISOLATED_AREA_LADDER_DOWN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_SW_EAST_ISOLATED_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_B2F_BELOW_WATERFALL_SOUTH_AREA_LADDER_UP",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_B1F_SW_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_SW_ENTRANCE_WEST_AREA_LADDER_DOWN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_B2F_ABOVE_WATERFALL_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_B1F_NE_AREA_LADDER_DOWN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_B2F_BELOW_WATERFALL_NORTH_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_LUGIA_CHAMBER_CAVE_OUT",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
  {
    LOCATIONS: [
      "WHIRL_ISLAND_B2F_BELOW_WATERFALL_SOUTH_AREA",
    ],
    MATCHING_REQUIREMENTS: [
      "WHIRL_ISLAND_SW_EAST_ISOLATED_AREA_LADDER_DOWN",
    ],
    ADDED_REQUIREMENTS: [
      "ZEPHYRBADGE",
      "HM05",
    ],
  },
]