import type { AccessModifier } from "@shared/appData/accessRulesets"

export const noVanillaBasement: AccessModifier[] = [
  {
    LOCATIONS: [
      "GOLDENROD_UNDERGROUND_SWITCH_ROOM_STAIRS_UP",
      "GOLDENROD_UNDERGROUND_SWITCH_ROOM_BOTTOM_LEFT_ITEM_BALL",
      "GOLDENROD_UNDERGROUND_SWITCH_ROOM_TOP_RIGHT_ITEM_BALL",
      "GOLDENROD_UNDERGROUND_SWITCH_ROOM_TOP_MIDDLE_HIDDEN_ITEM",
      "GOLDENROD_UNDERGROUND_SWITCH_ROOM_TOP_LEFT_HIDDEN_ITEM",
      "GOLDENROD_UNDERGROUND_SWITCH_ROOM_DOOR_IN_LEFT",
      "GOLDENROD_UNDERGROUND_SWITCH_ROOM_DOOR_IN_RIGHT",
      "GOLDENROD_UNDERGROUND_WAREHOUSE_DOOR_OUT_LEFT",
      "GOLDENROD_UNDERGROUND_WAREHOUSE_DOOR_OUT_RIGHT",
      "GOLDENROD_UNDERGROUND_WAREHOUSE_ITEM_BALL_1",
      "GOLDENROD_UNDERGROUND_WAREHOUSE_ITEM_BALL_2",
      "GOLDENROD_UNDERGROUND_WAREHOUSE_ITEM_BALL_3",
      "GOLDENROD_UNDERGROUND_WAREHOUSE_RADIO_DIRECTORS_GIFT",
      "GOLDENROD_UNDERGROUND_WAREHOUSE_TALKED_TO_DIRECTOR",
      "GOLDENROD_UNDERGROUND_WAREHOUSE_STAIRS_UP",
    ],
    ADDED_REQUIREMENTS: [
      "RADIO_TOWER_5F_EAST_AREA_DEFEATED_ROCKETS",
    ],
  },
]