export const gameMapGroupIds = [
  "OLIVINE",
  "MAHOGANY",
  "DUNGEONS",
  "ECRUTEAK",
  "BLACKTHORN",
  "CINNABAR",
  "CERULEAN",
  "AZALEA",
  "LAKE_OF_RAGE",
  "VIOLET",
  "GOLDENROD",
  "VERMILION",
  "PALLET",
  "PEWTER",
  "FAST_SHIP",
  "INDIGO",
  "FUCHSIA",
  "LAVENDER",
  "SILVER",
  "CABLE_CLUB",
  "CELADON",
  "CIANWOOD",
  "VIRIDIAN",
  "NEW_BARK",
  "SAFFRON",
  "CHERRYGROVE",
] as const

export type GameMapGroupId = typeof gameMapGroupIds[number]