export const pokedexPartItemIds = [
  "POKEDEX",
  "UNONWNDEX",
] as const

export const pokegearPartItemIds = [
  "POKEGEAR",
  "MAP_CARD",
  "RADIO_CARD",
  "EXPN_CARD",
] as const

export const johtoBadgeItemIds = [
  "ZEPHYRBADGE",
  "HIVEBADGE",
  "PLAINBADGE",
  "FOGBADGE",
  "STORMBADGE",
  "MINERALBADGE",
  "GLACIERBADGE",
  "RISINGBADGE",
] as const

export const kantoBadgeItemIds = [
  "BOULDERBADGE",
  "CASCADEBADGE",
  "THUNDERBADGE",
  "RAINBOWBADGE",
  "SOULBADGE",
  "MARSHBADGE",
  "VOLCANOBADGE",
  "EARTHBADGE",
] as const

export const keyItemIds = [
  "BASEMENT_KEY",
  "BICYCLE",
  "BLUE_CARD",
  "CARD_KEY",
  "CLEAR_BELL",
  "COIN_CASE",
  "EGG_TICKET",
  "GOOD_ROD",
  "GS_BALL",
  "ITEMFINDER",
  "LOST_ITEM",
  "MACHINE_PART",
  "MYSTERY_EGG",
  "OLD_ROD",
  "PASS",
  "RAINBOW_WING",
  "RED_SCALE",
  "SECRETPOTION",
  "SILVER_WING",
  "SQUIRTBOTTLE",
  "S_S_TICKET",
  "SUPER_ROD",
] as const

export const hmItemIds = [
  "HM01",
  "HM02",
  "HM03",
  "HM04",
  "HM05",
  "HM06",
  "HM07",
] as const

export const tmItemIds = [
  "TM01",
  "TM02",
  "TM03",
  "TM04",
  "TM05",
  "TM06",
  "TM07",
  "TM08",
  "TM09",
  "TM10",
  "TM11",
  "TM12",
  "TM13",
  "TM14",
  "TM15",
  "TM16",
  "TM17",
  "TM18",
  "TM19",
  "TM20",
  "TM21",
  "TM22",
  "TM23",
  "TM24",
  "TM25",
  "TM26",
  "TM27",
  "TM28",
  "TM29",
  "TM30",
  "TM31",
  "TM32",
  "TM33",
  "TM34",
  "TM35",
  "TM36",
  "TM37",
  "TM38",
  "TM39",
  "TM40",
  "TM41",
  "TM42",
  "TM43",
  "TM44",
  "TM45",
  "TM46",
  "TM47",
  "TM48",
  "TM49",
  "TM50",
] as const

export const regularItemIds = [
  "AMULET_COIN",
  "ANTIDOTE",
  "AWAKENING",
  "BERRY_JUICE",
  "BERRY",
  "BERSERK_GENE",
  "BIG_MUSHROOM",
  "BIG_PEARL",
  "BITTER_BERRY",
  "BLACKBELT",
  "BLACKGLASSES",
  "BLK_APRICORN",
  "BLU_APRICORN",
  "BLUESKY_MAIL",
  "BRICK_PIECE",
  "BRIGHTPOWDER",
  "BURN_HEAL",
  "BURNT_BERRY",
  "CALCIUM",
  "CARBOS",
  "CHARCOAL",
  "CLEANSE_TAG",
  "DIRE_HIT",
  "DRAGON_FANG",
  "DRAGON_SCALE",
  "ELIXER",
  "ENERGY_ROOT",
  "ENERGYPOWDER",
  "EON_MAIL",
  "ESCAPE_ROPE",
  "ETHER",
  "EVERSTONE",
  "EXP_SHARE",
  "FIRE_STONE",
  "FLOWER_MAIL",
  "FOCUS_BAND",
  "FRESH_WATER",
  "FULL_HEAL",
  "FULL_RESTORE",
  "GOLD_BERRY",
  "GOLD_LEAF",
  "GORGEOUS_BOX",
  "GRN_APRICORN",
  "GUARD_SPEC",
  "HARD_STONE",
  "HEAL_POWDER",
  "HP_UP",
  "HYPER_POTION",
  "ICE_BERRY",
  "ICE_HEAL",
  "IRON",
  "KINGS_ROCK",
  "LEAF_STONE",
  "LEFTOVERS",
  "LEMONADE",
  "LIGHT_BALL",
  "LITEBLUEMAIL",
  "LOVELY_MAIL",
  "LUCKY_EGG",
  "LUCKY_PUNCH",
  "MAGNET",
  "MAX_ELIXER",
  "MAX_ETHER",
  "MAX_POTION",
  "MAX_REPEL",
  "MAX_REVIVE",
  "METAL_COAT",
  "METAL_POWDER",
  "MINT_BERRY",
  "MIRACLE_SEED",
  "MIRACLEBERRY",
  "MIRAGE_MAIL",
  "MOOMOO_MILK",
  "MOON_STONE",
  "MORPH_MAIL",
  "MUSIC_MAIL",
  "MYSTERYBERRY",
  "MYSTIC_WATER",
  "NEVERMELTICE",
  "NORMAL_BOX",
  "NUGGET",
  "PARLYZ_HEAL",
  "PEARL",
  "PINK_BOW",
  "PNK_APRICORN",
  "POISON_BARB",
  "POKE_DOLL",
  "POLKADOT_BOW",
  "PORTRAITMAIL",
  "POTION",
  "PP_UP",
  "PROTEIN",
  "PRZCUREBERRY",
  "PSNCUREBERRY",
  "QUICK_CLAW",
  "RAGECANDYBAR",
  "RARE_CANDY",
  "RED_APRICORN",
  "REPEL",
  "REVIVAL_HERB",
  "REVIVE",
  "SACRED_ASH",
  "SCOPE_LENS",
  "SHARP_BEAK",
  "SILVER_LEAF",
  "SILVERPOWDER",
  "SLOWPOKETAIL",
  "SMOKE_BALL",
  "SODA_POP",
  "SOFT_SAND",
  "SPELL_TAG",
  "STAR_PIECE",
  "STARDUST",
  "STICK",
  "SUN_STONE",
  "SUPER_POTION",
  "SUPER_REPEL",
  "SURF_MAIL",
  "THICK_CLUB",
  "THUNDERSTONE",
  "TINYMUSHROOM",
  "TWISTEDSPOON",
  "UP_GRADE",
  "WATER_STONE",
  "WHT_APRICORN",
  "X_ACCURACY",
  "X_ATTACK",
  "X_DEFEND",
  "X_SPECIAL",
  "X_SPEED",
  "YLW_APRICORN",
] as const

export const ballItemIds = [
  "POKE_BALL",
  "GREAT_BALL",
  "ULTRA_BALL",
  "MASTER_BALL",
  "FAST_BALL",
  "FRIEND_BALL",
  "HEAVY_BALL",
  "LEVEL_BALL",
  "LOVE_BALL",
  "LURE_BALL",
  "MOON_BALL",
  "PARK_BALL",
] as const

export const menuItemIds = [
  ...pokedexPartItemIds,
  ...pokegearPartItemIds,
] as const

export const badgeItemIds = [
  ...johtoBadgeItemIds,
  ...kantoBadgeItemIds,
] as const

export const holdableItemIds = [
  ...tmItemIds,
  ...regularItemIds,
  ...ballItemIds,
] as const

export const bagItemIds = [
  ...keyItemIds,
  ...hmItemIds,
  ...holdableItemIds,
] as const

export const itemIds = [
  ...menuItemIds,
  ...badgeItemIds,
  ...bagItemIds,
] as const

export type PokedexPartItemId = typeof pokedexPartItemIds[number]
export type PokegearPartItemId = typeof pokegearPartItemIds[number]
export type JohtoBadgeItemId = typeof johtoBadgeItemIds[number]
export type KantoBadgeItemId = typeof kantoBadgeItemIds[number]
export type KeyItemId = typeof keyItemIds[number]
export type HMItemId = typeof hmItemIds[number]
export type TMItemId = typeof tmItemIds[number]
export type RegularItemId = typeof regularItemIds[number]
export type BallItemId = typeof ballItemIds[number]
export type MenuItemId = typeof menuItemIds[number]
export type BadgeItemId = typeof badgeItemIds[number]
export type HoldableItemId = typeof holdableItemIds[number]
export type BagItemId = typeof bagItemIds[number]
export type ItemId = typeof itemIds[number]

export const isItemId = (value: string): value is ItemId => {
  return itemIds.includes(value as any)
}