export const martGroupIds = [
  "CHERRYGROVE",
  "VIOLET",
  "AZALEA",
  "CIANWOOD",
  "GOLDENROD_2F_1",
  "GOLDENROD_2F_2",
  "GOLDENROD_3F",
  "GOLDENROD_4F",
  "GOLDENROD_5F",
  "OLIVINE",
  "ECRUTEAK",
  "MAHOGANY_1",
  "MAHOGANY_2",
  "BLACKTHORN",
  "VIRIDIAN",
  "PEWTER",
  "CERULEAN",
  "LAVENDER",
  "VERMILION",
  "CELADON_2F_1",
  "CELADON_2F_2",
  "CELADON_3F",
  "CELADON_4F",
  "CELADON_5F_1",
  "CELADON_5F_2",
  "FUCHSIA",
  "SAFFRON",
  "MT_MOON",
  "INDIGO_PLATEAU",
  "UNDERGROUND",
] as const

export type MartGroupId = typeof martGroupIds[number]