export const martIds = [
  "CHERRYGROVE_MART_SHOP_1",
  "CHERRYGROVE_MART_SHOP_2",
  "VIOLET_MART_SHOP",
  "AZALEA_MART_SHOP",
  "CIANWOOD_PHARMACY_SHOP",
  "GOLDENROD_DEPT_STORE_2F_SHOP_1",
  "GOLDENROD_DEPT_STORE_2F_SHOP_2",
  "GOLDENROD_DEPT_STORE_3F_SHOP",
  "GOLDENROD_DEPT_STORE_4F_SHOP",
  "GOLDENROD_DEPT_STORE_5F_SHOP_1",
  "GOLDENROD_DEPT_STORE_5F_SHOP_2",
  "GOLDENROD_DEPT_STORE_5F_SHOP_3",
  "GOLDENROD_DEPT_STORE_5F_SHOP_4",
  "OLIVINE_MART_SHOP",
  "ECRUTEAK_MART_SHOP",
  "MAHOGANY_MART_1F_SHOP_1",
  "MAHOGANY_MART_1F_SHOP_2",
  "BLACKTHORN_MART_SHOP",
  "VIRIDIAN_MART_SHOP",
  "PEWTER_MART_SHOP",
  "CERULEAN_MART_SHOP",
  "LAVENDER_MART_SHOP",
  "VERMILION_MART_SHOP",
  "CELADON_DEPT_STORE_2F_SHOP_1",
  "CELADON_DEPT_STORE_2F_SHOP_2",
  "CELADON_DEPT_STORE_3F_SHOP",
  "CELADON_DEPT_STORE_4F_SHOP",
  "CELADON_DEPT_STORE_5F_SHOP_1",
  "CELADON_DEPT_STORE_5F_SHOP_2",
  "FUCHSIA_MART_SHOP",
  "SAFFRON_MART_SHOP",
  "MOUNT_MOON_GIFT_SHOP_SHOP",
  "INDIGO_PLATEAU_POKECENTER_1F_SHOP",
  "GOLDENROD_UNDERGROUND_HERB_SHOP",
  "GOLDENROD_DEPT_STORE_5F_SHOP_5",
  "GOLDENROD_DEPT_STORE_5F_SHOP_6",
  "GOLDENROD_DEPT_STORE_5F_SHOP_7",
  "GOLDENROD_DEPT_STORE_5F_SHOP_8",
] as const

export type MartId = typeof martIds[number]

export const isMartId = (value: any): value is MartId => {
  return (martIds as readonly string[]).includes(value)
}

export const specialShopIds = [
  "GOLDENROD_DEPT_STORE_6F_VENDING_MACHINES",
  "CELADON_DEPT_STORE_6F_VENDING_MACHINES",
  "GOLDENROD_UNDERGROUND_BARGAIN_SHOP",
  "GOLDENROD_DEPT_STORE_ROOF_SHOP_1",
  "GOLDENROD_DEPT_STORE_ROOF_SHOP_2",
  "ROUTE_39_FARMHOUSE_SHOP",
  "MAHOGANY_TOWN_STREET_VENDOR",
  "GOLDENROD_GAME_CORNER_ITEM_SHOP",
  "CELADON_GAME_CORNER_ITEM_SHOP",
  "RADIO_TOWER_2F_BLUE_CARD_SHOP",
] as const

export type SpecialShopId = typeof specialShopIds[number]

export const isSpecialShopId = (value: any): value is SpecialShopId => {
  return (specialShopIds as readonly string[]).includes(value)
}