export const overworldMovementBehaviourIds = [
  "STILL",
  "WANDER",
  "SPINRANDOM_SLOW",
  "WALK_UP_DOWN",
  "WALK_LEFT_RIGHT",
  "STANDING_DOWN",
  "STANDING_UP",
  "STANDING_LEFT",
  "STANDING_RIGHT",
  "SPINRANDOM_FAST",
  "PLAYER",
  "FOLLOWING",
  "SCRIPTED",
  "BIGDOLLSYM",
  "POKEMON",
  "SUDOWOODO",
  "SMASHABLE_ROCK",
  "STRENGTH_BOULDER",
  "FOLLOWNOTEXACT",
  "SHADOW",
  "EMOTE",
  "SCREENSHAKE",
  "SPINCOUNTERCLOCKWISE",
  "SPINCLOCKWISE",
  "BIGDOLLASYM",
  "BIGDOLL",
  "BOULDERDUST",
  "GRASS",
  "SWIM_WANDER",
] as const

export type OverworldMovementBehaviourId = typeof overworldMovementBehaviourIds[number]