export const trainerClassIds = [
  "LEADER",
  "RIVAL",
  "POKEMON_PROF",
  "ELITE_FOUR",
  "PKMN_TRAINER",
  "CHAMPION",
  "SCIENTIST",
  "YOUNGSTER",
  "SCHOOLBOY",
  "BIRD_KEEPER",
  "LASS",
  "COOLTRAINER",
  "BEAUTY",
  "POKEMANIAC",
  "ROCKET",
  "GENTLEMAN",
  "SKIER",
  "TEACHER",
  "BUG_CATCHER",
  "FISHER",
  "SWIMMERM",
  "SWIMMERF",
  "SAILOR",
  "SUPER_NERD",
  "GUITARIST",
  "HIKER",
  "BIKER",
  "BURGLAR",
  "FIREBREATHER",
  "JUGGLER",
  "BLACKBELT",
  "PSYCHIC",
  "PICNICKER",
  "CAMPER",
  "SAGE",
  "MEDIUM",
  "BOARDER",
  "POKEFAN",
  "KIMONO_GIRL",
  "TWINS",
  "OFFICER",
  "MYSTICALMAN",
] as const

export type TrainerClassId = typeof trainerClassIds[number]