description: "Changes the data for the trainer names and pokemon."
changes:
- description: "Changes the data for the trainer names and pokemon."
  locations:
  - bank: 14
    address: 0x5999
  value: "@#trainerGroups.$data #trainerGroups.$data"