import type { GameMap } from "@shared/types/gameData/gameMap"
import type { GameMapId } from "@shared/types/gameDataIds/gameMaps"

export const gameMapsMap: IdMap<GameMapId, GameMap> = {
  OLIVINE_POKECENTER_1F: {
    id: "OLIVINE_POKECENTER_1F",
    numericId: 1,
    mapGroup: "OLIVINE",
  },
  OLIVINE_GYM: {
    id: "OLIVINE_GYM",
    numericId: 2,
    mapGroup: "OLIVINE",
  },
  OLIVINE_TIMS_HOUSE: {
    id: "OLIVINE_TIMS_HOUSE",
    numericId: 3,
    mapGroup: "OLIVINE",
  },
  OLIVINE_HOUSE_BETA: {
    id: "OLIVINE_HOUSE_BETA",
    numericId: 4,
    mapGroup: "OLIVINE",
  },
  OLIVINE_PUNISHMENT_SPEECH_HOUSE: {
    id: "OLIVINE_PUNISHMENT_SPEECH_HOUSE",
    numericId: 5,
    mapGroup: "OLIVINE",
  },
  OLIVINE_GOOD_ROD_HOUSE: {
    id: "OLIVINE_GOOD_ROD_HOUSE",
    numericId: 6,
    mapGroup: "OLIVINE",
  },
  OLIVINE_CAFE: {
    id: "OLIVINE_CAFE",
    numericId: 7,
    mapGroup: "OLIVINE",
  },
  OLIVINE_MART: {
    id: "OLIVINE_MART",
    numericId: 8,
    mapGroup: "OLIVINE",
  },
  ROUTE_38_ECRUTEAK_GATE: {
    id: "ROUTE_38_ECRUTEAK_GATE",
    numericId: 9,
    mapGroup: "OLIVINE",
  },
  ROUTE_39_BARN: {
    id: "ROUTE_39_BARN",
    numericId: 10,
    mapGroup: "OLIVINE",
  },
  ROUTE_39_FARMHOUSE: {
    id: "ROUTE_39_FARMHOUSE",
    numericId: 11,
    mapGroup: "OLIVINE",
  },
  ROUTE_38: {
    id: "ROUTE_38",
    numericId: 12,
    mapGroup: "OLIVINE",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    treeGroup: "ROUTE",
  },
  ROUTE_39: {
    id: "ROUTE_39",
    numericId: 13,
    mapGroup: "OLIVINE",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
    treeGroup: "ROUTE",
  },
  OLIVINE_CITY: {
    id: "OLIVINE_CITY",
    numericId: 14,
    mapGroup: "OLIVINE",
    encounterRegion: "JOHTO",
    waterEncounterRate: 15,
    fishingGroup: "SHORE",
  },
  MAHOGANY_RED_GYARADOS_SPEECH_HOUSE: {
    id: "MAHOGANY_RED_GYARADOS_SPEECH_HOUSE",
    numericId: 1,
    mapGroup: "MAHOGANY",
  },
  MAHOGANY_GYM: {
    id: "MAHOGANY_GYM",
    numericId: 2,
    mapGroup: "MAHOGANY",
  },
  MAHOGANY_POKECENTER_1F: {
    id: "MAHOGANY_POKECENTER_1F",
    numericId: 3,
    mapGroup: "MAHOGANY",
  },
  ROUTE_42_ECRUTEAK_GATE: {
    id: "ROUTE_42_ECRUTEAK_GATE",
    numericId: 4,
    mapGroup: "MAHOGANY",
  },
  ROUTE_42: {
    id: "ROUTE_42",
    numericId: 5,
    mapGroup: "MAHOGANY",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 10,
    fishingGroup: "LAKE",
    treeGroup: "TOWN",
  },
  ROUTE_44: {
    id: "ROUTE_44",
    numericId: 6,
    mapGroup: "MAHOGANY",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
    treeGroup: "CANYON",
  },
  MAHOGANY_TOWN: {
    id: "MAHOGANY_TOWN",
    numericId: 7,
    mapGroup: "MAHOGANY",
    treeGroup: "CANYON",
  },
  SPROUT_TOWER_1F: {
    id: "SPROUT_TOWER_1F",
    numericId: 1,
    mapGroup: "DUNGEONS",
  },
  SPROUT_TOWER_2F: {
    id: "SPROUT_TOWER_2F",
    numericId: 2,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  SPROUT_TOWER_3F: {
    id: "SPROUT_TOWER_3F",
    numericId: 3,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  TIN_TOWER_1F: {
    id: "TIN_TOWER_1F",
    numericId: 4,
    mapGroup: "DUNGEONS",
  },
  TIN_TOWER_2F: {
    id: "TIN_TOWER_2F",
    numericId: 5,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  TIN_TOWER_3F: {
    id: "TIN_TOWER_3F",
    numericId: 6,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  TIN_TOWER_4F: {
    id: "TIN_TOWER_4F",
    numericId: 7,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  TIN_TOWER_5F: {
    id: "TIN_TOWER_5F",
    numericId: 8,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  TIN_TOWER_6F: {
    id: "TIN_TOWER_6F",
    numericId: 9,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  TIN_TOWER_7F: {
    id: "TIN_TOWER_7F",
    numericId: 10,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  TIN_TOWER_8F: {
    id: "TIN_TOWER_8F",
    numericId: 11,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  TIN_TOWER_9F: {
    id: "TIN_TOWER_9F",
    numericId: 12,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  BURNED_TOWER_1F: {
    id: "BURNED_TOWER_1F",
    numericId: 13,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      10,
      10,
      10,
    ],
  },
  BURNED_TOWER_B1F: {
    id: "BURNED_TOWER_B1F",
    numericId: 14,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  NATIONAL_PARK: {
    id: "NATIONAL_PARK",
    numericId: 15,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  NATIONAL_PARK_BUG_CONTEST: {
    id: "NATIONAL_PARK_BUG_CONTEST",
    numericId: 16,
    mapGroup: "DUNGEONS",
  },
  RADIO_TOWER_1F: {
    id: "RADIO_TOWER_1F",
    numericId: 17,
    mapGroup: "DUNGEONS",
  },
  RADIO_TOWER_2F: {
    id: "RADIO_TOWER_2F",
    numericId: 18,
    mapGroup: "DUNGEONS",
  },
  RADIO_TOWER_3F: {
    id: "RADIO_TOWER_3F",
    numericId: 19,
    mapGroup: "DUNGEONS",
  },
  RADIO_TOWER_4F: {
    id: "RADIO_TOWER_4F",
    numericId: 20,
    mapGroup: "DUNGEONS",
  },
  RADIO_TOWER_5F: {
    id: "RADIO_TOWER_5F",
    numericId: 21,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_OUTSIDE: {
    id: "RUINS_OF_ALPH_OUTSIDE",
    numericId: 22,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      10,
      10,
      10,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
  },
  RUINS_OF_ALPH_HO_OH_CHAMBER: {
    id: "RUINS_OF_ALPH_HO_OH_CHAMBER",
    numericId: 23,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_KABUTO_CHAMBER: {
    id: "RUINS_OF_ALPH_KABUTO_CHAMBER",
    numericId: 24,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_OMANYTE_CHAMBER: {
    id: "RUINS_OF_ALPH_OMANYTE_CHAMBER",
    numericId: 25,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_AERODACTYL_CHAMBER: {
    id: "RUINS_OF_ALPH_AERODACTYL_CHAMBER",
    numericId: 26,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_INNER_CHAMBER: {
    id: "RUINS_OF_ALPH_INNER_CHAMBER",
    numericId: 27,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  RUINS_OF_ALPH_RESEARCH_CENTER: {
    id: "RUINS_OF_ALPH_RESEARCH_CENTER",
    numericId: 28,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_HO_OH_ITEM_ROOM: {
    id: "RUINS_OF_ALPH_HO_OH_ITEM_ROOM",
    numericId: 29,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_KABUTO_ITEM_ROOM: {
    id: "RUINS_OF_ALPH_KABUTO_ITEM_ROOM",
    numericId: 30,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_OMANYTE_ITEM_ROOM: {
    id: "RUINS_OF_ALPH_OMANYTE_ITEM_ROOM",
    numericId: 31,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM: {
    id: "RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM",
    numericId: 32,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_HO_OH_WORD_ROOM: {
    id: "RUINS_OF_ALPH_HO_OH_WORD_ROOM",
    numericId: 33,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_KABUTO_WORD_ROOM: {
    id: "RUINS_OF_ALPH_KABUTO_WORD_ROOM",
    numericId: 34,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_OMANYTE_WORD_ROOM: {
    id: "RUINS_OF_ALPH_OMANYTE_WORD_ROOM",
    numericId: 35,
    mapGroup: "DUNGEONS",
  },
  RUINS_OF_ALPH_AERODACTYL_WORD_ROOM: {
    id: "RUINS_OF_ALPH_AERODACTYL_WORD_ROOM",
    numericId: 36,
    mapGroup: "DUNGEONS",
  },
  UNION_CAVE_1F: {
    id: "UNION_CAVE_1F",
    numericId: 37,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 5,
    fishingGroup: "LAKE",
  },
  UNION_CAVE_B1F: {
    id: "UNION_CAVE_B1F",
    numericId: 38,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 5,
    fishingGroup: "LAKE",
  },
  UNION_CAVE_B2F: {
    id: "UNION_CAVE_B2F",
    numericId: 39,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      10,
      10,
      10,
    ],
    waterEncounterRate: 10,
    fishingGroup: "SHORE",
  },
  SLOWPOKE_WELL_B1F: {
    id: "SLOWPOKE_WELL_B1F",
    numericId: 40,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
    waterEncounterRate: 5,
    fishingGroup: "LAKE",
  },
  SLOWPOKE_WELL_B2F: {
    id: "SLOWPOKE_WELL_B2F",
    numericId: 41,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
    waterEncounterRate: 5,
    fishingGroup: "LAKE",
  },
  OLIVINE_LIGHTHOUSE_1F: {
    id: "OLIVINE_LIGHTHOUSE_1F",
    numericId: 42,
    mapGroup: "DUNGEONS",
  },
  OLIVINE_LIGHTHOUSE_2F: {
    id: "OLIVINE_LIGHTHOUSE_2F",
    numericId: 43,
    mapGroup: "DUNGEONS",
  },
  OLIVINE_LIGHTHOUSE_3F: {
    id: "OLIVINE_LIGHTHOUSE_3F",
    numericId: 44,
    mapGroup: "DUNGEONS",
  },
  OLIVINE_LIGHTHOUSE_4F: {
    id: "OLIVINE_LIGHTHOUSE_4F",
    numericId: 45,
    mapGroup: "DUNGEONS",
  },
  OLIVINE_LIGHTHOUSE_5F: {
    id: "OLIVINE_LIGHTHOUSE_5F",
    numericId: 46,
    mapGroup: "DUNGEONS",
  },
  OLIVINE_LIGHTHOUSE_6F: {
    id: "OLIVINE_LIGHTHOUSE_6F",
    numericId: 47,
    mapGroup: "DUNGEONS",
  },
  MAHOGANY_MART_1F: {
    id: "MAHOGANY_MART_1F",
    numericId: 48,
    mapGroup: "DUNGEONS",
  },
  TEAM_ROCKET_BASE_B1F: {
    id: "TEAM_ROCKET_BASE_B1F",
    numericId: 49,
    mapGroup: "DUNGEONS",
  },
  TEAM_ROCKET_BASE_B2F: {
    id: "TEAM_ROCKET_BASE_B2F",
    numericId: 50,
    mapGroup: "DUNGEONS",
  },
  TEAM_ROCKET_BASE_B3F: {
    id: "TEAM_ROCKET_BASE_B3F",
    numericId: 51,
    mapGroup: "DUNGEONS",
  },
  ILEX_FOREST: {
    id: "ILEX_FOREST",
    numericId: 52,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      10,
      10,
      10,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
    treeGroup: "FOREST",
  },
  GOLDENROD_UNDERGROUND: {
    id: "GOLDENROD_UNDERGROUND",
    numericId: 53,
    mapGroup: "DUNGEONS",
  },
  GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES: {
    id: "GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES",
    numericId: 54,
    mapGroup: "DUNGEONS",
  },
  GOLDENROD_DEPT_STORE_B1F: {
    id: "GOLDENROD_DEPT_STORE_B1F",
    numericId: 55,
    mapGroup: "DUNGEONS",
  },
  GOLDENROD_UNDERGROUND_WAREHOUSE: {
    id: "GOLDENROD_UNDERGROUND_WAREHOUSE",
    numericId: 56,
    mapGroup: "DUNGEONS",
  },
  MOUNT_MORTAR_1F_OUTSIDE: {
    id: "MOUNT_MORTAR_1F_OUTSIDE",
    numericId: 57,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 10,
    fishingGroup: "LAKE",
  },
  MOUNT_MORTAR_1F_INSIDE: {
    id: "MOUNT_MORTAR_1F_INSIDE",
    numericId: 58,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  MOUNT_MORTAR_2F_INSIDE: {
    id: "MOUNT_MORTAR_2F_INSIDE",
    numericId: 59,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 5,
    fishingGroup: "LAKE",
  },
  MOUNT_MORTAR_B1F: {
    id: "MOUNT_MORTAR_B1F",
    numericId: 60,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 5,
    fishingGroup: "LAKE",
  },
  ICE_PATH_1F: {
    id: "ICE_PATH_1F",
    numericId: 61,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  ICE_PATH_B1F: {
    id: "ICE_PATH_B1F",
    numericId: 62,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  ICE_PATH_B2F_MAHOGANY_SIDE: {
    id: "ICE_PATH_B2F_MAHOGANY_SIDE",
    numericId: 63,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  ICE_PATH_B2F_BLACKTHORN_SIDE: {
    id: "ICE_PATH_B2F_BLACKTHORN_SIDE",
    numericId: 64,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  ICE_PATH_B3F: {
    id: "ICE_PATH_B3F",
    numericId: 65,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      5,
      5,
      5,
    ],
  },
  WHIRL_ISLAND_NW: {
    id: "WHIRL_ISLAND_NW",
    numericId: 66,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  WHIRL_ISLAND_NE: {
    id: "WHIRL_ISLAND_NE",
    numericId: 67,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  WHIRL_ISLAND_SW: {
    id: "WHIRL_ISLAND_SW",
    numericId: 68,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 10,
    fishingGroup: "WHIRL_ISLANDS",
  },
  WHIRL_ISLAND_CAVE: {
    id: "WHIRL_ISLAND_CAVE",
    numericId: 69,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  WHIRL_ISLAND_SE: {
    id: "WHIRL_ISLAND_SE",
    numericId: 70,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  WHIRL_ISLAND_B1F: {
    id: "WHIRL_ISLAND_B1F",
    numericId: 71,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  WHIRL_ISLAND_B2F: {
    id: "WHIRL_ISLAND_B2F",
    numericId: 72,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 10,
    fishingGroup: "WHIRL_ISLANDS",
  },
  WHIRL_ISLAND_LUGIA_CHAMBER: {
    id: "WHIRL_ISLAND_LUGIA_CHAMBER",
    numericId: 73,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 10,
    fishingGroup: "WHIRL_ISLANDS",
  },
  SILVER_CAVE_ROOM_1: {
    id: "SILVER_CAVE_ROOM_1",
    numericId: 74,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  SILVER_CAVE_ROOM_2: {
    id: "SILVER_CAVE_ROOM_2",
    numericId: 75,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 5,
    fishingGroup: "LAKE",
  },
  SILVER_CAVE_ROOM_3: {
    id: "SILVER_CAVE_ROOM_3",
    numericId: 76,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  SILVER_CAVE_ITEM_ROOMS: {
    id: "SILVER_CAVE_ITEM_ROOMS",
    numericId: 77,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  DARK_CAVE_VIOLET_ENTRANCE: {
    id: "DARK_CAVE_VIOLET_ENTRANCE",
    numericId: 78,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      10,
      10,
      10,
    ],
    waterEncounterRate: 5,
    swarmEncounterRates: [
      10,
      10,
      10,
    ],
    fishingGroup: "LAKE",
  },
  DARK_CAVE_BLACKTHORN_ENTRANCE: {
    id: "DARK_CAVE_BLACKTHORN_ENTRANCE",
    numericId: 79,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      10,
      10,
      10,
    ],
    waterEncounterRate: 5,
    fishingGroup: "LAKE",
  },
  DRAGONS_DEN_1F: {
    id: "DRAGONS_DEN_1F",
    numericId: 80,
    mapGroup: "DUNGEONS",
  },
  DRAGONS_DEN_B1F: {
    id: "DRAGONS_DEN_B1F",
    numericId: 81,
    mapGroup: "DUNGEONS",
    encounterRegion: "JOHTO",
    waterEncounterRate: 10,
    fishingGroup: "DRATINI",
  },
  DRAGON_SHRINE: {
    id: "DRAGON_SHRINE",
    numericId: 82,
    mapGroup: "DUNGEONS",
  },
  TOHJO_FALLS: {
    id: "TOHJO_FALLS",
    numericId: 83,
    mapGroup: "DUNGEONS",
    encounterRegion: "KANTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 10,
    fishingGroup: "LAKE",
  },
  DIGLETTS_CAVE: {
    id: "DIGLETTS_CAVE",
    numericId: 84,
    mapGroup: "DUNGEONS",
    encounterRegion: "KANTO",
    landEncounterRates: [
      10,
      5,
      20,
    ],
  },
  MOUNT_MOON: {
    id: "MOUNT_MOON",
    numericId: 85,
    mapGroup: "DUNGEONS",
    encounterRegion: "KANTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  UNDERGROUND_PATH: {
    id: "UNDERGROUND_PATH",
    numericId: 86,
    mapGroup: "DUNGEONS",
  },
  ROCK_TUNNEL_1F: {
    id: "ROCK_TUNNEL_1F",
    numericId: 87,
    mapGroup: "DUNGEONS",
    encounterRegion: "KANTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  ROCK_TUNNEL_B1F: {
    id: "ROCK_TUNNEL_B1F",
    numericId: 88,
    mapGroup: "DUNGEONS",
    encounterRegion: "KANTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  SAFARI_ZONE_FUCHSIA_GATE_BETA: {
    id: "SAFARI_ZONE_FUCHSIA_GATE_BETA",
    numericId: 89,
    mapGroup: "DUNGEONS",
  },
  SAFARI_ZONE_BETA: {
    id: "SAFARI_ZONE_BETA",
    numericId: 90,
    mapGroup: "DUNGEONS",
  },
  VICTORY_ROAD: {
    id: "VICTORY_ROAD",
    numericId: 91,
    mapGroup: "DUNGEONS",
    encounterRegion: "KANTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
  },
  ECRUTEAK_TIN_TOWER_ENTRANCE: {
    id: "ECRUTEAK_TIN_TOWER_ENTRANCE",
    numericId: 1,
    mapGroup: "ECRUTEAK",
  },
  WISE_TRIOS_ROOM: {
    id: "WISE_TRIOS_ROOM",
    numericId: 2,
    mapGroup: "ECRUTEAK",
  },
  ECRUTEAK_POKECENTER_1F: {
    id: "ECRUTEAK_POKECENTER_1F",
    numericId: 3,
    mapGroup: "ECRUTEAK",
  },
  ECRUTEAK_LUGIA_SPEECH_HOUSE: {
    id: "ECRUTEAK_LUGIA_SPEECH_HOUSE",
    numericId: 4,
    mapGroup: "ECRUTEAK",
  },
  DANCE_THEATER: {
    id: "DANCE_THEATER",
    numericId: 5,
    mapGroup: "ECRUTEAK",
  },
  ECRUTEAK_MART: {
    id: "ECRUTEAK_MART",
    numericId: 6,
    mapGroup: "ECRUTEAK",
  },
  ECRUTEAK_GYM: {
    id: "ECRUTEAK_GYM",
    numericId: 7,
    mapGroup: "ECRUTEAK",
  },
  ECRUTEAK_ITEMFINDER_HOUSE: {
    id: "ECRUTEAK_ITEMFINDER_HOUSE",
    numericId: 8,
    mapGroup: "ECRUTEAK",
  },
  ECRUTEAK_CITY: {
    id: "ECRUTEAK_CITY",
    numericId: 9,
    mapGroup: "ECRUTEAK",
    encounterRegion: "JOHTO",
    waterEncounterRate: 5,
    fishingGroup: "POND",
    treeGroup: "CANYON",
  },
  BLACKTHORN_GYM_1F: {
    id: "BLACKTHORN_GYM_1F",
    numericId: 1,
    mapGroup: "BLACKTHORN",
  },
  BLACKTHORN_GYM_2F: {
    id: "BLACKTHORN_GYM_2F",
    numericId: 2,
    mapGroup: "BLACKTHORN",
  },
  BLACKTHORN_DRAGON_SPEECH_HOUSE: {
    id: "BLACKTHORN_DRAGON_SPEECH_HOUSE",
    numericId: 3,
    mapGroup: "BLACKTHORN",
  },
  BLACKTHORN_EMYS_HOUSE: {
    id: "BLACKTHORN_EMYS_HOUSE",
    numericId: 4,
    mapGroup: "BLACKTHORN",
  },
  BLACKTHORN_MART: {
    id: "BLACKTHORN_MART",
    numericId: 5,
    mapGroup: "BLACKTHORN",
  },
  BLACKTHORN_POKECENTER_1F: {
    id: "BLACKTHORN_POKECENTER_1F",
    numericId: 6,
    mapGroup: "BLACKTHORN",
  },
  MOVE_DELETERS_HOUSE: {
    id: "MOVE_DELETERS_HOUSE",
    numericId: 7,
    mapGroup: "BLACKTHORN",
  },
  ROUTE_45: {
    id: "ROUTE_45",
    numericId: 8,
    mapGroup: "BLACKTHORN",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "DRATINI_2",
  },
  ROUTE_46: {
    id: "ROUTE_46",
    numericId: 9,
    mapGroup: "BLACKTHORN",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  BLACKTHORN_CITY: {
    id: "BLACKTHORN_CITY",
    numericId: 10,
    mapGroup: "BLACKTHORN",
    encounterRegion: "JOHTO",
    waterEncounterRate: 10,
    fishingGroup: "POND",
  },
  CINNABAR_POKECENTER_1F: {
    id: "CINNABAR_POKECENTER_1F",
    numericId: 1,
    mapGroup: "CINNABAR",
  },
  CINNABAR_POKECENTER_2F_BETA: {
    id: "CINNABAR_POKECENTER_2F_BETA",
    numericId: 2,
    mapGroup: "CINNABAR",
  },
  ROUTE_19_FUCHSIA_GATE: {
    id: "ROUTE_19_FUCHSIA_GATE",
    numericId: 3,
    mapGroup: "CINNABAR",
  },
  SEAFOAM_GYM: {
    id: "SEAFOAM_GYM",
    numericId: 4,
    mapGroup: "CINNABAR",
  },
  ROUTE_19: {
    id: "ROUTE_19",
    numericId: 5,
    mapGroup: "CINNABAR",
    encounterRegion: "KANTO",
    waterEncounterRate: 15,
    fishingGroup: "SHORE",
  },
  ROUTE_20: {
    id: "ROUTE_20",
    numericId: 6,
    mapGroup: "CINNABAR",
    encounterRegion: "KANTO",
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
  },
  ROUTE_21: {
    id: "ROUTE_21",
    numericId: 7,
    mapGroup: "CINNABAR",
    encounterRegion: "KANTO",
    landEncounterRates: [
      15,
      15,
      15,
    ],
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
  },
  CINNABAR_ISLAND: {
    id: "CINNABAR_ISLAND",
    numericId: 8,
    mapGroup: "CINNABAR",
    encounterRegion: "KANTO",
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
  },
  CERULEAN_GYM_BADGE_SPEECH_HOUSE: {
    id: "CERULEAN_GYM_BADGE_SPEECH_HOUSE",
    numericId: 1,
    mapGroup: "CERULEAN",
  },
  CERULEAN_POLICE_STATION: {
    id: "CERULEAN_POLICE_STATION",
    numericId: 2,
    mapGroup: "CERULEAN",
  },
  CERULEAN_TRADE_SPEECH_HOUSE: {
    id: "CERULEAN_TRADE_SPEECH_HOUSE",
    numericId: 3,
    mapGroup: "CERULEAN",
  },
  CERULEAN_POKECENTER_1F: {
    id: "CERULEAN_POKECENTER_1F",
    numericId: 4,
    mapGroup: "CERULEAN",
  },
  CERULEAN_POKECENTER_2F_BETA: {
    id: "CERULEAN_POKECENTER_2F_BETA",
    numericId: 5,
    mapGroup: "CERULEAN",
  },
  CERULEAN_GYM: {
    id: "CERULEAN_GYM",
    numericId: 6,
    mapGroup: "CERULEAN",
  },
  CERULEAN_MART: {
    id: "CERULEAN_MART",
    numericId: 7,
    mapGroup: "CERULEAN",
  },
  ROUTE_10_POKECENTER_1F: {
    id: "ROUTE_10_POKECENTER_1F",
    numericId: 8,
    mapGroup: "CERULEAN",
  },
  ROUTE_10_POKECENTER_2F_BETA: {
    id: "ROUTE_10_POKECENTER_2F_BETA",
    numericId: 9,
    mapGroup: "CERULEAN",
  },
  POWER_PLANT: {
    id: "POWER_PLANT",
    numericId: 10,
    mapGroup: "CERULEAN",
  },
  BILLS_HOUSE: {
    id: "BILLS_HOUSE",
    numericId: 11,
    mapGroup: "CERULEAN",
  },
  ROUTE_4: {
    id: "ROUTE_4",
    numericId: 12,
    mapGroup: "CERULEAN",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 10,
  },
  ROUTE_9: {
    id: "ROUTE_9",
    numericId: 13,
    mapGroup: "CERULEAN",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 10,
    fishingGroup: "LAKE",
  },
  ROUTE_10_NORTH: {
    id: "ROUTE_10_NORTH",
    numericId: 14,
    mapGroup: "CERULEAN",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 10,
    fishingGroup: "LAKE",
  },
  ROUTE_24: {
    id: "ROUTE_24",
    numericId: 15,
    mapGroup: "CERULEAN",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 10,
    fishingGroup: "LAKE",
  },
  ROUTE_25: {
    id: "ROUTE_25",
    numericId: 16,
    mapGroup: "CERULEAN",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 10,
    fishingGroup: "LAKE",
  },
  CERULEAN_CITY: {
    id: "CERULEAN_CITY",
    numericId: 17,
    mapGroup: "CERULEAN",
    encounterRegion: "KANTO",
    waterEncounterRate: 10,
  },
  AZALEA_POKECENTER_1F: {
    id: "AZALEA_POKECENTER_1F",
    numericId: 1,
    mapGroup: "AZALEA",
  },
  CHARCOAL_KILN: {
    id: "CHARCOAL_KILN",
    numericId: 2,
    mapGroup: "AZALEA",
  },
  AZALEA_MART: {
    id: "AZALEA_MART",
    numericId: 3,
    mapGroup: "AZALEA",
  },
  KURTS_HOUSE: {
    id: "KURTS_HOUSE",
    numericId: 4,
    mapGroup: "AZALEA",
  },
  AZALEA_GYM: {
    id: "AZALEA_GYM",
    numericId: 5,
    mapGroup: "AZALEA",
  },
  ROUTE_33: {
    id: "ROUTE_33",
    numericId: 6,
    mapGroup: "AZALEA",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    treeGroup: "TOWN",
  },
  AZALEA_TOWN: {
    id: "AZALEA_TOWN",
    numericId: 7,
    mapGroup: "AZALEA",
    treeGroup: "TOWN",
  },
  LAKE_OF_RAGE_HIDDEN_POWER_HOUSE: {
    id: "LAKE_OF_RAGE_HIDDEN_POWER_HOUSE",
    numericId: 1,
    mapGroup: "LAKE_OF_RAGE",
  },
  LAKE_OF_RAGE_MAGIKARP_HOUSE: {
    id: "LAKE_OF_RAGE_MAGIKARP_HOUSE",
    numericId: 2,
    mapGroup: "LAKE_OF_RAGE",
  },
  ROUTE_43_MAHOGANY_GATE: {
    id: "ROUTE_43_MAHOGANY_GATE",
    numericId: 3,
    mapGroup: "LAKE_OF_RAGE",
  },
  ROUTE_43_GATE: {
    id: "ROUTE_43_GATE",
    numericId: 4,
    mapGroup: "LAKE_OF_RAGE",
  },
  ROUTE_43: {
    id: "ROUTE_43",
    numericId: 5,
    mapGroup: "LAKE_OF_RAGE",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
    treeGroup: "LAKE",
  },
  LAKE_OF_RAGE: {
    id: "LAKE_OF_RAGE",
    numericId: 6,
    mapGroup: "LAKE_OF_RAGE",
    encounterRegion: "JOHTO",
    waterEncounterRate: 15,
    fishingGroup: "GYARADOS",
    treeGroup: "LAKE",
  },
  ROUTE_32: {
    id: "ROUTE_32",
    numericId: 1,
    mapGroup: "VIOLET",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 15,
    fishingGroup: "QWILFISH",
    treeGroup: "KANTO",
  },
  ROUTE_35: {
    id: "ROUTE_35",
    numericId: 2,
    mapGroup: "VIOLET",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 10,
    swarmEncounterRates: [
      25,
      25,
      25,
    ],
    fishingGroup: "POND",
    treeGroup: "ROUTE",
  },
  ROUTE_36: {
    id: "ROUTE_36",
    numericId: 3,
    mapGroup: "VIOLET",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    treeGroup: "ROUTE",
  },
  ROUTE_37: {
    id: "ROUTE_37",
    numericId: 4,
    mapGroup: "VIOLET",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    treeGroup: "ROUTE",
  },
  VIOLET_CITY: {
    id: "VIOLET_CITY",
    numericId: 5,
    mapGroup: "VIOLET",
    encounterRegion: "JOHTO",
    waterEncounterRate: 5,
    fishingGroup: "POND",
    treeGroup: "CANYON",
  },
  VIOLET_MART: {
    id: "VIOLET_MART",
    numericId: 6,
    mapGroup: "VIOLET",
  },
  VIOLET_GYM: {
    id: "VIOLET_GYM",
    numericId: 7,
    mapGroup: "VIOLET",
  },
  EARLS_POKEMON_ACADEMY: {
    id: "EARLS_POKEMON_ACADEMY",
    numericId: 8,
    mapGroup: "VIOLET",
  },
  VIOLET_NICKNAME_SPEECH_HOUSE: {
    id: "VIOLET_NICKNAME_SPEECH_HOUSE",
    numericId: 9,
    mapGroup: "VIOLET",
  },
  VIOLET_POKECENTER_1F: {
    id: "VIOLET_POKECENTER_1F",
    numericId: 10,
    mapGroup: "VIOLET",
  },
  VIOLET_KYLES_HOUSE: {
    id: "VIOLET_KYLES_HOUSE",
    numericId: 11,
    mapGroup: "VIOLET",
  },
  ROUTE_32_RUINS_OF_ALPH_GATE: {
    id: "ROUTE_32_RUINS_OF_ALPH_GATE",
    numericId: 12,
    mapGroup: "VIOLET",
  },
  ROUTE_32_POKECENTER_1F: {
    id: "ROUTE_32_POKECENTER_1F",
    numericId: 13,
    mapGroup: "VIOLET",
  },
  ROUTE_35_GOLDENROD_GATE: {
    id: "ROUTE_35_GOLDENROD_GATE",
    numericId: 14,
    mapGroup: "VIOLET",
  },
  ROUTE_35_NATIONAL_PARK_GATE: {
    id: "ROUTE_35_NATIONAL_PARK_GATE",
    numericId: 15,
    mapGroup: "VIOLET",
  },
  ROUTE_36_RUINS_OF_ALPH_GATE: {
    id: "ROUTE_36_RUINS_OF_ALPH_GATE",
    numericId: 16,
    mapGroup: "VIOLET",
  },
  ROUTE_36_NATIONAL_PARK_GATE: {
    id: "ROUTE_36_NATIONAL_PARK_GATE",
    numericId: 17,
    mapGroup: "VIOLET",
  },
  ROUTE_34: {
    id: "ROUTE_34",
    numericId: 1,
    mapGroup: "GOLDENROD",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 15,
    fishingGroup: "SHORE",
    treeGroup: "ROUTE",
  },
  GOLDENROD_CITY: {
    id: "GOLDENROD_CITY",
    numericId: 2,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_GYM: {
    id: "GOLDENROD_GYM",
    numericId: 3,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_BIKE_SHOP: {
    id: "GOLDENROD_BIKE_SHOP",
    numericId: 4,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_HAPPINESS_RATER: {
    id: "GOLDENROD_HAPPINESS_RATER",
    numericId: 5,
    mapGroup: "GOLDENROD",
  },
  BILLS_FAMILYS_HOUSE: {
    id: "BILLS_FAMILYS_HOUSE",
    numericId: 6,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_MAGNET_TRAIN_STATION: {
    id: "GOLDENROD_MAGNET_TRAIN_STATION",
    numericId: 7,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_FLOWER_SHOP: {
    id: "GOLDENROD_FLOWER_SHOP",
    numericId: 8,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_PP_SPEECH_HOUSE: {
    id: "GOLDENROD_PP_SPEECH_HOUSE",
    numericId: 9,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_NAME_RATER: {
    id: "GOLDENROD_NAME_RATER",
    numericId: 10,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_DEPT_STORE_1F: {
    id: "GOLDENROD_DEPT_STORE_1F",
    numericId: 11,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_DEPT_STORE_2F: {
    id: "GOLDENROD_DEPT_STORE_2F",
    numericId: 12,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_DEPT_STORE_3F: {
    id: "GOLDENROD_DEPT_STORE_3F",
    numericId: 13,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_DEPT_STORE_4F: {
    id: "GOLDENROD_DEPT_STORE_4F",
    numericId: 14,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_DEPT_STORE_5F: {
    id: "GOLDENROD_DEPT_STORE_5F",
    numericId: 15,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_DEPT_STORE_6F: {
    id: "GOLDENROD_DEPT_STORE_6F",
    numericId: 16,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_DEPT_STORE_ELEVATOR: {
    id: "GOLDENROD_DEPT_STORE_ELEVATOR",
    numericId: 17,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_DEPT_STORE_ROOF: {
    id: "GOLDENROD_DEPT_STORE_ROOF",
    numericId: 18,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_GAME_CORNER: {
    id: "GOLDENROD_GAME_CORNER",
    numericId: 19,
    mapGroup: "GOLDENROD",
  },
  GOLDENROD_POKECENTER_1F: {
    id: "GOLDENROD_POKECENTER_1F",
    numericId: 20,
    mapGroup: "GOLDENROD",
  },
  POKECOM_CENTER_ADMIN_OFFICE_MOBILE: {
    id: "POKECOM_CENTER_ADMIN_OFFICE_MOBILE",
    numericId: 21,
    mapGroup: "GOLDENROD",
  },
  ILEX_FOREST_AZALEA_GATE: {
    id: "ILEX_FOREST_AZALEA_GATE",
    numericId: 22,
    mapGroup: "GOLDENROD",
  },
  ROUTE_34_ILEX_FOREST_GATE: {
    id: "ROUTE_34_ILEX_FOREST_GATE",
    numericId: 23,
    mapGroup: "GOLDENROD",
  },
  DAY_CARE: {
    id: "DAY_CARE",
    numericId: 24,
    mapGroup: "GOLDENROD",
  },
  ROUTE_6: {
    id: "ROUTE_6",
    numericId: 1,
    mapGroup: "VERMILION",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
  },
  ROUTE_11: {
    id: "ROUTE_11",
    numericId: 2,
    mapGroup: "VERMILION",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  VERMILION_CITY: {
    id: "VERMILION_CITY",
    numericId: 3,
    mapGroup: "VERMILION",
    encounterRegion: "KANTO",
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
  },
  VERMILION_FISHING_SPEECH_HOUSE: {
    id: "VERMILION_FISHING_SPEECH_HOUSE",
    numericId: 4,
    mapGroup: "VERMILION",
  },
  VERMILION_POKECENTER_1F: {
    id: "VERMILION_POKECENTER_1F",
    numericId: 5,
    mapGroup: "VERMILION",
  },
  VERMILION_POKECENTER_2F_BETA: {
    id: "VERMILION_POKECENTER_2F_BETA",
    numericId: 6,
    mapGroup: "VERMILION",
  },
  POKEMON_FAN_CLUB: {
    id: "POKEMON_FAN_CLUB",
    numericId: 7,
    mapGroup: "VERMILION",
  },
  VERMILION_MAGNET_TRAIN_SPEECH_HOUSE: {
    id: "VERMILION_MAGNET_TRAIN_SPEECH_HOUSE",
    numericId: 8,
    mapGroup: "VERMILION",
  },
  VERMILION_MART: {
    id: "VERMILION_MART",
    numericId: 9,
    mapGroup: "VERMILION",
  },
  VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE: {
    id: "VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE",
    numericId: 10,
    mapGroup: "VERMILION",
  },
  VERMILION_GYM: {
    id: "VERMILION_GYM",
    numericId: 11,
    mapGroup: "VERMILION",
  },
  ROUTE_6_SAFFRON_GATE: {
    id: "ROUTE_6_SAFFRON_GATE",
    numericId: 12,
    mapGroup: "VERMILION",
  },
  ROUTE_6_UNDERGROUND_PATH_ENTRANCE: {
    id: "ROUTE_6_UNDERGROUND_PATH_ENTRANCE",
    numericId: 13,
    mapGroup: "VERMILION",
  },
  ROUTE_1: {
    id: "ROUTE_1",
    numericId: 1,
    mapGroup: "PALLET",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  PALLET_TOWN: {
    id: "PALLET_TOWN",
    numericId: 2,
    mapGroup: "PALLET",
    encounterRegion: "KANTO",
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
  },
  REDS_HOUSE_1F: {
    id: "REDS_HOUSE_1F",
    numericId: 3,
    mapGroup: "PALLET",
  },
  REDS_HOUSE_2F: {
    id: "REDS_HOUSE_2F",
    numericId: 4,
    mapGroup: "PALLET",
  },
  BLUES_HOUSE: {
    id: "BLUES_HOUSE",
    numericId: 5,
    mapGroup: "PALLET",
  },
  OAKS_LAB: {
    id: "OAKS_LAB",
    numericId: 6,
    mapGroup: "PALLET",
  },
  ROUTE_3: {
    id: "ROUTE_3",
    numericId: 1,
    mapGroup: "PEWTER",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  PEWTER_CITY: {
    id: "PEWTER_CITY",
    numericId: 2,
    mapGroup: "PEWTER",
  },
  PEWTER_NIDORAN_SPEECH_HOUSE: {
    id: "PEWTER_NIDORAN_SPEECH_HOUSE",
    numericId: 3,
    mapGroup: "PEWTER",
  },
  PEWTER_GYM: {
    id: "PEWTER_GYM",
    numericId: 4,
    mapGroup: "PEWTER",
  },
  PEWTER_MART: {
    id: "PEWTER_MART",
    numericId: 5,
    mapGroup: "PEWTER",
  },
  PEWTER_POKECENTER_1F: {
    id: "PEWTER_POKECENTER_1F",
    numericId: 6,
    mapGroup: "PEWTER",
  },
  PEWTER_POKECENTER_2F_BETA: {
    id: "PEWTER_POKECENTER_2F_BETA",
    numericId: 7,
    mapGroup: "PEWTER",
  },
  PEWTER_SNOOZE_SPEECH_HOUSE: {
    id: "PEWTER_SNOOZE_SPEECH_HOUSE",
    numericId: 8,
    mapGroup: "PEWTER",
  },
  OLIVINE_PORT: {
    id: "OLIVINE_PORT",
    numericId: 1,
    mapGroup: "FAST_SHIP",
    encounterRegion: "JOHTO",
    waterEncounterRate: 5,
    fishingGroup: "OCEAN",
  },
  VERMILION_PORT: {
    id: "VERMILION_PORT",
    numericId: 2,
    mapGroup: "FAST_SHIP",
    encounterRegion: "KANTO",
    waterEncounterRate: 5,
    fishingGroup: "OCEAN",
  },
  FAST_SHIP_1F: {
    id: "FAST_SHIP_1F",
    numericId: 3,
    mapGroup: "FAST_SHIP",
  },
  FAST_SHIP_CABINS_NNW_NNE_NE: {
    id: "FAST_SHIP_CABINS_NNW_NNE_NE",
    numericId: 4,
    mapGroup: "FAST_SHIP",
  },
  FAST_SHIP_CABINS_SW_SSW_NW: {
    id: "FAST_SHIP_CABINS_SW_SSW_NW",
    numericId: 5,
    mapGroup: "FAST_SHIP",
  },
  FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN: {
    id: "FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN",
    numericId: 6,
    mapGroup: "FAST_SHIP",
  },
  FAST_SHIP_B1F: {
    id: "FAST_SHIP_B1F",
    numericId: 7,
    mapGroup: "FAST_SHIP",
  },
  OLIVINE_PORT_PASSAGE: {
    id: "OLIVINE_PORT_PASSAGE",
    numericId: 8,
    mapGroup: "FAST_SHIP",
  },
  VERMILION_PORT_PASSAGE: {
    id: "VERMILION_PORT_PASSAGE",
    numericId: 9,
    mapGroup: "FAST_SHIP",
  },
  MOUNT_MOON_SQUARE: {
    id: "MOUNT_MOON_SQUARE",
    numericId: 10,
    mapGroup: "FAST_SHIP",
  },
  MOUNT_MOON_GIFT_SHOP: {
    id: "MOUNT_MOON_GIFT_SHOP",
    numericId: 11,
    mapGroup: "FAST_SHIP",
  },
  TIN_TOWER_ROOF: {
    id: "TIN_TOWER_ROOF",
    numericId: 12,
    mapGroup: "FAST_SHIP",
  },
  ROUTE_23: {
    id: "ROUTE_23",
    numericId: 1,
    mapGroup: "INDIGO",
  },
  INDIGO_PLATEAU_POKECENTER_1F: {
    id: "INDIGO_PLATEAU_POKECENTER_1F",
    numericId: 2,
    mapGroup: "INDIGO",
  },
  WILLS_ROOM: {
    id: "WILLS_ROOM",
    numericId: 3,
    mapGroup: "INDIGO",
  },
  KOGAS_ROOM: {
    id: "KOGAS_ROOM",
    numericId: 4,
    mapGroup: "INDIGO",
  },
  BRUNOS_ROOM: {
    id: "BRUNOS_ROOM",
    numericId: 5,
    mapGroup: "INDIGO",
  },
  KARENS_ROOM: {
    id: "KARENS_ROOM",
    numericId: 6,
    mapGroup: "INDIGO",
  },
  LANCES_ROOM: {
    id: "LANCES_ROOM",
    numericId: 7,
    mapGroup: "INDIGO",
  },
  HALL_OF_FAME: {
    id: "HALL_OF_FAME",
    numericId: 8,
    mapGroup: "INDIGO",
  },
  ROUTE_13: {
    id: "ROUTE_13",
    numericId: 1,
    mapGroup: "FUCHSIA",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 15,
    fishingGroup: "QWILFISH",
  },
  ROUTE_14: {
    id: "ROUTE_14",
    numericId: 2,
    mapGroup: "FUCHSIA",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  ROUTE_15: {
    id: "ROUTE_15",
    numericId: 3,
    mapGroup: "FUCHSIA",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  ROUTE_18: {
    id: "ROUTE_18",
    numericId: 4,
    mapGroup: "FUCHSIA",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  FUCHSIA_CITY: {
    id: "FUCHSIA_CITY",
    numericId: 5,
    mapGroup: "FUCHSIA",
    encounterRegion: "KANTO",
    waterEncounterRate: 5,
    fishingGroup: "GYARADOS",
  },
  FUCHSIA_MART: {
    id: "FUCHSIA_MART",
    numericId: 6,
    mapGroup: "FUCHSIA",
  },
  SAFARI_ZONE_MAIN_OFFICE: {
    id: "SAFARI_ZONE_MAIN_OFFICE",
    numericId: 7,
    mapGroup: "FUCHSIA",
  },
  FUCHSIA_GYM: {
    id: "FUCHSIA_GYM",
    numericId: 8,
    mapGroup: "FUCHSIA",
  },
  BILLS_BROTHERS_HOUSE: {
    id: "BILLS_BROTHERS_HOUSE",
    numericId: 9,
    mapGroup: "FUCHSIA",
  },
  FUCHSIA_POKECENTER_1F: {
    id: "FUCHSIA_POKECENTER_1F",
    numericId: 10,
    mapGroup: "FUCHSIA",
  },
  FUCHSIA_POKECENTER_2F_BETA: {
    id: "FUCHSIA_POKECENTER_2F_BETA",
    numericId: 11,
    mapGroup: "FUCHSIA",
  },
  SAFARI_ZONE_WARDENS_HOME: {
    id: "SAFARI_ZONE_WARDENS_HOME",
    numericId: 12,
    mapGroup: "FUCHSIA",
  },
  ROUTE_15_FUCHSIA_GATE: {
    id: "ROUTE_15_FUCHSIA_GATE",
    numericId: 13,
    mapGroup: "FUCHSIA",
  },
  ROUTE_8: {
    id: "ROUTE_8",
    numericId: 1,
    mapGroup: "LAVENDER",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  ROUTE_12: {
    id: "ROUTE_12",
    numericId: 2,
    mapGroup: "LAVENDER",
    encounterRegion: "KANTO",
    waterEncounterRate: 15,
    fishingGroup: "QWILFISH",
  },
  ROUTE_10_SOUTH: {
    id: "ROUTE_10_SOUTH",
    numericId: 3,
    mapGroup: "LAVENDER",
  },
  LAVENDER_TOWN: {
    id: "LAVENDER_TOWN",
    numericId: 4,
    mapGroup: "LAVENDER",
  },
  LAVENDER_POKECENTER_1F: {
    id: "LAVENDER_POKECENTER_1F",
    numericId: 5,
    mapGroup: "LAVENDER",
  },
  LAVENDER_POKECENTER_2F_BETA: {
    id: "LAVENDER_POKECENTER_2F_BETA",
    numericId: 6,
    mapGroup: "LAVENDER",
  },
  MR_FUJIS_HOUSE: {
    id: "MR_FUJIS_HOUSE",
    numericId: 7,
    mapGroup: "LAVENDER",
  },
  LAVENDER_SPEECH_HOUSE: {
    id: "LAVENDER_SPEECH_HOUSE",
    numericId: 8,
    mapGroup: "LAVENDER",
  },
  LAVENDER_NAME_RATER: {
    id: "LAVENDER_NAME_RATER",
    numericId: 9,
    mapGroup: "LAVENDER",
  },
  LAVENDER_MART: {
    id: "LAVENDER_MART",
    numericId: 10,
    mapGroup: "LAVENDER",
  },
  SOUL_HOUSE: {
    id: "SOUL_HOUSE",
    numericId: 11,
    mapGroup: "LAVENDER",
  },
  LAV_RADIO_TOWER_1F: {
    id: "LAV_RADIO_TOWER_1F",
    numericId: 12,
    mapGroup: "LAVENDER",
  },
  ROUTE_8_SAFFRON_GATE: {
    id: "ROUTE_8_SAFFRON_GATE",
    numericId: 13,
    mapGroup: "LAVENDER",
  },
  ROUTE_12_SUPER_ROD_HOUSE: {
    id: "ROUTE_12_SUPER_ROD_HOUSE",
    numericId: 14,
    mapGroup: "LAVENDER",
  },
  ROUTE_28: {
    id: "ROUTE_28",
    numericId: 1,
    mapGroup: "SILVER",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
  },
  SILVER_CAVE_OUTSIDE: {
    id: "SILVER_CAVE_OUTSIDE",
    numericId: 2,
    mapGroup: "SILVER",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
  },
  SILVER_CAVE_POKECENTER_1F: {
    id: "SILVER_CAVE_POKECENTER_1F",
    numericId: 3,
    mapGroup: "SILVER",
  },
  ROUTE_28_STEEL_WING_HOUSE: {
    id: "ROUTE_28_STEEL_WING_HOUSE",
    numericId: 4,
    mapGroup: "SILVER",
  },
  POKECENTER_2F: {
    id: "POKECENTER_2F",
    numericId: 1,
    mapGroup: "CABLE_CLUB",
  },
  TRADE_CENTER: {
    id: "TRADE_CENTER",
    numericId: 2,
    mapGroup: "CABLE_CLUB",
  },
  COLOSSEUM: {
    id: "COLOSSEUM",
    numericId: 3,
    mapGroup: "CABLE_CLUB",
  },
  TIME_CAPSULE: {
    id: "TIME_CAPSULE",
    numericId: 4,
    mapGroup: "CABLE_CLUB",
  },
  MOBILE_TRADE_ROOM: {
    id: "MOBILE_TRADE_ROOM",
    numericId: 5,
    mapGroup: "CABLE_CLUB",
  },
  MOBILE_BATTLE_ROOM: {
    id: "MOBILE_BATTLE_ROOM",
    numericId: 6,
    mapGroup: "CABLE_CLUB",
  },
  ROUTE_7: {
    id: "ROUTE_7",
    numericId: 1,
    mapGroup: "CELADON",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  ROUTE_16: {
    id: "ROUTE_16",
    numericId: 2,
    mapGroup: "CELADON",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  ROUTE_17: {
    id: "ROUTE_17",
    numericId: 3,
    mapGroup: "CELADON",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  CELADON_CITY: {
    id: "CELADON_CITY",
    numericId: 4,
    mapGroup: "CELADON",
    encounterRegion: "KANTO",
    waterEncounterRate: 5,
  },
  CELADON_DEPT_STORE_1F: {
    id: "CELADON_DEPT_STORE_1F",
    numericId: 5,
    mapGroup: "CELADON",
  },
  CELADON_DEPT_STORE_2F: {
    id: "CELADON_DEPT_STORE_2F",
    numericId: 6,
    mapGroup: "CELADON",
  },
  CELADON_DEPT_STORE_3F: {
    id: "CELADON_DEPT_STORE_3F",
    numericId: 7,
    mapGroup: "CELADON",
  },
  CELADON_DEPT_STORE_4F: {
    id: "CELADON_DEPT_STORE_4F",
    numericId: 8,
    mapGroup: "CELADON",
  },
  CELADON_DEPT_STORE_5F: {
    id: "CELADON_DEPT_STORE_5F",
    numericId: 9,
    mapGroup: "CELADON",
  },
  CELADON_DEPT_STORE_6F: {
    id: "CELADON_DEPT_STORE_6F",
    numericId: 10,
    mapGroup: "CELADON",
  },
  CELADON_DEPT_STORE_ELEVATOR: {
    id: "CELADON_DEPT_STORE_ELEVATOR",
    numericId: 11,
    mapGroup: "CELADON",
  },
  CELADON_MANSION_1F: {
    id: "CELADON_MANSION_1F",
    numericId: 12,
    mapGroup: "CELADON",
  },
  CELADON_MANSION_2F: {
    id: "CELADON_MANSION_2F",
    numericId: 13,
    mapGroup: "CELADON",
  },
  CELADON_MANSION_3F: {
    id: "CELADON_MANSION_3F",
    numericId: 14,
    mapGroup: "CELADON",
  },
  CELADON_MANSION_ROOF: {
    id: "CELADON_MANSION_ROOF",
    numericId: 15,
    mapGroup: "CELADON",
  },
  CELADON_MANSION_ROOF_HOUSE: {
    id: "CELADON_MANSION_ROOF_HOUSE",
    numericId: 16,
    mapGroup: "CELADON",
  },
  CELADON_POKECENTER_1F: {
    id: "CELADON_POKECENTER_1F",
    numericId: 17,
    mapGroup: "CELADON",
  },
  CELADON_POKECENTER_2F_BETA: {
    id: "CELADON_POKECENTER_2F_BETA",
    numericId: 18,
    mapGroup: "CELADON",
  },
  CELADON_GAME_CORNER: {
    id: "CELADON_GAME_CORNER",
    numericId: 19,
    mapGroup: "CELADON",
  },
  CELADON_GAME_CORNER_PRIZE_ROOM: {
    id: "CELADON_GAME_CORNER_PRIZE_ROOM",
    numericId: 20,
    mapGroup: "CELADON",
  },
  CELADON_GYM: {
    id: "CELADON_GYM",
    numericId: 21,
    mapGroup: "CELADON",
  },
  CELADON_CAFE: {
    id: "CELADON_CAFE",
    numericId: 22,
    mapGroup: "CELADON",
  },
  ROUTE_16_FUCHSIA_SPEECH_HOUSE: {
    id: "ROUTE_16_FUCHSIA_SPEECH_HOUSE",
    numericId: 23,
    mapGroup: "CELADON",
  },
  ROUTE_16_GATE: {
    id: "ROUTE_16_GATE",
    numericId: 24,
    mapGroup: "CELADON",
  },
  ROUTE_7_SAFFRON_GATE: {
    id: "ROUTE_7_SAFFRON_GATE",
    numericId: 25,
    mapGroup: "CELADON",
  },
  ROUTE_17_ROUTE_18_GATE: {
    id: "ROUTE_17_ROUTE_18_GATE",
    numericId: 26,
    mapGroup: "CELADON",
  },
  ROUTE_40: {
    id: "ROUTE_40",
    numericId: 1,
    mapGroup: "CIANWOOD",
    encounterRegion: "JOHTO",
    waterEncounterRate: 15,
    fishingGroup: "SHORE",
  },
  ROUTE_41: {
    id: "ROUTE_41",
    numericId: 2,
    mapGroup: "CIANWOOD",
    encounterRegion: "JOHTO",
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
  },
  CIANWOOD_CITY: {
    id: "CIANWOOD_CITY",
    numericId: 3,
    mapGroup: "CIANWOOD",
    encounterRegion: "JOHTO",
    waterEncounterRate: 15,
    fishingGroup: "SHORE",
  },
  MANIAS_HOUSE: {
    id: "MANIAS_HOUSE",
    numericId: 4,
    mapGroup: "CIANWOOD",
  },
  CIANWOOD_GYM: {
    id: "CIANWOOD_GYM",
    numericId: 5,
    mapGroup: "CIANWOOD",
  },
  CIANWOOD_POKECENTER_1F: {
    id: "CIANWOOD_POKECENTER_1F",
    numericId: 6,
    mapGroup: "CIANWOOD",
  },
  CIANWOOD_PHARMACY: {
    id: "CIANWOOD_PHARMACY",
    numericId: 7,
    mapGroup: "CIANWOOD",
  },
  CIANWOOD_PHOTO_STUDIO: {
    id: "CIANWOOD_PHOTO_STUDIO",
    numericId: 8,
    mapGroup: "CIANWOOD",
  },
  CIANWOOD_LUGIA_SPEECH_HOUSE: {
    id: "CIANWOOD_LUGIA_SPEECH_HOUSE",
    numericId: 9,
    mapGroup: "CIANWOOD",
  },
  POKE_SEERS_HOUSE: {
    id: "POKE_SEERS_HOUSE",
    numericId: 10,
    mapGroup: "CIANWOOD",
  },
  BATTLE_TOWER_1F: {
    id: "BATTLE_TOWER_1F",
    numericId: 11,
    mapGroup: "CIANWOOD",
  },
  BATTLE_TOWER_BATTLE_ROOM: {
    id: "BATTLE_TOWER_BATTLE_ROOM",
    numericId: 12,
    mapGroup: "CIANWOOD",
  },
  BATTLE_TOWER_ELEVATOR: {
    id: "BATTLE_TOWER_ELEVATOR",
    numericId: 13,
    mapGroup: "CIANWOOD",
  },
  BATTLE_TOWER_HALLWAY: {
    id: "BATTLE_TOWER_HALLWAY",
    numericId: 14,
    mapGroup: "CIANWOOD",
  },
  ROUTE_40_BATTLE_TOWER_GATE: {
    id: "ROUTE_40_BATTLE_TOWER_GATE",
    numericId: 15,
    mapGroup: "CIANWOOD",
  },
  BATTLE_TOWER_OUTSIDE: {
    id: "BATTLE_TOWER_OUTSIDE",
    numericId: 16,
    mapGroup: "CIANWOOD",
  },
  ROUTE_2: {
    id: "ROUTE_2",
    numericId: 1,
    mapGroup: "VIRIDIAN",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  ROUTE_22: {
    id: "ROUTE_22",
    numericId: 2,
    mapGroup: "VIRIDIAN",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
  },
  VIRIDIAN_CITY: {
    id: "VIRIDIAN_CITY",
    numericId: 3,
    mapGroup: "VIRIDIAN",
    encounterRegion: "KANTO",
    waterEncounterRate: 5,
    fishingGroup: "POND",
  },
  VIRIDIAN_GYM: {
    id: "VIRIDIAN_GYM",
    numericId: 4,
    mapGroup: "VIRIDIAN",
  },
  VIRIDIAN_NICKNAME_SPEECH_HOUSE: {
    id: "VIRIDIAN_NICKNAME_SPEECH_HOUSE",
    numericId: 5,
    mapGroup: "VIRIDIAN",
  },
  TRAINER_HOUSE_1F: {
    id: "TRAINER_HOUSE_1F",
    numericId: 6,
    mapGroup: "VIRIDIAN",
  },
  TRAINER_HOUSE_B1F: {
    id: "TRAINER_HOUSE_B1F",
    numericId: 7,
    mapGroup: "VIRIDIAN",
  },
  VIRIDIAN_MART: {
    id: "VIRIDIAN_MART",
    numericId: 8,
    mapGroup: "VIRIDIAN",
  },
  VIRIDIAN_POKECENTER_1F: {
    id: "VIRIDIAN_POKECENTER_1F",
    numericId: 9,
    mapGroup: "VIRIDIAN",
  },
  VIRIDIAN_POKECENTER_2F_BETA: {
    id: "VIRIDIAN_POKECENTER_2F_BETA",
    numericId: 10,
    mapGroup: "VIRIDIAN",
  },
  ROUTE_2_NUGGET_HOUSE: {
    id: "ROUTE_2_NUGGET_HOUSE",
    numericId: 11,
    mapGroup: "VIRIDIAN",
  },
  ROUTE_2_GATE: {
    id: "ROUTE_2_GATE",
    numericId: 12,
    mapGroup: "VIRIDIAN",
  },
  VICTORY_ROAD_GATE: {
    id: "VICTORY_ROAD_GATE",
    numericId: 13,
    mapGroup: "VIRIDIAN",
  },
  ROUTE_26: {
    id: "ROUTE_26",
    numericId: 1,
    mapGroup: "NEW_BARK",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
    treeGroup: "KANTO",
  },
  ROUTE_27: {
    id: "ROUTE_27",
    numericId: 2,
    mapGroup: "NEW_BARK",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
    treeGroup: "KANTO",
  },
  ROUTE_29: {
    id: "ROUTE_29",
    numericId: 3,
    mapGroup: "NEW_BARK",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    treeGroup: "ROUTE",
  },
  NEW_BARK_TOWN: {
    id: "NEW_BARK_TOWN",
    numericId: 4,
    mapGroup: "NEW_BARK",
    encounterRegion: "JOHTO",
    waterEncounterRate: 15,
    fishingGroup: "OCEAN",
    treeGroup: "CANYON",
  },
  ELMS_LAB: {
    id: "ELMS_LAB",
    numericId: 5,
    mapGroup: "NEW_BARK",
  },
  PLAYERS_HOUSE_1F: {
    id: "PLAYERS_HOUSE_1F",
    numericId: 6,
    mapGroup: "NEW_BARK",
  },
  PLAYERS_HOUSE_2F: {
    id: "PLAYERS_HOUSE_2F",
    numericId: 7,
    mapGroup: "NEW_BARK",
  },
  PLAYERS_NEIGHBORS_HOUSE: {
    id: "PLAYERS_NEIGHBORS_HOUSE",
    numericId: 8,
    mapGroup: "NEW_BARK",
  },
  ELMS_HOUSE: {
    id: "ELMS_HOUSE",
    numericId: 9,
    mapGroup: "NEW_BARK",
  },
  ROUTE_26_HEAL_HOUSE: {
    id: "ROUTE_26_HEAL_HOUSE",
    numericId: 10,
    mapGroup: "NEW_BARK",
  },
  DAY_OF_WEEK_SIBLINGS_HOUSE: {
    id: "DAY_OF_WEEK_SIBLINGS_HOUSE",
    numericId: 11,
    mapGroup: "NEW_BARK",
  },
  ROUTE_27_SANDSTORM_HOUSE: {
    id: "ROUTE_27_SANDSTORM_HOUSE",
    numericId: 12,
    mapGroup: "NEW_BARK",
  },
  ROUTE_29_ROUTE_46_GATE: {
    id: "ROUTE_29_ROUTE_46_GATE",
    numericId: 13,
    mapGroup: "NEW_BARK",
  },
  ROUTE_5: {
    id: "ROUTE_5",
    numericId: 1,
    mapGroup: "SAFFRON",
    encounterRegion: "KANTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
  },
  SAFFRON_CITY: {
    id: "SAFFRON_CITY",
    numericId: 2,
    mapGroup: "SAFFRON",
  },
  FIGHTING_DOJO: {
    id: "FIGHTING_DOJO",
    numericId: 3,
    mapGroup: "SAFFRON",
  },
  SAFFRON_GYM: {
    id: "SAFFRON_GYM",
    numericId: 4,
    mapGroup: "SAFFRON",
  },
  SAFFRON_MART: {
    id: "SAFFRON_MART",
    numericId: 5,
    mapGroup: "SAFFRON",
  },
  SAFFRON_POKECENTER_1F: {
    id: "SAFFRON_POKECENTER_1F",
    numericId: 6,
    mapGroup: "SAFFRON",
  },
  SAFFRON_POKECENTER_2F_BETA: {
    id: "SAFFRON_POKECENTER_2F_BETA",
    numericId: 7,
    mapGroup: "SAFFRON",
  },
  MR_PSYCHICS_HOUSE: {
    id: "MR_PSYCHICS_HOUSE",
    numericId: 8,
    mapGroup: "SAFFRON",
  },
  SAFFRON_MAGNET_TRAIN_STATION: {
    id: "SAFFRON_MAGNET_TRAIN_STATION",
    numericId: 9,
    mapGroup: "SAFFRON",
  },
  SILPH_CO_1F: {
    id: "SILPH_CO_1F",
    numericId: 10,
    mapGroup: "SAFFRON",
  },
  COPYCATS_HOUSE_1F: {
    id: "COPYCATS_HOUSE_1F",
    numericId: 11,
    mapGroup: "SAFFRON",
  },
  COPYCATS_HOUSE_2F: {
    id: "COPYCATS_HOUSE_2F",
    numericId: 12,
    mapGroup: "SAFFRON",
  },
  ROUTE_5_UNDERGROUND_PATH_ENTRANCE: {
    id: "ROUTE_5_UNDERGROUND_PATH_ENTRANCE",
    numericId: 13,
    mapGroup: "SAFFRON",
  },
  ROUTE_5_SAFFRON_GATE: {
    id: "ROUTE_5_SAFFRON_GATE",
    numericId: 14,
    mapGroup: "SAFFRON",
  },
  ROUTE_5_CLEANSE_TAG_HOUSE: {
    id: "ROUTE_5_CLEANSE_TAG_HOUSE",
    numericId: 15,
    mapGroup: "SAFFRON",
  },
  ROUTE_30: {
    id: "ROUTE_30",
    numericId: 1,
    mapGroup: "CHERRYGROVE",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
    treeGroup: "ROUTE",
  },
  ROUTE_31: {
    id: "ROUTE_31",
    numericId: 2,
    mapGroup: "CHERRYGROVE",
    encounterRegion: "JOHTO",
    landEncounterRates: [
      25,
      25,
      25,
    ],
    waterEncounterRate: 5,
    fishingGroup: "POND",
    treeGroup: "ROUTE",
  },
  CHERRYGROVE_CITY: {
    id: "CHERRYGROVE_CITY",
    numericId: 3,
    mapGroup: "CHERRYGROVE",
    encounterRegion: "JOHTO",
    waterEncounterRate: 15,
    fishingGroup: "SHORE",
  },
  CHERRYGROVE_MART: {
    id: "CHERRYGROVE_MART",
    numericId: 4,
    mapGroup: "CHERRYGROVE",
  },
  CHERRYGROVE_POKECENTER_1F: {
    id: "CHERRYGROVE_POKECENTER_1F",
    numericId: 5,
    mapGroup: "CHERRYGROVE",
  },
  CHERRYGROVE_GYM_SPEECH_HOUSE: {
    id: "CHERRYGROVE_GYM_SPEECH_HOUSE",
    numericId: 6,
    mapGroup: "CHERRYGROVE",
  },
  GUIDE_GENTS_HOUSE: {
    id: "GUIDE_GENTS_HOUSE",
    numericId: 7,
    mapGroup: "CHERRYGROVE",
  },
  CHERRYGROVE_EVOLUTION_SPEECH_HOUSE: {
    id: "CHERRYGROVE_EVOLUTION_SPEECH_HOUSE",
    numericId: 8,
    mapGroup: "CHERRYGROVE",
  },
  ROUTE_30_BERRY_HOUSE: {
    id: "ROUTE_30_BERRY_HOUSE",
    numericId: 9,
    mapGroup: "CHERRYGROVE",
  },
  MR_POKEMONS_HOUSE: {
    id: "MR_POKEMONS_HOUSE",
    numericId: 10,
    mapGroup: "CHERRYGROVE",
  },
  ROUTE_31_VIOLET_GATE: {
    id: "ROUTE_31_VIOLET_GATE",
    numericId: 11,
    mapGroup: "CHERRYGROVE",
  },
}