import type { Item } from "@shared/types/gameData/item"
import type { ItemId } from "@shared/types/gameDataIds/items"

export const itemsMap: IdMap<ItemId, Item> = {
  POKEDEX: {
    id: "POKEDEX",
    type: "POKEDEX_PART",
    category: "MENU_ITEMS",
    numericId: 0x01,
    name: "Pokédex",
  },
  UNONWNDEX: {
    id: "UNONWNDEX",
    type: "POKEDEX_PART",
    category: "MENU_ITEMS",
    numericId: 0x02,
    name: "Unowndex",
  },
  POKEGEAR: {
    id: "POKEGEAR",
    type: "POKEGEAR_PART",
    category: "MENU_ITEMS",
    numericId: 0x84,
    name: "Pokégear",
  },
  MAP_CARD: {
    id: "MAP_CARD",
    type: "POKEGEAR_PART",
    category: "MENU_ITEMS",
    numericId: 0x01,
    name: "Map Card",
  },
  RADIO_CARD: {
    id: "RADIO_CARD",
    type: "POKEGEAR_PART",
    category: "MENU_ITEMS",
    numericId: 0x02,
    name: "Radio Card",
  },
  EXPN_CARD: {
    id: "EXPN_CARD",
    type: "POKEGEAR_PART",
    category: "MENU_ITEMS",
    numericId: 0x08,
    name: "Expn Card",
  },
  ZEPHYRBADGE: {
    id: "ZEPHYRBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x01,
    name: "Zephyrbadge (Flash)",
  },
  HIVEBADGE: {
    id: "HIVEBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x02,
    name: "Hivebadge (Cut)",
  },
  PLAINBADGE: {
    id: "PLAINBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x04,
    name: "Plainbadge (Strength)",
  },
  FOGBADGE: {
    id: "FOGBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x08,
    name: "Fogbadge (Surf)",
  },
  STORMBADGE: {
    id: "STORMBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x20,
    name: "Stormbadge (Fly)",
  },
  MINERALBADGE: {
    id: "MINERALBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x10,
    name: "Mineralbadge",
  },
  GLACIERBADGE: {
    id: "GLACIERBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x40,
    name: "Glacierbadge (Whirlpool)",
  },
  RISINGBADGE: {
    id: "RISINGBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x80,
    name: "Risingbadge (Waterfall)",
  },
  BOULDERBADGE: {
    id: "BOULDERBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x01,
    name: "Boulderbadge",
  },
  CASCADEBADGE: {
    id: "CASCADEBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x02,
    name: "Cascadebadge",
  },
  THUNDERBADGE: {
    id: "THUNDERBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x04,
    name: "Thunderbadge",
  },
  RAINBOWBADGE: {
    id: "RAINBOWBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x08,
    name: "Rainbowbadge",
  },
  SOULBADGE: {
    id: "SOULBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x10,
    name: "Soulbadge",
  },
  MARSHBADGE: {
    id: "MARSHBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x20,
    name: "Marshbadge",
  },
  VOLCANOBADGE: {
    id: "VOLCANOBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x40,
    name: "Volcanobadge",
  },
  EARTHBADGE: {
    id: "EARTHBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x80,
    name: "Earthbadge",
  },
  BASEMENT_KEY: {
    id: "BASEMENT_KEY",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x85,
    name: "Basement Key",
  },
  BICYCLE: {
    id: "BICYCLE",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x07,
    name: "Bicycle",
  },
  BLUE_CARD: {
    id: "BLUE_CARD",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x74,
    name: "Blue Card",
  },
  CARD_KEY: {
    id: "CARD_KEY",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x7F,
    name: "Card Key",
  },
  CLEAR_BELL: {
    id: "CLEAR_BELL",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x46,
    name: "Clear Bell",
  },
  COIN_CASE: {
    id: "COIN_CASE",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x36,
    name: "Coin Case",
  },
  EGG_TICKET: {
    id: "EGG_TICKET",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x81,
    name: "Egg Ticket",
  },
  GOOD_ROD: {
    id: "GOOD_ROD",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x3B,
    name: "Good Rod",
  },
  GS_BALL: {
    id: "GS_BALL",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x73,
    name: "GS Ball",
  },
  ITEMFINDER: {
    id: "ITEMFINDER",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x37,
    name: "Itemfinder",
  },
  LOST_ITEM: {
    id: "LOST_ITEM",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x82,
    name: "Lost Item",
  },
  MACHINE_PART: {
    id: "MACHINE_PART",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x80,
    name: "Machine Part",
  },
  MYSTERY_EGG: {
    id: "MYSTERY_EGG",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x45,
    name: "Mystery Egg",
  },
  OLD_ROD: {
    id: "OLD_ROD",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x3A,
    name: "Old Rod",
  },
  PASS: {
    id: "PASS",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x86,
    name: "Pass",
  },
  RAINBOW_WING: {
    id: "RAINBOW_WING",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0xB2,
    name: "Rainbow Wing",
  },
  RED_SCALE: {
    id: "RED_SCALE",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x42,
    name: "Red Scale",
  },
  SECRETPOTION: {
    id: "SECRETPOTION",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x43,
    name: "Secretpotion",
  },
  SILVER_WING: {
    id: "SILVER_WING",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x47,
    name: "Silver Wing",
  },
  SQUIRTBOTTLE: {
    id: "SQUIRTBOTTLE",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0xAF,
    name: "Squirtbottle",
  },
  S_S_TICKET: {
    id: "S_S_TICKET",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x44,
    name: "S.S.Ticket",
  },
  SUPER_ROD: {
    id: "SUPER_ROD",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x3D,
    name: "Super Rod",
  },
  HM01: {
    id: "HM01",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF3,
    name: "HM01 (Cut)",
  },
  HM02: {
    id: "HM02",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF4,
    name: "HM02 (Fly)",
  },
  HM03: {
    id: "HM03",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF5,
    name: "HM03 (Surf)",
  },
  HM04: {
    id: "HM04",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF6,
    name: "HM04 (Strength)",
  },
  HM05: {
    id: "HM05",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF7,
    name: "HM05 (Flash)",
  },
  HM06: {
    id: "HM06",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF8,
    name: "HM06 (Whirlpool)",
  },
  HM07: {
    id: "HM07",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF9,
    name: "HM07 (Waterfall)",
  },
  TM01: {
    id: "TM01",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xBF,
    name: "TM01",
  },
  TM02: {
    id: "TM02",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC0,
    name: "TM02 (Headbutt)",
  },
  TM03: {
    id: "TM03",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC1,
    name: "TM03",
  },
  TM04: {
    id: "TM04",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC2,
    name: "TM04",
  },
  TM05: {
    id: "TM05",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC4,
    name: "TM05",
  },
  TM06: {
    id: "TM06",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC5,
    name: "TM06",
  },
  TM07: {
    id: "TM07",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC6,
    name: "TM07",
  },
  TM08: {
    id: "TM08",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC7,
    name: "TM08 (Rock Smash)",
  },
  TM09: {
    id: "TM09",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC8,
    name: "TM09",
  },
  TM10: {
    id: "TM10",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC9,
    name: "TM10",
  },
  TM11: {
    id: "TM11",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCA,
    name: "TM11",
  },
  TM12: {
    id: "TM12",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCB,
    name: "TM12 (Sweet Scent)",
  },
  TM13: {
    id: "TM13",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCC,
    name: "TM13",
  },
  TM14: {
    id: "TM14",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCD,
    name: "TM14",
  },
  TM15: {
    id: "TM15",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCE,
    name: "TM15",
  },
  TM16: {
    id: "TM16",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCF,
    name: "TM16",
  },
  TM17: {
    id: "TM17",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD0,
    name: "TM17",
  },
  TM18: {
    id: "TM18",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD1,
    name: "TM18",
  },
  TM19: {
    id: "TM19",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD2,
    name: "TM19",
  },
  TM20: {
    id: "TM20",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD3,
    name: "TM20",
  },
  TM21: {
    id: "TM21",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD4,
    name: "TM21",
  },
  TM22: {
    id: "TM22",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD5,
    name: "TM22",
  },
  TM23: {
    id: "TM23",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD6,
    name: "TM23",
  },
  TM24: {
    id: "TM24",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD7,
    name: "TM24",
  },
  TM25: {
    id: "TM25",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD8,
    name: "TM25",
  },
  TM26: {
    id: "TM26",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD9,
    name: "TM26",
  },
  TM27: {
    id: "TM27",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDA,
    name: "TM27",
  },
  TM28: {
    id: "TM28",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDB,
    name: "TM28 (Dig)",
  },
  TM29: {
    id: "TM29",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDD,
    name: "TM29",
  },
  TM30: {
    id: "TM30",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDE,
    name: "TM30",
  },
  TM31: {
    id: "TM31",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDF,
    name: "TM31",
  },
  TM32: {
    id: "TM32",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE0,
    name: "TM32",
  },
  TM33: {
    id: "TM33",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE1,
    name: "TM33",
  },
  TM34: {
    id: "TM34",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE2,
    name: "TM34",
  },
  TM35: {
    id: "TM35",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE3,
    name: "TM35",
  },
  TM36: {
    id: "TM36",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE4,
    name: "TM36",
  },
  TM37: {
    id: "TM37",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE5,
    name: "TM37",
  },
  TM38: {
    id: "TM38",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE6,
    name: "TM38",
  },
  TM39: {
    id: "TM39",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE7,
    name: "TM39",
  },
  TM40: {
    id: "TM40",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE8,
    name: "TM40",
  },
  TM41: {
    id: "TM41",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE9,
    name: "TM41",
  },
  TM42: {
    id: "TM42",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEA,
    name: "TM42",
  },
  TM43: {
    id: "TM43",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEB,
    name: "TM43",
  },
  TM44: {
    id: "TM44",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEC,
    name: "TM44",
  },
  TM45: {
    id: "TM45",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xED,
    name: "TM45",
  },
  TM46: {
    id: "TM46",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEE,
    name: "TM46",
  },
  TM47: {
    id: "TM47",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEF,
    name: "TM47",
  },
  TM48: {
    id: "TM48",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xF0,
    name: "TM48",
  },
  TM49: {
    id: "TM49",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xF1,
    name: "TM49",
  },
  TM50: {
    id: "TM50",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xF2,
    name: "TM50",
  },
  AMULET_COIN: {
    id: "AMULET_COIN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5B,
    name: "Amulet Coin",
  },
  ANTIDOTE: {
    id: "ANTIDOTE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x09,
    name: "Antidote",
  },
  AWAKENING: {
    id: "AWAKENING",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0C,
    name: "Awakening",
  },
  BERRY_JUICE: {
    id: "BERRY_JUICE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x8B,
    name: "Berry Juice",
  },
  BERRY: {
    id: "BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xAD,
    name: "Berry",
  },
  BERSERK_GENE: {
    id: "BERSERK_GENE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x98,
    name: "Berserk Gene",
  },
  BIG_MUSHROOM: {
    id: "BIG_MUSHROOM",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x57,
    name: "Big Mushroom",
  },
  BIG_PEARL: {
    id: "BIG_PEARL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6F,
    name: "Big Pearl",
  },
  BITTER_BERRY: {
    id: "BITTER_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x53,
    name: "Bitter Berry",
  },
  BLACKBELT: {
    id: "BLACKBELT",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x62,
    name: "Blackbelt",
  },
  BLACKGLASSES: {
    id: "BLACKGLASSES",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x66,
    name: "Blackglasses",
  },
  BLK_APRICORN: {
    id: "BLK_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x63,
    name: "Blk Apricorn",
  },
  BLU_APRICORN: {
    id: "BLU_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x59,
    name: "Blu Apricorn",
  },
  BLUESKY_MAIL: {
    id: "BLUESKY_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xBB,
    name: "Bluesky Mail",
  },
  BRICK_PIECE: {
    id: "BRICK_PIECE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB4,
    name: "Brick Piece",
  },
  BRIGHTPOWDER: {
    id: "BRIGHTPOWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x03,
    name: "Brightpowder",
  },
  BURN_HEAL: {
    id: "BURN_HEAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0A,
    name: "Burn Heal",
  },
  BURNT_BERRY: {
    id: "BURNT_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4F,
    name: "Burnt Berry",
  },
  CALCIUM: {
    id: "CALCIUM",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1F,
    name: "Calcium",
  },
  CARBOS: {
    id: "CARBOS",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1D,
    name: "Carbos",
  },
  CHARCOAL: {
    id: "CHARCOAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x8A,
    name: "Charcoal",
  },
  CLEANSE_TAG: {
    id: "CLEANSE_TAG",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5E,
    name: "Cleanse Tag",
  },
  DIRE_HIT: {
    id: "DIRE_HIT",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2C,
    name: "Dire Hit",
  },
  DRAGON_FANG: {
    id: "DRAGON_FANG",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x90,
    name: "Dragon Fang",
  },
  DRAGON_SCALE: {
    id: "DRAGON_SCALE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x97,
    name: "Dragon Scale",
  },
  ELIXER: {
    id: "ELIXER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x41,
    name: "Elixer",
  },
  ENERGY_ROOT: {
    id: "ENERGY_ROOT",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7A,
    name: "Energy Root",
  },
  ENERGYPOWDER: {
    id: "ENERGYPOWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x79,
    name: "Energypowder",
  },
  EON_MAIL: {
    id: "EON_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB9,
    name: "Eon Mail",
  },
  ESCAPE_ROPE: {
    id: "ESCAPE_ROPE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x13,
    name: "Escape Rope",
  },
  ETHER: {
    id: "ETHER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x3F,
    name: "Ether",
  },
  EVERSTONE: {
    id: "EVERSTONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x70,
    name: "Everstone",
  },
  EXP_SHARE: {
    id: "EXP_SHARE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x39,
    name: "Exp Share",
  },
  FIRE_STONE: {
    id: "FIRE_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x16,
    name: "Fire Stone",
  },
  FLOWER_MAIL: {
    id: "FLOWER_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x9E,
    name: "Flower Mail",
  },
  FOCUS_BAND: {
    id: "FOCUS_BAND",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x77,
    name: "Focus Band",
  },
  FRESH_WATER: {
    id: "FRESH_WATER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2E,
    name: "Fresh Water",
  },
  FULL_HEAL: {
    id: "FULL_HEAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x26,
    name: "Full Heal",
  },
  FULL_RESTORE: {
    id: "FULL_RESTORE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0E,
    name: "Full Restore",
  },
  GOLD_BERRY: {
    id: "GOLD_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xAE,
    name: "Gold Berry",
  },
  GOLD_LEAF: {
    id: "GOLD_LEAF",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4B,
    name: "Gold Leaf",
  },
  GORGEOUS_BOX: {
    id: "GORGEOUS_BOX",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xA8,
    name: "Gorgeous Box",
  },
  GRN_APRICORN: {
    id: "GRN_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5D,
    name: "Grn Apricorn",
  },
  GUARD_SPEC: {
    id: "GUARD_SPEC",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x29,
    name: "Guard Spec",
  },
  HARD_STONE: {
    id: "HARD_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7D,
    name: "Hard Stone",
  },
  HEAL_POWDER: {
    id: "HEAL_POWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7B,
    name: "Heal Powder",
  },
  HP_UP: {
    id: "HP_UP",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1A,
    name: "Hp Up",
  },
  HYPER_POTION: {
    id: "HYPER_POTION",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x10,
    name: "Hyper Potion",
  },
  ICE_BERRY: {
    id: "ICE_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x50,
    name: "Ice Berry",
  },
  ICE_HEAL: {
    id: "ICE_HEAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0B,
    name: "Ice Heal",
  },
  IRON: {
    id: "IRON",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1C,
    name: "Iron",
  },
  KINGS_ROCK: {
    id: "KINGS_ROCK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x52,
    name: "Kings Rock",
  },
  LEAF_STONE: {
    id: "LEAF_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x22,
    name: "Leaf Stone",
  },
  LEFTOVERS: {
    id: "LEFTOVERS",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x92,
    name: "Leftovers",
  },
  LEMONADE: {
    id: "LEMONADE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x30,
    name: "Lemonade",
  },
  LIGHT_BALL: {
    id: "LIGHT_BALL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xA3,
    name: "Light Ball",
  },
  LITEBLUEMAIL: {
    id: "LITEBLUEMAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB6,
    name: "Litebluemail",
  },
  LOVELY_MAIL: {
    id: "LOVELY_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB8,
    name: "Lovely Mail",
  },
  LUCKY_EGG: {
    id: "LUCKY_EGG",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7E,
    name: "Lucky Egg",
  },
  LUCKY_PUNCH: {
    id: "LUCKY_PUNCH",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1E,
    name: "Lucky Punch",
  },
  MAGNET: {
    id: "MAGNET",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6C,
    name: "Magnet",
  },
  MAX_ELIXER: {
    id: "MAX_ELIXER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x15,
    name: "Max Elixer",
  },
  MAX_ETHER: {
    id: "MAX_ETHER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x40,
    name: "Max Ether",
  },
  MAX_POTION: {
    id: "MAX_POTION",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0F,
    name: "Max Potion",
  },
  MAX_REPEL: {
    id: "MAX_REPEL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2B,
    name: "Max Repel",
  },
  MAX_REVIVE: {
    id: "MAX_REVIVE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x28,
    name: "Max Revive",
  },
  METAL_COAT: {
    id: "METAL_COAT",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x8F,
    name: "Metal Coat",
  },
  METAL_POWDER: {
    id: "METAL_POWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x23,
    name: "Metal Powder",
  },
  MINT_BERRY: {
    id: "MINT_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x54,
    name: "Mint Berry",
  },
  MIRACLE_SEED: {
    id: "MIRACLE_SEED",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x75,
    name: "Miracle Seed",
  },
  MIRACLEBERRY: {
    id: "MIRACLEBERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6D,
    name: "Miracleberry",
  },
  MIRAGE_MAIL: {
    id: "MIRAGE_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xBD,
    name: "Mirage Mail",
  },
  MOOMOO_MILK: {
    id: "MOOMOO_MILK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x48,
    name: "Moomoo Milk",
  },
  MOON_STONE: {
    id: "MOON_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x08,
    name: "Moon Stone",
  },
  MORPH_MAIL: {
    id: "MORPH_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xBA,
    name: "Morph Mail",
  },
  MUSIC_MAIL: {
    id: "MUSIC_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xBC,
    name: "Music Mail",
  },
  MYSTERYBERRY: {
    id: "MYSTERYBERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x96,
    name: "Mysteryberry",
  },
  MYSTIC_WATER: {
    id: "MYSTIC_WATER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5F,
    name: "Mystic Water",
  },
  NEVERMELTICE: {
    id: "NEVERMELTICE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6B,
    name: "Nevermeltice",
  },
  NORMAL_BOX: {
    id: "NORMAL_BOX",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xA7,
    name: "Normal Box",
  },
  NUGGET: {
    id: "NUGGET",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x24,
    name: "Nugget",
  },
  PARLYZ_HEAL: {
    id: "PARLYZ_HEAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0D,
    name: "Parlyz Heal",
  },
  PEARL: {
    id: "PEARL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6E,
    name: "Pearl",
  },
  PINK_BOW: {
    id: "PINK_BOW",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x68,
    name: "Pink Bow",
  },
  PNK_APRICORN: {
    id: "PNK_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x65,
    name: "Pnk Apricorn",
  },
  POISON_BARB: {
    id: "POISON_BARB",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x51,
    name: "Poison Barb",
  },
  POKE_DOLL: {
    id: "POKE_DOLL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x25,
    name: "Poké Doll",
  },
  POLKADOT_BOW: {
    id: "POLKADOT_BOW",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xAA,
    name: "Polkadot Bow",
  },
  PORTRAITMAIL: {
    id: "PORTRAITMAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB7,
    name: "Portraitmail",
  },
  POTION: {
    id: "POTION",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x12,
    name: "Potion",
  },
  PP_UP: {
    id: "PP_UP",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x3E,
    name: "Pp Up",
  },
  PROTEIN: {
    id: "PROTEIN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1B,
    name: "Protein",
  },
  PRZCUREBERRY: {
    id: "PRZCUREBERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4E,
    name: "Przcureberry",
  },
  PSNCUREBERRY: {
    id: "PSNCUREBERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4A,
    name: "Psncureberry",
  },
  QUICK_CLAW: {
    id: "QUICK_CLAW",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x49,
    name: "Quick Claw",
  },
  RAGECANDYBAR: {
    id: "RAGECANDYBAR",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x72,
    name: "Ragecandybar",
  },
  RARE_CANDY: {
    id: "RARE_CANDY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x20,
    name: "Rare Candy",
  },
  RED_APRICORN: {
    id: "RED_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x55,
    name: "Red Apricorn",
  },
  REPEL: {
    id: "REPEL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x14,
    name: "Repel",
  },
  REVIVAL_HERB: {
    id: "REVIVAL_HERB",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7C,
    name: "Revival Herb",
  },
  REVIVE: {
    id: "REVIVE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x27,
    name: "Revive",
  },
  SACRED_ASH: {
    id: "SACRED_ASH",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x9C,
    name: "Sacred Ash",
  },
  SCOPE_LENS: {
    id: "SCOPE_LENS",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x8C,
    name: "Scope Lens",
  },
  SHARP_BEAK: {
    id: "SHARP_BEAK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4D,
    name: "Sharp Beak",
  },
  SILVER_LEAF: {
    id: "SILVER_LEAF",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x3C,
    name: "Silver Leaf",
  },
  SILVERPOWDER: {
    id: "SILVERPOWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x58,
    name: "Silverpowder",
  },
  SLOWPOKETAIL: {
    id: "SLOWPOKETAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x67,
    name: "Slowpoketail",
  },
  SMOKE_BALL: {
    id: "SMOKE_BALL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6A,
    name: "Smoke Ball",
  },
  SODA_POP: {
    id: "SODA_POP",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2F,
    name: "Soda Pop",
  },
  SOFT_SAND: {
    id: "SOFT_SAND",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4C,
    name: "Soft Sand",
  },
  SPELL_TAG: {
    id: "SPELL_TAG",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x71,
    name: "Spell Tag",
  },
  STAR_PIECE: {
    id: "STAR_PIECE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x84,
    name: "Star Piece",
  },
  STARDUST: {
    id: "STARDUST",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x83,
    name: "Stardust",
  },
  STICK: {
    id: "STICK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x69,
    name: "Stick",
  },
  SUN_STONE: {
    id: "SUN_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xA9,
    name: "Sun Stone",
  },
  SUPER_POTION: {
    id: "SUPER_POTION",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x11,
    name: "Super Potion",
  },
  SUPER_REPEL: {
    id: "SUPER_REPEL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2A,
    name: "Super Repel",
  },
  SURF_MAIL: {
    id: "SURF_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB5,
    name: "Surf Mail",
  },
  THICK_CLUB: {
    id: "THICK_CLUB",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x76,
    name: "Thick Club",
  },
  THUNDERSTONE: {
    id: "THUNDERSTONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x17,
    name: "Thunderstone",
  },
  TINYMUSHROOM: {
    id: "TINYMUSHROOM",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x56,
    name: "Tinymushroom",
  },
  TWISTEDSPOON: {
    id: "TWISTEDSPOON",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x60,
    name: "Twistedspoon",
  },
  UP_GRADE: {
    id: "UP_GRADE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xAC,
    name: "Up Grade",
  },
  WATER_STONE: {
    id: "WATER_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x18,
    name: "Water Stone",
  },
  WHT_APRICORN: {
    id: "WHT_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x61,
    name: "Wht Apricorn",
  },
  X_ACCURACY: {
    id: "X_ACCURACY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x21,
    name: "X Accuracy",
  },
  X_ATTACK: {
    id: "X_ATTACK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x31,
    name: "X Attack",
  },
  X_DEFEND: {
    id: "X_DEFEND",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x33,
    name: "X Defend",
  },
  X_SPECIAL: {
    id: "X_SPECIAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x35,
    name: "X Special",
  },
  X_SPEED: {
    id: "X_SPEED",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x34,
    name: "X Speed",
  },
  YLW_APRICORN: {
    id: "YLW_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5C,
    name: "Ylw Apricorn",
  },
  POKE_BALL: {
    id: "POKE_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x05,
    name: "Poké Ball",
  },
  GREAT_BALL: {
    id: "GREAT_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x04,
    name: "Great Ball",
  },
  ULTRA_BALL: {
    id: "ULTRA_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x02,
    name: "Ultra Ball",
  },
  MASTER_BALL: {
    id: "MASTER_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x01,
    name: "Master Ball",
  },
  FAST_BALL: {
    id: "FAST_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA1,
    name: "Fast Ball",
  },
  FRIEND_BALL: {
    id: "FRIEND_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA4,
    name: "Friend Ball",
  },
  HEAVY_BALL: {
    id: "HEAVY_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x9D,
    name: "Heavy Ball",
  },
  LEVEL_BALL: {
    id: "LEVEL_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x9F,
    name: "Level Ball",
  },
  LOVE_BALL: {
    id: "LOVE_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA6,
    name: "Love Ball",
  },
  LURE_BALL: {
    id: "LURE_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA0,
    name: "Lure Ball",
  },
  MOON_BALL: {
    id: "MOON_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA5,
    name: "Moon Ball",
  },
  PARK_BALL: {
    id: "PARK_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xB1,
    name: "Park Ball",
  },
}