export const itemCategories: ItemCategory[] = [
  {
    id: "menuItems",
    name: "Menu Items",
    slotSize: 1,
    maxSlots: 16,
    items: [
      {
        id: "POKEDEX",
        type: "POKEDEX_PART",
        hexId: "01",
        name: "Pokédex",
      },
      {
        id: "UNONWNDEX",
        type: "POKEDEX_PART",
        hexId: "02",
        name: "Unowndex",
      },
      {
        id: "POKEGEAR",
        type: "POKEGEAR_PART",
        hexId: "84",
        name: "Pokégear",
      },
      {
        id: "MAP_CARD",
        type: "POKEGEAR_PART",
        hexId: "02",
        name: "Map Card",
      },
      {
        id: "RADIO_CARD",
        type: "POKEGEAR_PART",
        hexId: "01",
        name: "Radio Card",
      },
      {
        id: "EXPN_CARD",
        type: "POKEGEAR_PART",
        hexId: "08",
        name: "Expn Card",
      },
    ],
  },
  {
    id: "badges",
    name: "Badges",
    slotSize: 1,
    maxSlots: 16,
    items: [
      {
        id: "ZEPHYRBADGE",
        type: "JOHTO_BADGE",
        hexId: "01",
        name: "Zephyrbadge (Flash)",
      },
      {
        id: "HIVEBADGE",
        type: "JOHTO_BADGE",
        hexId: "02",
        name: "Hivebadge (Cut)",
      },
      {
        id: "PLAINBADGE",
        type: "JOHTO_BADGE",
        hexId: "04",
        name: "Plainbadge (Strength)",
      },
      {
        id: "FOGBADGE",
        type: "JOHTO_BADGE",
        hexId: "08",
        name: "Fogbadge (Surf)",
      },
      {
        id: "STORMBADGE",
        type: "JOHTO_BADGE",
        hexId: "20",
        name: "Stormbadge (Fly)",
      },
      {
        id: "MINERALBADGE",
        type: "JOHTO_BADGE",
        hexId: "10",
        name: "Mineralbadge",
      },
      {
        id: "GLACIERBADGE",
        type: "JOHTO_BADGE",
        hexId: "40",
        name: "Glacierbadge (Whirlpool)",
      },
      {
        id: "RISINGBADGE",
        type: "JOHTO_BADGE",
        hexId: "80",
        name: "Risingbadge (Waterfall)",
      },
      {
        id: "BOULDERBADGE",
        type: "KANTO_BADGE",
        hexId: "01",
        name: "Boulderbadge",
      },
      {
        id: "CASCADEBADGE",
        type: "KANTO_BADGE",
        hexId: "02",
        name: "Cascadebadge",
      },
      {
        id: "THUNDERBADGE",
        type: "KANTO_BADGE",
        hexId: "04",
        name: "Thunderbadge",
      },
      {
        id: "RAINBOWBADGE",
        type: "KANTO_BADGE",
        hexId: "08",
        name: "Rainbowbadge",
      },
      {
        id: "SOULBADGE",
        type: "KANTO_BADGE",
        hexId: "10",
        name: "Soulbadge",
      },
      {
        id: "MARSHBADGE",
        type: "KANTO_BADGE",
        hexId: "20",
        name: "Marshbadge",
      },
      {
        id: "VOLCANOBADGE",
        type: "KANTO_BADGE",
        hexId: "40",
        name: "Volcanobadge",
      },
      {
        id: "EARTHBADGE",
        type: "KANTO_BADGE",
        hexId: "80",
        name: "Earthbadge",
      },
    ],
  },
  {
    id: "keyItems",
    name: "Key Items",
    slotSize: 1,
    maxSlots: 25,
    items: [
      {
        id: "BASEMENT_KEY",
        type: "BAG_ITEM",
        hexId: "85",
        name: "Basement Key",
      },
      {
        id: "BICYCLE",
        type: "BAG_ITEM",
        hexId: "07",
        name: "Bicycle",
      },
      {
        id: "BLUE_CARD",
        type: "BAG_ITEM",
        hexId: "74",
        name: "Blue Card",
      },
      {
        id: "CARD_KEY",
        type: "BAG_ITEM",
        hexId: "7F",
        name: "Card Key",
      },
      {
        id: "CLEAR_BELL",
        type: "BAG_ITEM",
        hexId: "46",
        name: "Clear Bell",
      },
      {
        id: "COIN_CASE",
        type: "BAG_ITEM",
        hexId: "36",
        name: "Coin Case",
      },
      {
        id: "EGG_TICKET",
        type: "BAG_ITEM",
        hexId: "81",
        name: "Egg Ticket",
      },
      {
        id: "GOOD_ROD",
        type: "BAG_ITEM",
        hexId: "3B",
        name: "Good Rod",
      },
      {
        id: "GS_BALL",
        type: "BAG_ITEM",
        hexId: "73",
        name: "GS Ball",
      },
      {
        id: "ITEMFINDER",
        type: "BAG_ITEM",
        hexId: "37",
        name: "Itemfinder",
      },
      {
        id: "LOST_ITEM",
        type: "BAG_ITEM",
        hexId: "82",
        name: "Lost Item",
      },
      {
        id: "MACHINE_PART",
        type: "BAG_ITEM",
        hexId: "80",
        name: "Machine Part",
      },
      {
        id: "MYSTERY_EGG",
        type: "BAG_ITEM",
        hexId: "45",
        name: "Mystery Egg",
      },
      {
        id: "OLD_ROD",
        type: "BAG_ITEM",
        hexId: "3A",
        name: "Old Rod",
      },
      {
        id: "PASS",
        type: "BAG_ITEM",
        hexId: "86",
        name: "Pass",
      },
      {
        id: "RAINBOW_WING",
        type: "BAG_ITEM",
        hexId: "B2",
        name: "Rainbow Wing",
      },
      {
        id: "RED_SCALE",
        type: "BAG_ITEM",
        hexId: "42",
        name: "Red Scale",
      },
      {
        id: "SECRETPOTION",
        type: "BAG_ITEM",
        hexId: "43",
        name: "Secretpotion",
      },
      {
        id: "SILVER_WING",
        type: "BAG_ITEM",
        hexId: "47",
        name: "Silver Wing",
      },
      {
        id: "SQUIRTBOTTLE",
        type: "BAG_ITEM",
        hexId: "AF",
        name: "Squirtbottle",
      },
      {
        id: "S_S_TICKET",
        type: "BAG_ITEM",
        hexId: "44",
        name: "S.S.Ticket",
      },
      {
        id: "SUPER_ROD",
        type: "BAG_ITEM",
        hexId: "3D",
        name: "Super Rod",
      },
    ],
  },
  {
    id: "hms",
    name: "HMs",
    slotSize: 1,
    maxSlots: 7,
    items: [
      {
        id: "HM01",
        type: "BAG_ITEM",
        hexId: "F3",
        name: "HM01 (Cut)",
      },
      {
        id: "HM02",
        type: "BAG_ITEM",
        hexId: "F4",
        name: "HM02 (Fly)",
      },
      {
        id: "HM03",
        type: "BAG_ITEM",
        hexId: "F5",
        name: "HM03 (Surf)",
      },
      {
        id: "HM04",
        type: "BAG_ITEM",
        hexId: "F6",
        name: "HM04 (Strength)",
      },
      {
        id: "HM05",
        type: "BAG_ITEM",
        hexId: "F7",
        name: "HM05 (Flash)",
      },
      {
        id: "HM06",
        type: "BAG_ITEM",
        hexId: "F8",
        name: "HM06 (Whirlpool)",
      },
      {
        id: "HM07",
        type: "BAG_ITEM",
        hexId: "F9",
        name: "HM07 (Waterfall)",
      },
    ],
  },
  {
    id: "tms",
    name: "TMs",
    slotSize: 99,
    maxSlots: 50,
    items: [
      {
        id: "TM01",
        type: "BAG_ITEM",
        hexId: "BF",
        name: "TM01",
      },
      {
        id: "TM02",
        type: "BAG_ITEM",
        hexId: "C0",
        name: "TM02 (Headbutt)",
      },
      {
        id: "TM03",
        type: "BAG_ITEM",
        hexId: "C1",
        name: "TM03",
      },
      {
        id: "TM04",
        type: "BAG_ITEM",
        hexId: "C2",
        name: "TM04",
      },
      {
        id: "TM05",
        type: "BAG_ITEM",
        hexId: "C4",
        name: "TM05",
      },
      {
        id: "TM06",
        type: "BAG_ITEM",
        hexId: "C5",
        name: "TM06",
      },
      {
        id: "TM07",
        type: "BAG_ITEM",
        hexId: "C6",
        name: "TM07",
      },
      {
        id: "TM08",
        type: "BAG_ITEM",
        hexId: "C7",
        name: "TM08 (Rock Smash)",
      },
      {
        id: "TM09",
        type: "BAG_ITEM",
        hexId: "C8",
        name: "TM09",
      },
      {
        id: "TM10",
        type: "BAG_ITEM",
        hexId: "C9",
        name: "TM10",
      },
      {
        id: "TM11",
        type: "BAG_ITEM",
        hexId: "CA",
        name: "TM11",
      },
      {
        id: "TM12",
        type: "BAG_ITEM",
        hexId: "CB",
        name: "TM12 (Sweet Scent)",
      },
      {
        id: "TM13",
        type: "BAG_ITEM",
        hexId: "CC",
        name: "TM13",
      },
      {
        id: "TM14",
        type: "BAG_ITEM",
        hexId: "CD",
        name: "TM14",
      },
      {
        id: "TM15",
        type: "BAG_ITEM",
        hexId: "CE",
        name: "TM15",
      },
      {
        id: "TM16",
        type: "BAG_ITEM",
        hexId: "CF",
        name: "TM16",
      },
      {
        id: "TM17",
        type: "BAG_ITEM",
        hexId: "D0",
        name: "TM17",
      },
      {
        id: "TM18",
        type: "BAG_ITEM",
        hexId: "D1",
        name: "TM18",
      },
      {
        id: "TM19",
        type: "BAG_ITEM",
        hexId: "D2",
        name: "TM19",
      },
      {
        id: "TM20",
        type: "BAG_ITEM",
        hexId: "D3",
        name: "TM20",
      },
      {
        id: "TM21",
        type: "BAG_ITEM",
        hexId: "D4",
        name: "TM21",
      },
      {
        id: "TM22",
        type: "BAG_ITEM",
        hexId: "D5",
        name: "TM22",
      },
      {
        id: "TM23",
        type: "BAG_ITEM",
        hexId: "D6",
        name: "TM23",
      },
      {
        id: "TM24",
        type: "BAG_ITEM",
        hexId: "D7",
        name: "TM24",
      },
      {
        id: "TM25",
        type: "BAG_ITEM",
        hexId: "D8",
        name: "TM25",
      },
      {
        id: "TM26",
        type: "BAG_ITEM",
        hexId: "D9",
        name: "TM26",
      },
      {
        id: "TM27",
        type: "BAG_ITEM",
        hexId: "DA",
        name: "TM27",
      },
      {
        id: "TM28",
        type: "BAG_ITEM",
        hexId: "DB",
        name: "TM28 (Dig)",
      },
      {
        id: "TM29",
        type: "BAG_ITEM",
        hexId: "DD",
        name: "TM29",
      },
      {
        id: "TM30",
        type: "BAG_ITEM",
        hexId: "DE",
        name: "TM30",
      },
      {
        id: "TM31",
        type: "BAG_ITEM",
        hexId: "DF",
        name: "TM31",
      },
      {
        id: "TM32",
        type: "BAG_ITEM",
        hexId: "E0",
        name: "TM32",
      },
      {
        id: "TM33",
        type: "BAG_ITEM",
        hexId: "E1",
        name: "TM33",
      },
      {
        id: "TM34",
        type: "BAG_ITEM",
        hexId: "E2",
        name: "TM34",
      },
      {
        id: "TM35",
        type: "BAG_ITEM",
        hexId: "E3",
        name: "TM35",
      },
      {
        id: "TM36",
        type: "BAG_ITEM",
        hexId: "E4",
        name: "TM36",
      },
      {
        id: "TM37",
        type: "BAG_ITEM",
        hexId: "E5",
        name: "TM37",
      },
      {
        id: "TM38",
        type: "BAG_ITEM",
        hexId: "E6",
        name: "TM38",
      },
      {
        id: "TM39",
        type: "BAG_ITEM",
        hexId: "E7",
        name: "TM39",
      },
      {
        id: "TM40",
        type: "BAG_ITEM",
        hexId: "E8",
        name: "TM40",
      },
      {
        id: "TM41",
        type: "BAG_ITEM",
        hexId: "E9",
        name: "TM41",
      },
      {
        id: "TM42",
        type: "BAG_ITEM",
        hexId: "EA",
        name: "TM42",
      },
      {
        id: "TM43",
        type: "BAG_ITEM",
        hexId: "EB",
        name: "TM43",
      },
      {
        id: "TM44",
        type: "BAG_ITEM",
        hexId: "EC",
        name: "TM44",
      },
      {
        id: "TM45",
        type: "BAG_ITEM",
        hexId: "ED",
        name: "TM45",
      },
      {
        id: "TM46",
        type: "BAG_ITEM",
        hexId: "EE",
        name: "TM46",
      },
      {
        id: "TM47",
        type: "BAG_ITEM",
        hexId: "EF",
        name: "TM47",
      },
      {
        id: "TM48",
        type: "BAG_ITEM",
        hexId: "F0",
        name: "TM48",
      },
      {
        id: "TM49",
        type: "BAG_ITEM",
        hexId: "F1",
        name: "TM49",
      },
      {
        id: "TM50",
        type: "BAG_ITEM",
        hexId: "F2",
        name: "TM50",
      },
    ],
  },
  {
    id: "items",
    name: "Items",
    slotSize: 99,
    maxSlots: 20,
    items: [
      {
        id: "AMULET_COIN",
        type: "BAG_ITEM",
        hexId: "5B",
        name: "Amulet Coin",
      },
      {
        id: "ANTIDOTE",
        type: "BAG_ITEM",
        hexId: "09",
        name: "Antidote",
      },
      {
        id: "AWAKENING",
        type: "BAG_ITEM",
        hexId: "0C",
        name: "Awakening",
      },
      {
        id: "BERRY_JUICE",
        type: "BAG_ITEM",
        hexId: "8B",
        name: "Berry Juice",
      },
      {
        id: "BERRY",
        type: "BAG_ITEM",
        hexId: "AD",
        name: "Berry",
      },
      {
        id: "BERSERK_GENE",
        type: "BAG_ITEM",
        hexId: "98",
        name: "Berserk Gene",
      },
      {
        id: "BIG_MUSHROOM",
        type: "BAG_ITEM",
        hexId: "57",
        name: "Big Mushroom",
      },
      {
        id: "BIG_PEARL",
        type: "BAG_ITEM",
        hexId: "6F",
        name: "Big Pearl",
      },
      {
        id: "BITTER_BERRY",
        type: "BAG_ITEM",
        hexId: "53",
        name: "Bitter Berry",
      },
      {
        id: "BLACKBELT",
        type: "BAG_ITEM",
        hexId: "62",
        name: "Blackbelt",
      },
      {
        id: "BLACKGLASSES",
        type: "BAG_ITEM",
        hexId: "66",
        name: "Blackglasses",
      },
      {
        id: "BLK_APRICORN",
        type: "BAG_ITEM",
        hexId: "63",
        name: "Blk Apricorn",
      },
      {
        id: "BLU_APRICORN",
        type: "BAG_ITEM",
        hexId: "59",
        name: "Blu Apricorn",
      },
      {
        id: "BLUESKY_MAIL",
        type: "BAG_ITEM",
        hexId: "BB",
        name: "Bluesky Mail",
      },
      {
        id: "BRICK_PIECE",
        type: "BAG_ITEM",
        hexId: "B4",
        name: "Brick Piece",
      },
      {
        id: "BRIGHTPOWDER",
        type: "BAG_ITEM",
        hexId: "03",
        name: "Brightpowder",
      },
      {
        id: "BURN_HEAL",
        type: "BAG_ITEM",
        hexId: "0A",
        name: "Burn Heal",
      },
      {
        id: "BURNT_BERRY",
        type: "BAG_ITEM",
        hexId: "4F",
        name: "Burnt Berry",
      },
      {
        id: "CALCIUM",
        type: "BAG_ITEM",
        hexId: "1F",
        name: "Calcium",
      },
      {
        id: "CARBOS",
        type: "BAG_ITEM",
        hexId: "1D",
        name: "Carbos",
      },
      {
        id: "CHARCOAL",
        type: "BAG_ITEM",
        hexId: "8A",
        name: "Charcoal",
      },
      {
        id: "CLEANSE_TAG",
        type: "BAG_ITEM",
        hexId: "5E",
        name: "Cleanse Tag",
      },
      {
        id: "DIRE_HIT",
        type: "BAG_ITEM",
        hexId: "2C",
        name: "Dire Hit",
      },
      {
        id: "DRAGON_FANG",
        type: "BAG_ITEM",
        hexId: "90",
        name: "Dragon Fang",
      },
      {
        id: "DRAGON_SCALE",
        type: "BAG_ITEM",
        hexId: "97",
        name: "Dragon Scale",
      },
      {
        id: "ELIXER",
        type: "BAG_ITEM",
        hexId: "41",
        name: "Elixer",
      },
      {
        id: "ENERGY_ROOT",
        type: "BAG_ITEM",
        hexId: "7A",
        name: "Energy Root",
      },
      {
        id: "ENERGYPOWDER",
        type: "BAG_ITEM",
        hexId: "79",
        name: "Energypowder",
      },
      {
        id: "EON_MAIL",
        type: "BAG_ITEM",
        hexId: "B9",
        name: "Eon Mail",
      },
      {
        id: "ESCAPE_ROPE",
        type: "BAG_ITEM",
        hexId: "13",
        name: "Escape Rope",
      },
      {
        id: "ETHER",
        type: "BAG_ITEM",
        hexId: "3F",
        name: "Ether",
      },
      {
        id: "EVERSTONE",
        type: "BAG_ITEM",
        hexId: "70",
        name: "Everstone",
      },
      {
        id: "EXP_SHARE",
        type: "BAG_ITEM",
        hexId: "39",
        name: "Exp Share",
      },
      {
        id: "FIRE_STONE",
        type: "BAG_ITEM",
        hexId: "16",
        name: "Fire Stone",
      },
      {
        id: "FLOWER_MAIL",
        type: "BAG_ITEM",
        hexId: "9E",
        name: "Flower Mail",
      },
      {
        id: "FOCUS_BAND",
        type: "BAG_ITEM",
        hexId: "77",
        name: "Focus Band",
      },
      {
        id: "FRESH_WATER",
        type: "BAG_ITEM",
        hexId: "2E",
        name: "Fresh Water",
      },
      {
        id: "FULL_HEAL",
        type: "BAG_ITEM",
        hexId: "26",
        name: "Full Heal",
      },
      {
        id: "FULL_RESTORE",
        type: "BAG_ITEM",
        hexId: "0E",
        name: "Full Restore",
      },
      {
        id: "GOLD_BERRY",
        type: "BAG_ITEM",
        hexId: "AE",
        name: "Gold Berry",
      },
      {
        id: "GOLD_LEAF",
        type: "BAG_ITEM",
        hexId: "4B",
        name: "Gold Leaf",
      },
      {
        id: "GORGEOUS_BOX",
        type: "BAG_ITEM",
        hexId: "A8",
        name: "Gorgeous Box",
      },
      {
        id: "GRN_APRICORN",
        type: "BAG_ITEM",
        hexId: "5D",
        name: "Grn Apricorn",
      },
      {
        id: "GUARD_SPEC",
        type: "BAG_ITEM",
        hexId: "29",
        name: "Guard Spec",
      },
      {
        id: "HARD_STONE",
        type: "BAG_ITEM",
        hexId: "7D",
        name: "Hard Stone",
      },
      {
        id: "HEAL_POWDER",
        type: "BAG_ITEM",
        hexId: "7B",
        name: "Heal Powder",
      },
      {
        id: "HP_UP",
        type: "BAG_ITEM",
        hexId: "1A",
        name: "Hp Up",
      },
      {
        id: "HYPER_POTION",
        type: "BAG_ITEM",
        hexId: "10",
        name: "Hyper Potion",
      },
      {
        id: "ICE_BERRY",
        type: "BAG_ITEM",
        hexId: "50",
        name: "Ice Berry",
      },
      {
        id: "ICE_HEAL",
        type: "BAG_ITEM",
        hexId: "0B",
        name: "Ice Heal",
      },
      {
        id: "IRON",
        type: "BAG_ITEM",
        hexId: "1C",
        name: "Iron",
      },
      {
        id: "ITEM_2D",
        type: "BAG_ITEM",
        hexId: "2D",
        name: "Item 2d",
      },
      {
        id: "ITEM_5A",
        type: "BAG_ITEM",
        hexId: "5A",
        name: "Item 5a",
      },
      {
        id: "ITEM_8D",
        type: "BAG_ITEM",
        hexId: "8D",
        name: "Item 8d",
      },
      {
        id: "ITEM_8E",
        type: "BAG_ITEM",
        hexId: "8E",
        name: "Item 8e",
      },
      {
        id: "ITEM_9A",
        type: "BAG_ITEM",
        hexId: "9A",
        name: "Item 9a",
      },
      {
        id: "ITEM_9B",
        type: "BAG_ITEM",
        hexId: "9B",
        name: "Item 9b",
      },
      {
        id: "ITEM_19",
        type: "BAG_ITEM",
        hexId: "19",
        name: "Item 19",
      },
      {
        id: "ITEM_32",
        type: "BAG_ITEM",
        hexId: "32",
        name: "Item 32",
      },
      {
        id: "ITEM_64",
        type: "BAG_ITEM",
        hexId: "64",
        name: "Item 64",
      },
      {
        id: "ITEM_78",
        type: "BAG_ITEM",
        hexId: "78",
        name: "Item 78",
      },
      {
        id: "ITEM_87",
        type: "BAG_ITEM",
        hexId: "87",
        name: "Item 87",
      },
      {
        id: "ITEM_88",
        type: "BAG_ITEM",
        hexId: "88",
        name: "Item 88",
      },
      {
        id: "ITEM_89",
        type: "BAG_ITEM",
        hexId: "89",
        name: "Item 89",
      },
      {
        id: "ITEM_91",
        type: "BAG_ITEM",
        hexId: "91",
        name: "Item 91",
      },
      {
        id: "ITEM_93",
        type: "BAG_ITEM",
        hexId: "93",
        name: "Item 93",
      },
      {
        id: "ITEM_94",
        type: "BAG_ITEM",
        hexId: "94",
        name: "Item 94",
      },
      {
        id: "ITEM_95",
        type: "BAG_ITEM",
        hexId: "95",
        name: "Item 95",
      },
      {
        id: "ITEM_99",
        type: "BAG_ITEM",
        hexId: "99",
        name: "Item 99",
      },
      {
        id: "ITEM_A2",
        type: "BAG_ITEM",
        hexId: "A2",
        name: "Item A2",
      },
      {
        id: "ITEM_AB",
        type: "BAG_ITEM",
        hexId: "AB",
        name: "Item Ab",
      },
      {
        id: "ITEM_B0",
        type: "BAG_ITEM",
        hexId: "B0",
        name: "Item B0",
      },
      {
        id: "ITEM_B3",
        type: "BAG_ITEM",
        hexId: "B3",
        name: "Item B3",
      },
      {
        id: "ITEM_BE",
        type: "BAG_ITEM",
        hexId: "BE",
        name: "Item Be",
      },
      {
        id: "ITEM_C3",
        type: "BAG_ITEM",
        hexId: "C3",
        name: "Item C3",
      },
      {
        id: "ITEM_DC",
        type: "BAG_ITEM",
        hexId: "DC",
        name: "Item Dc",
      },
      {
        id: "KINGS_ROCK",
        type: "BAG_ITEM",
        hexId: "52",
        name: "Kings Rock",
      },
      {
        id: "LEAF_STONE",
        type: "BAG_ITEM",
        hexId: "22",
        name: "Leaf Stone",
      },
      {
        id: "LEFTOVERS",
        type: "BAG_ITEM",
        hexId: "92",
        name: "Leftovers",
      },
      {
        id: "LEMONADE",
        type: "BAG_ITEM",
        hexId: "30",
        name: "Lemonade",
      },
      {
        id: "LIGHT_BALL",
        type: "BAG_ITEM",
        hexId: "A3",
        name: "Light Ball",
      },
      {
        id: "LITEBLUEMAIL",
        type: "BAG_ITEM",
        hexId: "B6",
        name: "Litebluemail",
      },
      {
        id: "LOVELY_MAIL",
        type: "BAG_ITEM",
        hexId: "B8",
        name: "Lovely Mail",
      },
      {
        id: "LUCKY_EGG",
        type: "BAG_ITEM",
        hexId: "7E",
        name: "Lucky Egg",
      },
      {
        id: "LUCKY_PUNCH",
        type: "BAG_ITEM",
        hexId: "1E",
        name: "Lucky Punch",
      },
      {
        id: "MAGNET",
        type: "BAG_ITEM",
        hexId: "6C",
        name: "Magnet",
      },
      {
        id: "MAX_ELIXER",
        type: "BAG_ITEM",
        hexId: "15",
        name: "Max Elixer",
      },
      {
        id: "MAX_ETHER",
        type: "BAG_ITEM",
        hexId: "40",
        name: "Max Ether",
      },
      {
        id: "MAX_POTION",
        type: "BAG_ITEM",
        hexId: "0F",
        name: "Max Potion",
      },
      {
        id: "MAX_REPEL",
        type: "BAG_ITEM",
        hexId: "2B",
        name: "Max Repel",
      },
      {
        id: "MAX_REVIVE",
        type: "BAG_ITEM",
        hexId: "28",
        name: "Max Revive",
      },
      {
        id: "METAL_COAT",
        type: "BAG_ITEM",
        hexId: "8F",
        name: "Metal Coat",
      },
      {
        id: "METAL_POWDER",
        type: "BAG_ITEM",
        hexId: "23",
        name: "Metal Powder",
      },
      {
        id: "MINT_BERRY",
        type: "BAG_ITEM",
        hexId: "54",
        name: "Mint Berry",
      },
      {
        id: "MIRACLE_SEED",
        type: "BAG_ITEM",
        hexId: "75",
        name: "Miracle Seed",
      },
      {
        id: "MIRACLEBERRY",
        type: "BAG_ITEM",
        hexId: "6D",
        name: "Miracleberry",
      },
      {
        id: "MIRAGE_MAIL",
        type: "BAG_ITEM",
        hexId: "BD",
        name: "Mirage Mail",
      },
      {
        id: "MOOMOO_MILK",
        type: "BAG_ITEM",
        hexId: "48",
        name: "Moomoo Milk",
      },
      {
        id: "MOON_STONE",
        type: "BAG_ITEM",
        hexId: "08",
        name: "Moon Stone",
      },
      {
        id: "MORPH_MAIL",
        type: "BAG_ITEM",
        hexId: "BA",
        name: "Morph Mail",
      },
      {
        id: "MUSIC_MAIL",
        type: "BAG_ITEM",
        hexId: "BC",
        name: "Music Mail",
      },
      {
        id: "MYSTERYBERRY",
        type: "BAG_ITEM",
        hexId: "96",
        name: "Mysteryberry",
      },
      {
        id: "MYSTIC_WATER",
        type: "BAG_ITEM",
        hexId: "5F",
        name: "Mystic Water",
      },
      {
        id: "NEVERMELTICE",
        type: "BAG_ITEM",
        hexId: "6B",
        name: "Nevermeltice",
      },
      {
        id: "NORMAL_BOX",
        type: "BAG_ITEM",
        hexId: "A7",
        name: "Normal Box",
      },
      {
        id: "NUGGET",
        type: "BAG_ITEM",
        hexId: "24",
        name: "Nugget",
      },
      {
        id: "PARLYZ_HEAL",
        type: "BAG_ITEM",
        hexId: "0D",
        name: "Parlyz Heal",
      },
      {
        id: "PEARL",
        type: "BAG_ITEM",
        hexId: "6E",
        name: "Pearl",
      },
      {
        id: "PINK_BOW",
        type: "BAG_ITEM",
        hexId: "68",
        name: "Pink Bow",
      },
      {
        id: "PNK_APRICORN",
        type: "BAG_ITEM",
        hexId: "65",
        name: "Pnk Apricorn",
      },
      {
        id: "POISON_BARB",
        type: "BAG_ITEM",
        hexId: "51",
        name: "Poison Barb",
      },
      {
        id: "POKE_DOLL",
        type: "BAG_ITEM",
        hexId: "25",
        name: "Poke Doll",
      },
      {
        id: "POKE_FLUTE",
        type: "BAG_ITEM",
        hexId: "38",
        name: "Poke Flute",
      },
      {
        id: "POLKADOT_BOW",
        type: "BAG_ITEM",
        hexId: "AA",
        name: "Polkadot Bow",
      },
      {
        id: "PORTRAITMAIL",
        type: "BAG_ITEM",
        hexId: "B7",
        name: "Portraitmail",
      },
      {
        id: "POTION",
        type: "BAG_ITEM",
        hexId: "12",
        name: "Potion",
      },
      {
        id: "PP_UP",
        type: "BAG_ITEM",
        hexId: "3E",
        name: "Pp Up",
      },
      {
        id: "PROTEIN",
        type: "BAG_ITEM",
        hexId: "1B",
        name: "Protein",
      },
      {
        id: "PRZCUREBERRY",
        type: "BAG_ITEM",
        hexId: "4E",
        name: "Przcureberry",
      },
      {
        id: "PSNCUREBERRY",
        type: "BAG_ITEM",
        hexId: "4A",
        name: "Psncureberry",
      },
      {
        id: "QUICK_CLAW",
        type: "BAG_ITEM",
        hexId: "49",
        name: "Quick Claw",
      },
      {
        id: "RAGECANDYBAR",
        type: "BAG_ITEM",
        hexId: "72",
        name: "Ragecandybar",
      },
      {
        id: "RARE_CANDY",
        type: "BAG_ITEM",
        hexId: "20",
        name: "Rare Candy",
      },
      {
        id: "RED_APRICORN",
        type: "BAG_ITEM",
        hexId: "55",
        name: "Red Apricorn",
      },
      {
        id: "REPEL",
        type: "BAG_ITEM",
        hexId: "14",
        name: "Repel",
      },
      {
        id: "REVIVAL_HERB",
        type: "BAG_ITEM",
        hexId: "7C",
        name: "Revival Herb",
      },
      {
        id: "REVIVE",
        type: "BAG_ITEM",
        hexId: "27",
        name: "Revive",
      },
      {
        id: "SACRED_ASH",
        type: "BAG_ITEM",
        hexId: "9C",
        name: "Sacred Ash",
      },
      {
        id: "SCOPE_LENS",
        type: "BAG_ITEM",
        hexId: "8C",
        name: "Scope Lens",
      },
      {
        id: "SHARP_BEAK",
        type: "BAG_ITEM",
        hexId: "4D",
        name: "Sharp Beak",
      },
      {
        id: "SILVER_LEAF",
        type: "BAG_ITEM",
        hexId: "3C",
        name: "Silver Leaf",
      },
      {
        id: "SILVERPOWDER",
        type: "BAG_ITEM",
        hexId: "58",
        name: "Silverpowder",
      },
      {
        id: "SLOWPOKETAIL",
        type: "BAG_ITEM",
        hexId: "67",
        name: "Slowpoketail",
      },
      {
        id: "SMOKE_BALL",
        type: "BAG_ITEM",
        hexId: "6A",
        name: "Smoke Ball",
      },
      {
        id: "SODA_POP",
        type: "BAG_ITEM",
        hexId: "2F",
        name: "Soda Pop",
      },
      {
        id: "SOFT_SAND",
        type: "BAG_ITEM",
        hexId: "4C",
        name: "Soft Sand",
      },
      {
        id: "SPELL_TAG",
        type: "BAG_ITEM",
        hexId: "71",
        name: "Spell Tag",
      },
      {
        id: "STAR_PIECE",
        type: "BAG_ITEM",
        hexId: "84",
        name: "Star Piece",
      },
      {
        id: "STARDUST",
        type: "BAG_ITEM",
        hexId: "83",
        name: "Stardust",
      },
      {
        id: "STICK",
        type: "BAG_ITEM",
        hexId: "69",
        name: "Stick",
      },
      {
        id: "SUN_STONE",
        type: "BAG_ITEM",
        hexId: "A9",
        name: "Sun Stone",
      },
      {
        id: "SUPER_POTION",
        type: "BAG_ITEM",
        hexId: "11",
        name: "Super Potion",
      },
      {
        id: "SUPER_REPEL",
        type: "BAG_ITEM",
        hexId: "2A",
        name: "Super Repel",
      },
      {
        id: "SURF_MAIL",
        type: "BAG_ITEM",
        hexId: "B5",
        name: "Surf Mail",
      },
      {
        id: "THICK_CLUB",
        type: "BAG_ITEM",
        hexId: "76",
        name: "Thick Club",
      },
      {
        id: "THUNDERSTONE",
        type: "BAG_ITEM",
        hexId: "17",
        name: "Thunderstone",
      },
      {
        id: "TINYMUSHROOM",
        type: "BAG_ITEM",
        hexId: "56",
        name: "Tinymushroom",
      },
      {
        id: "TOWN_MAP",
        type: "BAG_ITEM",
        hexId: "06",
        name: "Town Map",
      },
      {
        id: "TWISTEDSPOON",
        type: "BAG_ITEM",
        hexId: "60",
        name: "Twistedspoon",
      },
      {
        id: "UP_GRADE",
        type: "BAG_ITEM",
        hexId: "AC",
        name: "Up Grade",
      },
      {
        id: "WATER_STONE",
        type: "BAG_ITEM",
        hexId: "18",
        name: "Water Stone",
      },
      {
        id: "WHT_APRICORN",
        type: "BAG_ITEM",
        hexId: "61",
        name: "Wht Apricorn",
      },
      {
        id: "X_ACCURACY",
        type: "BAG_ITEM",
        hexId: "21",
        name: "X Accuracy",
      },
      {
        id: "X_ATTACK",
        type: "BAG_ITEM",
        hexId: "31",
        name: "X Attack",
      },
      {
        id: "X_DEFEND",
        type: "BAG_ITEM",
        hexId: "33",
        name: "X Defend",
      },
      {
        id: "X_SPECIAL",
        type: "BAG_ITEM",
        hexId: "35",
        name: "X Special",
      },
      {
        id: "X_SPEED",
        type: "BAG_ITEM",
        hexId: "34",
        name: "X Speed",
      },
      {
        id: "YLW_APRICORN",
        type: "BAG_ITEM",
        hexId: "5C",
        name: "Ylw Apricorn",
      },
    ],
  },
  {
    id: "balls",
    name: "Balls",
    slotSize: 99,
    maxSlots: 12,
    items: [
      {
        id: "POKE_BALL",
        type: "BAG_ITEM",
        hexId: "05",
        name: "Poke Ball",
      },
      {
        id: "GREAT_BALL",
        type: "BAG_ITEM",
        hexId: "04",
        name: "Great Ball",
      },
      {
        id: "ULTRA_BALL",
        type: "BAG_ITEM",
        hexId: "02",
        name: "Ultra Ball",
      },
      {
        id: "MASTER_BALL",
        type: "BAG_ITEM",
        hexId: "01",
        name: "Master Ball",
      },
      {
        id: "FAST_BALL",
        type: "BAG_ITEM",
        hexId: "A1",
        name: "Fast Ball",
      },
      {
        id: "FRIEND_BALL",
        type: "BAG_ITEM",
        hexId: "A4",
        name: "Friend Ball",
      },
      {
        id: "HEAVY_BALL",
        type: "BAG_ITEM",
        hexId: "9D",
        name: "Heavy Ball",
      },
      {
        id: "LEVEL_BALL",
        type: "BAG_ITEM",
        hexId: "9F",
        name: "Level Ball",
      },
      {
        id: "LOVE_BALL",
        type: "BAG_ITEM",
        hexId: "A6",
        name: "Love Ball",
      },
      {
        id: "LURE_BALL",
        type: "BAG_ITEM",
        hexId: "A0",
        name: "Lure Ball",
      },
      {
        id: "MOON_BALL",
        type: "BAG_ITEM",
        hexId: "A5",
        name: "Moon Ball",
      },
      {
        id: "PARK_BALL",
        type: "BAG_ITEM",
        hexId: "B1",
        name: "Park Ball",
      },
    ],
  },
]