import type { Item } from "@shared/types/gameData/item"
import type { ItemId } from "@shared/types/gameDataIds/items"

export const itemsMap: IdMap<ItemId, Item> = {
  POKEDEX: {
    id: "POKEDEX",
    type: "POKEDEX_PART",
    category: "MENU_ITEMS",
    numericId: 0x19,
    inGameName: "POKéDEX",
    name: "Pokédex",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000001,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  UNONWNDEX: {
    id: "UNONWNDEX",
    type: "POKEDEX_PART",
    category: "MENU_ITEMS",
    numericId: 0x2D,
    inGameName: "UNOWNDEX",
    name: "Unowndex",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000010,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  POKEGEAR: {
    id: "POKEGEAR",
    type: "POKEGEAR_PART",
    category: "MENU_ITEMS",
    numericId: 0x32,
    inGameName: "POKéGEAR",
    name: "Pokégear",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b10000100,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MAP_CARD: {
    id: "MAP_CARD",
    type: "POKEGEAR_PART",
    category: "MENU_ITEMS",
    numericId: 0x5A,
    inGameName: "MAP CARD",
    name: "Map Card",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000001,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  RADIO_CARD: {
    id: "RADIO_CARD",
    type: "POKEGEAR_PART",
    category: "MENU_ITEMS",
    numericId: 0x64,
    inGameName: "RADIO CARD",
    name: "Radio Card",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000010,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  EXPN_CARD: {
    id: "EXPN_CARD",
    type: "POKEGEAR_PART",
    category: "MENU_ITEMS",
    numericId: 0x78,
    inGameName: "EXPN CARD",
    name: "Expn Card",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00001000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  ZEPHYRBADGE: {
    id: "ZEPHYRBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x87,
    inGameName: "ZEPHYRBADGE",
    name: "Zephyrbadge (Flash)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000001,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  HIVEBADGE: {
    id: "HIVEBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x88,
    inGameName: "HIVEBADGE",
    name: "Hivebadge (Cut)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000010,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  PLAINBADGE: {
    id: "PLAINBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x89,
    inGameName: "PLAINBADGE",
    name: "Plainbadge (Strength)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000100,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  FOGBADGE: {
    id: "FOGBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x8D,
    inGameName: "FOGBADGE",
    name: "Fogbadge (Surf)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00001000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  STORMBADGE: {
    id: "STORMBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x91,
    inGameName: "STORMBADGE",
    name: "Stormbadge (Fly)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00100000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MINERALBADGE: {
    id: "MINERALBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x8E,
    inGameName: "MINERALBADGE",
    name: "Mineralbadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00010000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  GLACIERBADGE: {
    id: "GLACIERBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x93,
    inGameName: "GLACIERBADGE",
    name: "Glacierbadge (Whirlpool)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b01000000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  RISINGBADGE: {
    id: "RISINGBADGE",
    type: "JOHTO_BADGE",
    category: "BADGES",
    numericId: 0x94,
    inGameName: "RISINGBADGE",
    name: "Risingbadge (Waterfall)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b10000000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BOULDERBADGE: {
    id: "BOULDERBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x95,
    inGameName: "BOULDERBADGE",
    name: "Boulderbadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000001,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  CASCADEBADGE: {
    id: "CASCADEBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x99,
    inGameName: "CASCADEBADGE",
    name: "Cascadebadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000010,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  THUNDERBADGE: {
    id: "THUNDERBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x9A,
    inGameName: "THUNDERBADGE",
    name: "Thunderbadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00000100,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  RAINBOWBADGE: {
    id: "RAINBOWBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0x9B,
    inGameName: "RAINBOWBADGE",
    name: "Rainbowbadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00001000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SOULBADGE: {
    id: "SOULBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0xA2,
    inGameName: "SOULBADGE",
    name: "Soulbadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00010000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MARSHBADGE: {
    id: "MARSHBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0xAB,
    inGameName: "MARSHBADGE",
    name: "Marshbadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b00100000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  VOLCANOBADGE: {
    id: "VOLCANOBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0xB0,
    inGameName: "VOLCANOBADGE",
    name: "Volcanobadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b01000000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  EARTHBADGE: {
    id: "EARTHBADGE",
    type: "KANTO_BADGE",
    category: "BADGES",
    numericId: 0xB3,
    inGameName: "EARTHBADGE",
    name: "Earthbadge",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0b10000000,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BASEMENT_KEY: {
    id: "BASEMENT_KEY",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x85,
    inGameName: "BASEMENT KEY",
    name: "Basement Key",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  BICYCLE: {
    id: "BICYCLE",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x07,
    inGameName: "BICYCLE",
    name: "Bicycle",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: true,
    isTossable: false,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  BLUE_CARD: {
    id: "BLUE_CARD",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x74,
    inGameName: "BLUE CARD",
    name: "Blue Card",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "STAY",
    battleMenuAction: "NONE",
  },
  CARD_KEY: {
    id: "CARD_KEY",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x7F,
    inGameName: "CARD KEY",
    name: "Card Key",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  CLEAR_BELL: {
    id: "CLEAR_BELL",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x46,
    inGameName: "CLEAR BELL",
    name: "Clear Bell",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  COIN_CASE: {
    id: "COIN_CASE",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x36,
    inGameName: "COIN CASE",
    name: "Coin Case",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "STAY",
    battleMenuAction: "NONE",
  },
  EGG_TICKET: {
    id: "EGG_TICKET",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x81,
    inGameName: "EGG TICKET",
    name: "Egg Ticket",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  GOOD_ROD: {
    id: "GOOD_ROD",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x3B,
    inGameName: "GOOD ROD",
    name: "Good Rod",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: true,
    isTossable: false,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  GS_BALL: {
    id: "GS_BALL",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x73,
    inGameName: "GS BALL",
    name: "GS Ball",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  ITEMFINDER: {
    id: "ITEMFINDER",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x37,
    inGameName: "ITEMFINDER",
    name: "Itemfinder",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: true,
    isTossable: false,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  LOST_ITEM: {
    id: "LOST_ITEM",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x82,
    inGameName: "LOST ITEM",
    name: "Lost Item",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MACHINE_PART: {
    id: "MACHINE_PART",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x80,
    inGameName: "MACHINE PART",
    name: "Machine Part",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MYSTERY_EGG: {
    id: "MYSTERY_EGG",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x45,
    inGameName: "MYSTERY EGG",
    name: "Mystery Egg",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  OLD_ROD: {
    id: "OLD_ROD",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x3A,
    inGameName: "OLD ROD",
    name: "Old Rod",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: true,
    isTossable: false,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  PASS: {
    id: "PASS",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x86,
    inGameName: "PASS",
    name: "Pass",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  RAINBOW_WING: {
    id: "RAINBOW_WING",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0xB2,
    inGameName: "RAINBOW WING",
    name: "Rainbow Wing",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  RED_SCALE: {
    id: "RED_SCALE",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x42,
    inGameName: "RED SCALE",
    name: "Red Scale",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SECRETPOTION: {
    id: "SECRETPOTION",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x43,
    inGameName: "SECRETPOTION",
    name: "Secretpotion",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SILVER_WING: {
    id: "SILVER_WING",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x47,
    inGameName: "SILVER WING",
    name: "Silver Wing",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SQUIRTBOTTLE: {
    id: "SQUIRTBOTTLE",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0xAF,
    inGameName: "SQUIRTBOTTLE",
    name: "Squirtbottle",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  S_S_TICKET: {
    id: "S_S_TICKET",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x44,
    inGameName: "S.S.TICKET",
    name: "S.S.Ticket",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SUPER_ROD: {
    id: "SUPER_ROD",
    type: "BAG_ITEM",
    category: "KEY_ITEMS",
    numericId: 0x3D,
    inGameName: "SUPER ROD",
    name: "Super Rod",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: true,
    isTossable: false,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  HM01: {
    id: "HM01",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF3,
    inGameName: "HM01",
    name: "HM01 (Cut)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  HM02: {
    id: "HM02",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF4,
    inGameName: "HM02",
    name: "HM02 (Fly)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  HM03: {
    id: "HM03",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF5,
    inGameName: "HM03",
    name: "HM03 (Surf)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  HM04: {
    id: "HM04",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF6,
    inGameName: "HM04",
    name: "HM04 (Strength)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  HM05: {
    id: "HM05",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF7,
    inGameName: "HM05",
    name: "HM05 (Flash)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  HM06: {
    id: "HM06",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF8,
    inGameName: "HM06",
    name: "HM06 (Whirlpool)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  HM07: {
    id: "HM07",
    type: "BAG_ITEM",
    category: "HMS",
    numericId: 0xF9,
    inGameName: "HM07",
    name: "HM07 (Waterfall)",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: false,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM01: {
    id: "TM01",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xBF,
    inGameName: "TM01",
    name: "TM01",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM02: {
    id: "TM02",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC0,
    inGameName: "TM02",
    name: "TM02 (Headbutt)",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM03: {
    id: "TM03",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC1,
    inGameName: "TM03",
    name: "TM03",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM04: {
    id: "TM04",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC2,
    inGameName: "TM04",
    name: "TM04",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM05: {
    id: "TM05",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC4,
    inGameName: "TM05",
    name: "TM05",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM06: {
    id: "TM06",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC5,
    inGameName: "TM06",
    name: "TM06",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM07: {
    id: "TM07",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC6,
    inGameName: "TM07",
    name: "TM07",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM08: {
    id: "TM08",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC7,
    inGameName: "TM08",
    name: "TM08 (Rock Smash)",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM09: {
    id: "TM09",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC8,
    inGameName: "TM09",
    name: "TM09",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM10: {
    id: "TM10",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xC9,
    inGameName: "TM10",
    name: "TM10",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM11: {
    id: "TM11",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCA,
    inGameName: "TM11",
    name: "TM11",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM12: {
    id: "TM12",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCB,
    inGameName: "TM12",
    name: "TM12 (Sweet Scent)",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM13: {
    id: "TM13",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCC,
    inGameName: "TM13",
    name: "TM13",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM14: {
    id: "TM14",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCD,
    inGameName: "TM14",
    name: "TM14",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM15: {
    id: "TM15",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCE,
    inGameName: "TM15",
    name: "TM15",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM16: {
    id: "TM16",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xCF,
    inGameName: "TM16",
    name: "TM16",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM17: {
    id: "TM17",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD0,
    inGameName: "TM17",
    name: "TM17",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM18: {
    id: "TM18",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD1,
    inGameName: "TM18",
    name: "TM18",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM19: {
    id: "TM19",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD2,
    inGameName: "TM19",
    name: "TM19",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM20: {
    id: "TM20",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD3,
    inGameName: "TM20",
    name: "TM20",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM21: {
    id: "TM21",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD4,
    inGameName: "TM21",
    name: "TM21",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM22: {
    id: "TM22",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD5,
    inGameName: "TM22",
    name: "TM22",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM23: {
    id: "TM23",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD6,
    inGameName: "TM23",
    name: "TM23",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM24: {
    id: "TM24",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD7,
    inGameName: "TM24",
    name: "TM24",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM25: {
    id: "TM25",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD8,
    inGameName: "TM25",
    name: "TM25",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM26: {
    id: "TM26",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xD9,
    inGameName: "TM26",
    name: "TM26",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM27: {
    id: "TM27",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDA,
    inGameName: "TM27",
    name: "TM27",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM28: {
    id: "TM28",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDB,
    inGameName: "TM28",
    name: "TM28 (Dig)",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM29: {
    id: "TM29",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDD,
    inGameName: "TM29",
    name: "TM29",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM30: {
    id: "TM30",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDE,
    inGameName: "TM30",
    name: "TM30",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM31: {
    id: "TM31",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xDF,
    inGameName: "TM31",
    name: "TM31",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM32: {
    id: "TM32",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE0,
    inGameName: "TM32",
    name: "TM32",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM33: {
    id: "TM33",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE1,
    inGameName: "TM33",
    name: "TM33",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM34: {
    id: "TM34",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE2,
    inGameName: "TM34",
    name: "TM34",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM35: {
    id: "TM35",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE3,
    inGameName: "TM35",
    name: "TM35",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM36: {
    id: "TM36",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE4,
    inGameName: "TM36",
    name: "TM36",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM37: {
    id: "TM37",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE5,
    inGameName: "TM37",
    name: "TM37",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM38: {
    id: "TM38",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE6,
    inGameName: "TM38",
    name: "TM38",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM39: {
    id: "TM39",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE7,
    inGameName: "TM39",
    name: "TM39",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM40: {
    id: "TM40",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE8,
    inGameName: "TM40",
    name: "TM40",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM41: {
    id: "TM41",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xE9,
    inGameName: "TM41",
    name: "TM41",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM42: {
    id: "TM42",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEA,
    inGameName: "TM42",
    name: "TM42",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM43: {
    id: "TM43",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEB,
    inGameName: "TM43",
    name: "TM43",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM44: {
    id: "TM44",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEC,
    inGameName: "TM44",
    name: "TM44",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM45: {
    id: "TM45",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xED,
    inGameName: "TM45",
    name: "TM45",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM46: {
    id: "TM46",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEE,
    inGameName: "TM46",
    name: "TM46",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM47: {
    id: "TM47",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xEF,
    inGameName: "TM47",
    name: "TM47",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM48: {
    id: "TM48",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xF0,
    inGameName: "TM48",
    name: "TM48",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM49: {
    id: "TM49",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xF1,
    inGameName: "TM49",
    name: "TM49",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TM50: {
    id: "TM50",
    type: "BAG_ITEM",
    category: "TMS",
    numericId: 0xF2,
    inGameName: "TM50",
    name: "TM50",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  AMULET_COIN: {
    id: "AMULET_COIN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5B,
    inGameName: "AMULET COIN",
    name: "Amulet Coin",
    price: 100,
    holdEffectId: "AMULET_COIN",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  ANTIDOTE: {
    id: "ANTIDOTE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x09,
    inGameName: "ANTIDOTE",
    name: "Antidote",
    price: 100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  AWAKENING: {
    id: "AWAKENING",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0C,
    inGameName: "AWAKENING",
    name: "Awakening",
    price: 250,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  BERRY_JUICE: {
    id: "BERRY_JUICE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x8B,
    inGameName: "BERRY JUICE",
    name: "Berry Juice",
    price: 100,
    holdEffectId: "BERRY",
    associatedValue: 20,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  BERRY: {
    id: "BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xAD,
    inGameName: "BERRY",
    name: "Berry",
    price: 10,
    holdEffectId: "BERRY",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  BERSERK_GENE: {
    id: "BERSERK_GENE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x98,
    inGameName: "BERSERK GENE",
    name: "Berserk Gene",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BIG_MUSHROOM: {
    id: "BIG_MUSHROOM",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x57,
    inGameName: "BIG MUSHROOM",
    name: "Big Mushroom",
    price: 5000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BIG_PEARL: {
    id: "BIG_PEARL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6F,
    inGameName: "BIG PEARL",
    name: "Big Pearl",
    price: 7500,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BITTER_BERRY: {
    id: "BITTER_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x53,
    inGameName: "BITTER BERRY",
    name: "Bitter Berry",
    price: 10,
    holdEffectId: "HEAL_CONFUSION",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "OPEN_PARTY",
  },
  BLACKBELT: {
    id: "BLACKBELT",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x62,
    inGameName: "BLACKBELT",
    name: "Blackbelt",
    price: 100,
    holdEffectId: "FIGHTING_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BLACKGLASSES: {
    id: "BLACKGLASSES",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x66,
    inGameName: "BLACKGLASSES",
    name: "Blackglasses",
    price: 100,
    holdEffectId: "DARK_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BLK_APRICORN: {
    id: "BLK_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x63,
    inGameName: "BLK APRICORN",
    name: "Blk Apricorn",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BLU_APRICORN: {
    id: "BLU_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x59,
    inGameName: "BLU APRICORN",
    name: "Blu Apricorn",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BLUESKY_MAIL: {
    id: "BLUESKY_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xBB,
    inGameName: "BLUESKY MAIL",
    name: "Bluesky Mail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BRICK_PIECE: {
    id: "BRICK_PIECE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB4,
    inGameName: "BRICK PIECE",
    name: "Brick Piece",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BRIGHTPOWDER: {
    id: "BRIGHTPOWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x03,
    inGameName: "BRIGHTPOWDER",
    name: "Brightpowder",
    price: 10,
    holdEffectId: "BRIGHTPOWDER",
    associatedValue: 20,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  BURN_HEAL: {
    id: "BURN_HEAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0A,
    inGameName: "BURN HEAL",
    name: "Burn Heal",
    price: 250,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  BURNT_BERRY: {
    id: "BURNT_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4F,
    inGameName: "BURNT BERRY",
    name: "Burnt Berry",
    price: 10,
    holdEffectId: "HEAL_FREEZE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  CALCIUM: {
    id: "CALCIUM",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1F,
    inGameName: "CALCIUM",
    name: "Calcium",
    price: 9800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  CARBOS: {
    id: "CARBOS",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1D,
    inGameName: "CARBOS",
    name: "Carbos",
    price: 9800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  CHARCOAL: {
    id: "CHARCOAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x8A,
    inGameName: "CHARCOAL",
    name: "Charcoal",
    price: 9800,
    holdEffectId: "FIRE_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  CLEANSE_TAG: {
    id: "CLEANSE_TAG",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5E,
    inGameName: "CLEANSE TAG",
    name: "Cleanse Tag",
    price: 200,
    holdEffectId: "CLEANSE_TAG",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  DIRE_HIT: {
    id: "DIRE_HIT",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2C,
    inGameName: "DIRE HIT",
    name: "Dire Hit",
    price: 650,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  DRAGON_FANG: {
    id: "DRAGON_FANG",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x90,
    inGameName: "DRAGON FANG",
    name: "Dragon Fang",
    price: 100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  DRAGON_SCALE: {
    id: "DRAGON_SCALE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x97,
    inGameName: "DRAGON SCALE",
    name: "Dragon Scale",
    price: 2100,
    holdEffectId: "DRAGON_BOOST",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  ELIXER: {
    id: "ELIXER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x41,
    inGameName: "ELIXER",
    name: "Elixer",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  ENERGY_ROOT: {
    id: "ENERGY_ROOT",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7A,
    inGameName: "ENERGY ROOT",
    name: "Energy Root",
    price: 800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  ENERGYPOWDER: {
    id: "ENERGYPOWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x79,
    inGameName: "ENERGYPOWDER",
    name: "Energypowder",
    price: 500,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  EON_MAIL: {
    id: "EON_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB9,
    inGameName: "EON MAIL",
    name: "Eon Mail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  ESCAPE_ROPE: {
    id: "ESCAPE_ROPE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x13,
    inGameName: "ESCAPE ROPE",
    name: "Escape Rope",
    price: 550,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  ETHER: {
    id: "ETHER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x3F,
    inGameName: "ETHER",
    name: "Ether",
    price: 1200,
    holdEffectId: "NONE",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  EVERSTONE: {
    id: "EVERSTONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x70,
    inGameName: "EVERSTONE",
    name: "Everstone",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  EXP_SHARE: {
    id: "EXP_SHARE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x39,
    inGameName: "EXP.SHARE",
    name: "Exp Share",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  FIRE_STONE: {
    id: "FIRE_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x16,
    inGameName: "FIRE STONE",
    name: "Fire Stone",
    price: 2100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  FLOWER_MAIL: {
    id: "FLOWER_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x9E,
    inGameName: "FLOWER MAIL",
    name: "Flower Mail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  FOCUS_BAND: {
    id: "FOCUS_BAND",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x77,
    inGameName: "FOCUS BAND",
    name: "Focus Band",
    price: 200,
    holdEffectId: "FOCUS_BAND",
    associatedValue: 30,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  FRESH_WATER: {
    id: "FRESH_WATER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2E,
    inGameName: "FRESH WATER",
    name: "Fresh Water",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 50,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  FULL_HEAL: {
    id: "FULL_HEAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x26,
    inGameName: "FULL HEAL",
    name: "Full Heal",
    price: 600,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  FULL_RESTORE: {
    id: "FULL_RESTORE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0E,
    inGameName: "FULL RESTORE",
    name: "Full Restore",
    price: 3000,
    holdEffectId: "NONE",
    associatedValue: -1,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  GOLD_BERRY: {
    id: "GOLD_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xAE,
    inGameName: "GOLD BERRY",
    name: "Gold Berry",
    price: 20,
    holdEffectId: "BERRY",
    associatedValue: 30,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  GOLD_LEAF: {
    id: "GOLD_LEAF",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4B,
    inGameName: "GOLD LEAF",
    name: "Gold Leaf",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  GORGEOUS_BOX: {
    id: "GORGEOUS_BOX",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xA8,
    inGameName: "GORGEOUS BOX",
    name: "Gorgeous Box",
    price: 10,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "STAY",
    battleMenuAction: "NONE",
  },
  GRN_APRICORN: {
    id: "GRN_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5D,
    inGameName: "GRN APRICORN",
    name: "Grn Apricorn",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  GUARD_SPEC: {
    id: "GUARD_SPEC",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x29,
    inGameName: "GUARD SPEC.",
    name: "Guard Spec",
    price: 700,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  HARD_STONE: {
    id: "HARD_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7D,
    inGameName: "HARD STONE",
    name: "Hard Stone",
    price: 100,
    holdEffectId: "ROCK_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  HEAL_POWDER: {
    id: "HEAL_POWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7B,
    inGameName: "HEAL POWDER",
    name: "Heal Powder",
    price: 450,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  HP_UP: {
    id: "HP_UP",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1A,
    inGameName: "HP UP",
    name: "Hp Up",
    price: 9800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  HYPER_POTION: {
    id: "HYPER_POTION",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x10,
    inGameName: "HYPER POTION",
    name: "Hyper Potion",
    price: 1200,
    holdEffectId: "NONE",
    associatedValue: 200,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  ICE_BERRY: {
    id: "ICE_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x50,
    inGameName: "ICE BERRY",
    name: "Ice Berry",
    price: 10,
    holdEffectId: "HEAL_BURN",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  ICE_HEAL: {
    id: "ICE_HEAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0B,
    inGameName: "ICE HEAL",
    name: "Ice Heal",
    price: 250,
    holdEffectId: "HEAL_BURN",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  IRON: {
    id: "IRON",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1C,
    inGameName: "IRON",
    name: "Iron",
    price: 9800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  KINGS_ROCK: {
    id: "KINGS_ROCK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x52,
    inGameName: "KING'S ROCK",
    name: "Kings Rock",
    price: 100,
    holdEffectId: "FLINCH",
    associatedValue: 30,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  LEAF_STONE: {
    id: "LEAF_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x22,
    inGameName: "LEAF STONE",
    name: "Leaf Stone",
    price: 2100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  LEFTOVERS: {
    id: "LEFTOVERS",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x92,
    inGameName: "LEFTOVERS",
    name: "Leftovers",
    price: 200,
    holdEffectId: "LEFTOVERS",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  LEMONADE: {
    id: "LEMONADE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x30,
    inGameName: "LEMONADE",
    name: "Lemonade",
    price: 350,
    holdEffectId: "NONE",
    associatedValue: 80,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  LIGHT_BALL: {
    id: "LIGHT_BALL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xA3,
    inGameName: "LIGHT BALL",
    name: "Light Ball",
    price: 100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  LITEBLUEMAIL: {
    id: "LITEBLUEMAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB6,
    inGameName: "LITEBLUEMAIL",
    name: "Litebluemail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  LOVELY_MAIL: {
    id: "LOVELY_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB8,
    inGameName: "LOVELY MAIL",
    name: "Lovely Mail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  LUCKY_EGG: {
    id: "LUCKY_EGG",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7E,
    inGameName: "LUCKY EGG",
    name: "Lucky Egg",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  LUCKY_PUNCH: {
    id: "LUCKY_PUNCH",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1E,
    inGameName: "LUCKY PUNCH",
    name: "Lucky Punch",
    price: 10,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MAGNET: {
    id: "MAGNET",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6C,
    inGameName: "MAGNET",
    name: "Magnet",
    price: 100,
    holdEffectId: "ELECTRIC_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MAX_ELIXER: {
    id: "MAX_ELIXER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x15,
    inGameName: "MAX ELIXER",
    name: "Max Elixer",
    price: 4500,
    holdEffectId: "NONE",
    associatedValue: -1,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  MAX_ETHER: {
    id: "MAX_ETHER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x40,
    inGameName: "MAX ETHER",
    name: "Max Ether",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: -1,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  MAX_POTION: {
    id: "MAX_POTION",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0F,
    inGameName: "MAX POTION",
    name: "Max Potion",
    price: 2500,
    holdEffectId: "NONE",
    associatedValue: -1,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  MAX_REPEL: {
    id: "MAX_REPEL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2B,
    inGameName: "MAX REPEL",
    name: "Max Repel",
    price: 700,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "STAY",
    battleMenuAction: "NONE",
  },
  MAX_REVIVE: {
    id: "MAX_REVIVE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x28,
    inGameName: "MAX REVIVE",
    name: "Max Revive",
    price: 4000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  METAL_COAT: {
    id: "METAL_COAT",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x8F,
    inGameName: "METAL COAT",
    name: "Metal Coat",
    price: 100,
    holdEffectId: "STEEL_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  METAL_POWDER: {
    id: "METAL_POWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x23,
    inGameName: "METAL POWDER",
    name: "Metal Powder",
    price: 10,
    holdEffectId: "METAL_POWDER",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MINT_BERRY: {
    id: "MINT_BERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x54,
    inGameName: "MINT BERRY",
    name: "Mint Berry",
    price: 10,
    holdEffectId: "HEAL_SLEEP",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  MIRACLE_SEED: {
    id: "MIRACLE_SEED",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x75,
    inGameName: "MIRACLE SEED",
    name: "Miracle Seed",
    price: 100,
    holdEffectId: "GRASS_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MIRACLEBERRY: {
    id: "MIRACLEBERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6D,
    inGameName: "MIRACLEBERRY",
    name: "Miracleberry",
    price: 10,
    holdEffectId: "HEAL_STATUS",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  MIRAGE_MAIL: {
    id: "MIRAGE_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xBD,
    inGameName: "MIRAGE MAIL",
    name: "Mirage Mail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MOOMOO_MILK: {
    id: "MOOMOO_MILK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x48,
    inGameName: "MOOMOO MILK",
    name: "Moomoo Milk",
    price: 500,
    holdEffectId: "NONE",
    associatedValue: 100,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  MOON_STONE: {
    id: "MOON_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x08,
    inGameName: "MOON STONE",
    name: "Moon Stone",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  MORPH_MAIL: {
    id: "MORPH_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xBA,
    inGameName: "MORPH MAIL",
    name: "Morph Mail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MUSIC_MAIL: {
    id: "MUSIC_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xBC,
    inGameName: "MUSIC MAIL",
    name: "Music Mail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  MYSTERYBERRY: {
    id: "MYSTERYBERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x96,
    inGameName: "MYSTERYBERRY",
    name: "Mysteryberry",
    price: 10,
    holdEffectId: "RESTORE_PP",
    associatedValue: -1,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  MYSTIC_WATER: {
    id: "MYSTIC_WATER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5F,
    inGameName: "MYSTIC WATER",
    name: "Mystic Water",
    price: 100,
    holdEffectId: "WATER_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  NEVERMELTICE: {
    id: "NEVERMELTICE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6B,
    inGameName: "NEVERMELTICE",
    name: "Nevermeltice",
    price: 100,
    holdEffectId: "ICE_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  NORMAL_BOX: {
    id: "NORMAL_BOX",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xA7,
    inGameName: "NORMAL BOX",
    name: "Normal Box",
    price: 10,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "STAY",
    battleMenuAction: "NONE",
  },
  NUGGET: {
    id: "NUGGET",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x24,
    inGameName: "NUGGET",
    name: "Nugget",
    price: 10000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  PARLYZ_HEAL: {
    id: "PARLYZ_HEAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x0D,
    inGameName: "PARLYZ HEAL",
    name: "Parlyz Heal",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  PEARL: {
    id: "PEARL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6E,
    inGameName: "PEARL",
    name: "Pearl",
    price: 1400,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  PINK_BOW: {
    id: "PINK_BOW",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x68,
    inGameName: "PINK BOW",
    name: "Pink Bow",
    price: 100,
    holdEffectId: "NORMAL_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  PNK_APRICORN: {
    id: "PNK_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x65,
    inGameName: "PNK APRICORN",
    name: "Pnk Apricorn",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  POISON_BARB: {
    id: "POISON_BARB",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x51,
    inGameName: "POISON BARB",
    name: "Poison Barb",
    price: 100,
    holdEffectId: "POISON_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  POKE_DOLL: {
    id: "POKE_DOLL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x25,
    inGameName: "POKE DOLL",
    name: "Poké Doll",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  POLKADOT_BOW: {
    id: "POLKADOT_BOW",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xAA,
    inGameName: "POLKADOT BOW",
    name: "Polkadot Bow",
    price: 100,
    holdEffectId: "NORMAL_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  PORTRAITMAIL: {
    id: "PORTRAITMAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB7,
    inGameName: "PORTRAITMAIL",
    name: "Portraitmail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  POTION: {
    id: "POTION",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x12,
    inGameName: "POTION",
    name: "Potion",
    price: 300,
    holdEffectId: "NONE",
    associatedValue: 20,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  PP_UP: {
    id: "PP_UP",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x3E,
    inGameName: "PP UP",
    name: "Pp Up",
    price: 9800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  PROTEIN: {
    id: "PROTEIN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x1B,
    inGameName: "PROTEIN",
    name: "Protein",
    price: 9800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  PRZCUREBERRY: {
    id: "PRZCUREBERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4E,
    inGameName: "PRZCUREBERRY",
    name: "Przcureberry",
    price: 10,
    holdEffectId: "HEAL_PARALYZE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  PSNCUREBERRY: {
    id: "PSNCUREBERRY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4A,
    inGameName: "PSNCUREBERRY",
    name: "Psncureberry",
    price: 10,
    holdEffectId: "HEAL_POISON",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  QUICK_CLAW: {
    id: "QUICK_CLAW",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x49,
    inGameName: "QUICK CLAW",
    name: "Quick Claw",
    price: 100,
    holdEffectId: "NONE",
    associatedValue: 60,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  RAGECANDYBAR: {
    id: "RAGECANDYBAR",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x72,
    inGameName: "RAGECANDYBAR",
    name: "Ragecandybar",
    price: 300,
    holdEffectId: "NONE",
    associatedValue: 20,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  RARE_CANDY: {
    id: "RARE_CANDY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x20,
    inGameName: "RARE CANDY",
    name: "Rare Candy",
    price: 4800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  RED_APRICORN: {
    id: "RED_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x55,
    inGameName: "RED APRICORN",
    name: "Red Apricorn",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  REPEL: {
    id: "REPEL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x14,
    inGameName: "REPEL",
    name: "Repel",
    price: 350,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "STAY",
    battleMenuAction: "NONE",
  },
  REVIVAL_HERB: {
    id: "REVIVAL_HERB",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x7C,
    inGameName: "REVIVAL HERB",
    name: "Revival Herb",
    price: 2800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  REVIVE: {
    id: "REVIVE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x27,
    inGameName: "REVIVE",
    name: "Revive",
    price: 1500,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  SACRED_ASH: {
    id: "SACRED_ASH",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x9C,
    inGameName: "SACRED ASH",
    name: "Sacred Ash",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "CLOSE",
    battleMenuAction: "NONE",
  },
  SCOPE_LENS: {
    id: "SCOPE_LENS",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x8C,
    inGameName: "SCOPE LENS",
    name: "Scope Lens",
    price: 200,
    holdEffectId: "CRITICAL_UP",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SHARP_BEAK: {
    id: "SHARP_BEAK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4D,
    inGameName: "SHARP BEAK",
    name: "Sharp Beak",
    price: 100,
    holdEffectId: "FLYING_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SILVER_LEAF: {
    id: "SILVER_LEAF",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x3C,
    inGameName: "SILVER LEAF",
    name: "Silver Leaf",
    price: 1000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SILVERPOWDER: {
    id: "SILVERPOWDER",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x58,
    inGameName: "SILVERPOWDER",
    name: "Silverpowder",
    price: 100,
    holdEffectId: "BUG_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SLOWPOKETAIL: {
    id: "SLOWPOKETAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x67,
    inGameName: "SLOWPOKETAIL",
    name: "Slowpoketail",
    price: 9800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SMOKE_BALL: {
    id: "SMOKE_BALL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x6A,
    inGameName: "SMOKE BALL",
    name: "Smoke Ball",
    price: 200,
    holdEffectId: "ESCAPE",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SODA_POP: {
    id: "SODA_POP",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2F,
    inGameName: "SODA POP",
    name: "Soda Pop",
    price: 300,
    holdEffectId: "NONE",
    associatedValue: 60,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  SOFT_SAND: {
    id: "SOFT_SAND",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x4C,
    inGameName: "SOFT SAND",
    name: "Soft Sand",
    price: 100,
    holdEffectId: "GROUND_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SPELL_TAG: {
    id: "SPELL_TAG",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x71,
    inGameName: "SPELL TAG",
    name: "Spell Tag",
    price: 100,
    holdEffectId: "GHOST_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  STAR_PIECE: {
    id: "STAR_PIECE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x84,
    inGameName: "STAR PIECE",
    name: "Star Piece",
    price: 9800,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  STARDUST: {
    id: "STARDUST",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x83,
    inGameName: "STARDUST",
    name: "Stardust",
    price: 2000,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  STICK: {
    id: "STICK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x69,
    inGameName: "STICK",
    name: "Stick",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  SUN_STONE: {
    id: "SUN_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xA9,
    inGameName: "SUN STONE",
    name: "Sun Stone",
    price: 2100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  SUPER_POTION: {
    id: "SUPER_POTION",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x11,
    inGameName: "SUPER POTION",
    name: "Super Potion",
    price: 700,
    holdEffectId: "NONE",
    associatedValue: 50,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "OPEN_PARTY",
  },
  SUPER_REPEL: {
    id: "SUPER_REPEL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x2A,
    inGameName: "SUPER REPEL",
    name: "Super Repel",
    price: 500,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "STAY",
    battleMenuAction: "NONE",
  },
  SURF_MAIL: {
    id: "SURF_MAIL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xB5,
    inGameName: "SURF MAIL",
    name: "Surf Mail",
    price: 50,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  THICK_CLUB: {
    id: "THICK_CLUB",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x76,
    inGameName: "THICK CLUB",
    name: "Thick Club",
    price: 500,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  THUNDERSTONE: {
    id: "THUNDERSTONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x17,
    inGameName: "THUNDERSTONE",
    name: "Thunderstone",
    price: 2100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  TINYMUSHROOM: {
    id: "TINYMUSHROOM",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x56,
    inGameName: "TINYMUSHROOM",
    name: "Tinymushroom",
    price: 500,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  TWISTEDSPOON: {
    id: "TWISTEDSPOON",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x60,
    inGameName: "TWISTEDSPOON",
    name: "Twistedspoon",
    price: 100,
    holdEffectId: "PSYCHIC_BOOST",
    associatedValue: 10,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  UP_GRADE: {
    id: "UP_GRADE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0xAC,
    inGameName: "UP-GRADE",
    name: "Up Grade",
    price: 2100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  WATER_STONE: {
    id: "WATER_STONE",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x18,
    inGameName: "WATER STONE",
    name: "Water Stone",
    price: 2100,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "OPEN_PARTY",
    battleMenuAction: "NONE",
  },
  WHT_APRICORN: {
    id: "WHT_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x61,
    inGameName: "WHT APRICORN",
    name: "Wht Apricorn",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  X_ACCURACY: {
    id: "X_ACCURACY",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x21,
    inGameName: "X ACCURACY",
    name: "X Accuracy",
    price: 950,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  X_ATTACK: {
    id: "X_ATTACK",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x31,
    inGameName: "X ATTACK",
    name: "X Attack",
    price: 500,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  X_DEFEND: {
    id: "X_DEFEND",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x33,
    inGameName: "X DEFEND",
    name: "X Defend",
    price: 550,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  X_SPECIAL: {
    id: "X_SPECIAL",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x35,
    inGameName: "X SPECIAL",
    name: "X Special",
    price: 350,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  X_SPEED: {
    id: "X_SPEED",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x34,
    inGameName: "X SPEED",
    name: "X Speed",
    price: 350,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  YLW_APRICORN: {
    id: "YLW_APRICORN",
    type: "BAG_ITEM",
    category: "REGULAR_ITEMS",
    numericId: 0x5C,
    inGameName: "YLW APRICORN",
    name: "Ylw Apricorn",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "NONE",
  },
  POKE_BALL: {
    id: "POKE_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x05,
    inGameName: "POKE BALL",
    name: "Poké Ball",
    price: 200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  GREAT_BALL: {
    id: "GREAT_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x04,
    inGameName: "GREAT BALL",
    name: "Great Ball",
    price: 600,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  ULTRA_BALL: {
    id: "ULTRA_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x02,
    inGameName: "ULTRA BALL",
    name: "Ultra Ball",
    price: 1200,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  MASTER_BALL: {
    id: "MASTER_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x01,
    inGameName: "MASTER BALL",
    name: "Master Ball",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  FAST_BALL: {
    id: "FAST_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA1,
    inGameName: "FAST BALL",
    name: "Fast Ball",
    price: 150,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  FRIEND_BALL: {
    id: "FRIEND_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA4,
    inGameName: "FRIEND BALL",
    name: "Friend Ball",
    price: 150,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  HEAVY_BALL: {
    id: "HEAVY_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x9D,
    inGameName: "HEAVY BALL",
    name: "Heavy Ball",
    price: 150,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  LEVEL_BALL: {
    id: "LEVEL_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0x9F,
    inGameName: "LEVEL BALL",
    name: "Level Ball",
    price: 150,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  LOVE_BALL: {
    id: "LOVE_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA6,
    inGameName: "LOVE BALL",
    name: "Love Ball",
    price: 150,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  LURE_BALL: {
    id: "LURE_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA0,
    inGameName: "LURE BALL",
    name: "Lure Ball",
    price: 150,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  MOON_BALL: {
    id: "MOON_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xA5,
    inGameName: "MOON BALL",
    name: "Moon Ball",
    price: 150,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
  PARK_BALL: {
    id: "PARK_BALL",
    type: "BAG_ITEM",
    category: "BALLS",
    numericId: 0xB1,
    inGameName: "PARK BALL",
    name: "Park Ball",
    price: 0,
    holdEffectId: "NONE",
    associatedValue: 0,
    isRegisterable: false,
    isTossable: true,
    fieldMenuAction: "NONE",
    battleMenuAction: "CLOSE",
  },
}