import type { Mart } from "@shared/types/gameData/mart"
import type { MartId } from "@shared/types/gameDataIds/marts"

export const martsMap: IdMap<MartId, Mart> = {
  CHERRYGROVE_1: {
    id: "CHERRYGROVE_1",
    groupId: "CHERRYGROVE",
    items: [
      "POTION",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
    ],
  },
  CHERRYGROVE_2: {
    id: "CHERRYGROVE_2",
    groupId: "CHERRYGROVE",
    items: [
      "POKE_BALL",
      "POTION",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
    ],
  },
  VIOLET: {
    id: "VIOLET",
    groupId: "VIOLET",
    items: [
      "POKE_BALL",
      "POTION",
      "ESCAPE_ROPE",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
      "X_DEFEND",
      "X_ATTACK",
      "X_SPEED",
      "FLOWER_MAIL",
    ],
  },
  AZALEA: {
    id: "AZALEA",
    groupId: "AZALEA",
    items: [
      "CHARCOAL",
      "POKE_BALL",
      "POTION",
      "SUPER_POTION",
      "ESCAPE_ROPE",
      "REPEL",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "FLOWER_MAIL",
    ],
  },
  CIANWOOD: {
    id: "CIANWOOD",
    groupId: "CIANWOOD",
    items: [
      "POTION",
      "SUPER_POTION",
      "HYPER_POTION",
      "FULL_HEAL",
      "REVIVE",
    ],
  },
  GOLDENROD_2F_1: {
    id: "GOLDENROD_2F_1",
    groupId: "GOLDENROD_2F_1",
    items: [
      "POTION",
      "SUPER_POTION",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
      "BURN_HEAL",
      "ICE_HEAL",
    ],
  },
  GOLDENROD_2F_2: {
    id: "GOLDENROD_2F_2",
    groupId: "GOLDENROD_2F_2",
    items: [
      "POKE_BALL",
      "GREAT_BALL",
      "ESCAPE_ROPE",
      "REPEL",
      "REVIVE",
      "FULL_HEAL",
      "POKE_DOLL",
      "FLOWER_MAIL",
    ],
  },
  GOLDENROD_3F: {
    id: "GOLDENROD_3F",
    groupId: "GOLDENROD_3F",
    items: [
      "X_SPEED",
      "X_SPECIAL",
      "X_DEFEND",
      "X_ATTACK",
      "DIRE_HIT",
      "GUARD_SPEC",
      "X_ACCURACY",
    ],
  },
  GOLDENROD_4F: {
    id: "GOLDENROD_4F",
    groupId: "GOLDENROD_4F",
    items: [
      "PROTEIN",
      "IRON",
      "CARBOS",
      "CALCIUM",
      "HP_UP",
    ],
  },
  GOLDENROD_5F_1: {
    id: "GOLDENROD_5F_1",
    groupId: "GOLDENROD_5F",
    items: [
      "TM41",
      "TM48",
      "TM33",
    ],
  },
  GOLDENROD_5F_2: {
    id: "GOLDENROD_5F_2",
    groupId: "GOLDENROD_5F",
    items: [
      "TM41",
      "TM48",
      "TM33",
      "TM02",
    ],
  },
  GOLDENROD_5F_3: {
    id: "GOLDENROD_5F_3",
    groupId: "GOLDENROD_5F",
    items: [
      "TM41",
      "TM48",
      "TM33",
      "TM08",
    ],
  },
  GOLDENROD_5F_4: {
    id: "GOLDENROD_5F_4",
    groupId: "GOLDENROD_5F",
    items: [
      "TM41",
      "TM48",
      "TM33",
      "TM02",
      "TM08",
    ],
  },
  OLIVINE: {
    id: "OLIVINE",
    groupId: "OLIVINE",
    items: [
      "GREAT_BALL",
      "SUPER_POTION",
      "HYPER_POTION",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
      "ICE_HEAL",
      "SUPER_REPEL",
      "SURF_MAIL",
    ],
  },
  ECRUTEAK: {
    id: "ECRUTEAK",
    groupId: "ECRUTEAK",
    items: [
      "POKE_BALL",
      "GREAT_BALL",
      "POTION",
      "SUPER_POTION",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
      "BURN_HEAL",
      "ICE_HEAL",
      "REVIVE",
    ],
  },
  MAHOGANY_1: {
    id: "MAHOGANY_1",
    groupId: "MAHOGANY_1",
    items: [
      "TINYMUSHROOM",
      "SLOWPOKETAIL",
      "POKE_BALL",
      "POTION",
    ],
  },
  MAHOGANY_2: {
    id: "MAHOGANY_2",
    groupId: "MAHOGANY_2",
    items: [
      "RAGECANDYBAR",
      "GREAT_BALL",
      "SUPER_POTION",
      "HYPER_POTION",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "SUPER_REPEL",
      "REVIVE",
      "FLOWER_MAIL",
    ],
  },
  BLACKTHORN: {
    id: "BLACKTHORN",
    groupId: "BLACKTHORN",
    items: [
      "GREAT_BALL",
      "ULTRA_BALL",
      "HYPER_POTION",
      "MAX_POTION",
      "FULL_HEAL",
      "REVIVE",
      "MAX_REPEL",
      "X_DEFEND",
      "X_ATTACK",
    ],
  },
  VIRIDIAN: {
    id: "VIRIDIAN",
    groupId: "VIRIDIAN",
    items: [
      "ULTRA_BALL",
      "HYPER_POTION",
      "FULL_HEAL",
      "REVIVE",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
      "BURN_HEAL",
      "FLOWER_MAIL",
    ],
  },
  PEWTER: {
    id: "PEWTER",
    groupId: "PEWTER",
    items: [
      "GREAT_BALL",
      "SUPER_POTION",
      "SUPER_REPEL",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
      "BURN_HEAL",
    ],
  },
  CERULEAN: {
    id: "CERULEAN",
    groupId: "CERULEAN",
    items: [
      "GREAT_BALL",
      "ULTRA_BALL",
      "SUPER_POTION",
      "SUPER_REPEL",
      "FULL_HEAL",
      "X_DEFEND",
      "X_ATTACK",
      "DIRE_HIT",
      "SURF_MAIL",
    ],
  },
  LAVENDER: {
    id: "LAVENDER",
    groupId: "LAVENDER",
    items: [
      "GREAT_BALL",
      "POTION",
      "SUPER_POTION",
      "MAX_REPEL",
      "ANTIDOTE",
      "PARLYZ_HEAL",
      "AWAKENING",
      "BURN_HEAL",
    ],
  },
  VERMILION: {
    id: "VERMILION",
    groupId: "VERMILION",
    items: [
      "ULTRA_BALL",
      "SUPER_POTION",
      "HYPER_POTION",
      "REVIVE",
      "PARLYZ_HEAL",
      "AWAKENING",
      "BURN_HEAL",
      "LITEBLUEMAIL",
    ],
  },
  CELADON_2F_1: {
    id: "CELADON_2F_1",
    groupId: "CELADON_2F_1",
    items: [
      "POTION",
      "SUPER_POTION",
      "HYPER_POTION",
      "MAX_POTION",
      "REVIVE",
      "SUPER_REPEL",
      "MAX_REPEL",
    ],
  },
  CELADON_2F_2: {
    id: "CELADON_2F_2",
    groupId: "CELADON_2F_2",
    items: [
      "POKE_BALL",
      "GREAT_BALL",
      "ULTRA_BALL",
      "ESCAPE_ROPE",
      "FULL_HEAL",
      "ANTIDOTE",
      "BURN_HEAL",
      "ICE_HEAL",
      "AWAKENING",
      "PARLYZ_HEAL",
    ],
  },
  CELADON_3F: {
    id: "CELADON_3F",
    groupId: "CELADON_3F",
    items: [
      "TM10",
      "TM11",
      "TM17",
      "TM18",
      "TM37",
    ],
  },
  CELADON_4F: {
    id: "CELADON_4F",
    groupId: "CELADON_4F",
    items: [
      "POKE_DOLL",
      "LOVELY_MAIL",
      "SURF_MAIL",
    ],
  },
  CELADON_5F_1: {
    id: "CELADON_5F_1",
    groupId: "CELADON_5F_1",
    items: [
      "HP_UP",
      "PROTEIN",
      "IRON",
      "CARBOS",
      "CALCIUM",
    ],
  },
  CELADON_5F_2: {
    id: "CELADON_5F_2",
    groupId: "CELADON_5F_2",
    items: [
      "X_ACCURACY",
      "GUARD_SPEC",
      "DIRE_HIT",
      "X_ATTACK",
      "X_DEFEND",
      "X_SPEED",
      "X_SPECIAL",
    ],
  },
  FUCHSIA: {
    id: "FUCHSIA",
    groupId: "FUCHSIA",
    items: [
      "GREAT_BALL",
      "ULTRA_BALL",
      "SUPER_POTION",
      "HYPER_POTION",
      "FULL_HEAL",
      "MAX_REPEL",
      "FLOWER_MAIL",
    ],
  },
  SAFFRON: {
    id: "SAFFRON",
    groupId: "SAFFRON",
    items: [
      "GREAT_BALL",
      "ULTRA_BALL",
      "HYPER_POTION",
      "MAX_POTION",
      "FULL_HEAL",
      "X_ATTACK",
      "X_DEFEND",
      "FLOWER_MAIL",
    ],
  },
  MT_MOON: {
    id: "MT_MOON",
    groupId: "MT_MOON",
    items: [
      "POKE_DOLL",
      "FRESH_WATER",
      "SODA_POP",
      "LEMONADE",
      "REPEL",
      "PORTRAITMAIL",
    ],
  },
  INDIGO_PLATEAU: {
    id: "INDIGO_PLATEAU",
    groupId: "INDIGO_PLATEAU",
    items: [
      "ULTRA_BALL",
      "MAX_REPEL",
      "HYPER_POTION",
      "MAX_POTION",
      "FULL_RESTORE",
      "REVIVE",
      "FULL_HEAL",
    ],
  },
  UNDERGROUND: {
    id: "UNDERGROUND",
    groupId: "UNDERGROUND",
    items: [
      "ENERGYPOWDER",
      "ENERGY_ROOT",
      "HEAL_POWDER",
      "REVIVAL_HERB",
    ],
  },
  GOLDENROD_5F_5: {
    id: "GOLDENROD_5F_5",
    groupId: "GOLDENROD_5F",
    items: [],
  },
  GOLDENROD_5F_6: {
    id: "GOLDENROD_5F_6",
    groupId: "GOLDENROD_5F",
    items: [],
  },
  GOLDENROD_5F_7: {
    id: "GOLDENROD_5F_7",
    groupId: "GOLDENROD_5F",
    items: [],
  },
  GOLDENROD_5F_8: {
    id: "GOLDENROD_5F_8",
    groupId: "GOLDENROD_5F",
    items: [],
  },
} as const