import type { MoveEffectId } from "@shared/types/gameDataIds/moveEffects"
import type { MoveId } from "@shared/types/gameDataIds/moves"
import type { PokemonTypeId } from "@shared/types/gameDataIds/pokemonTypes"

export type Move = {
  id: MoveId,
  numericId: number,
  name: string,
  type: PokemonTypeId,
  power: number,
  accuracy: number,
  pp: number,
  effect: MoveEffectId,
  secondaryEffectChance: number,
  isFieldMove: boolean,
}

export const movesMap: IdMap<MoveId, Move> = {
  POUND: {
    id: "POUND",
    numericId: 0x01,
    name: "Pound",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  KARATE_CHOP: {
    id: "KARATE_CHOP",
    numericId: 0x02,
    name: "Karate Chop",
    type: "FIGHTING",
    power: 50,
    accuracy: 100,
    pp: 25,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DOUBLESLAP: {
    id: "DOUBLESLAP",
    numericId: 0x03,
    name: "Doubleslap",
    type: "NORMAL",
    power: 15,
    accuracy: 85,
    pp: 10,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  COMET_PUNCH: {
    id: "COMET_PUNCH",
    numericId: 0x04,
    name: "Comet Punch",
    type: "NORMAL",
    power: 18,
    accuracy: 85,
    pp: 15,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MEGA_PUNCH: {
    id: "MEGA_PUNCH",
    numericId: 0x05,
    name: "Mega Punch",
    type: "NORMAL",
    power: 80,
    accuracy: 85,
    pp: 20,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  PAY_DAY: {
    id: "PAY_DAY",
    numericId: 0x06,
    name: "Pay Day",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 20,
    effect: "PAY_DAY",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FIRE_PUNCH: {
    id: "FIRE_PUNCH",
    numericId: 0x07,
    name: "Fire Punch",
    type: "FIRE",
    power: 75,
    accuracy: 100,
    pp: 15,
    effect: "BURN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  ICE_PUNCH: {
    id: "ICE_PUNCH",
    numericId: 0x08,
    name: "Ice Punch",
    type: "ICE",
    power: 75,
    accuracy: 100,
    pp: 15,
    effect: "FREEZE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  THUNDERPUNCH: {
    id: "THUNDERPUNCH",
    numericId: 0x09,
    name: "Thunderpunch",
    type: "ELECTRIC",
    power: 75,
    accuracy: 100,
    pp: 15,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  SCRATCH: {
    id: "SCRATCH",
    numericId: 0x0A,
    name: "Scratch",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  VICEGRIP: {
    id: "VICEGRIP",
    numericId: 0x0B,
    name: "Vicegrip",
    type: "NORMAL",
    power: 55,
    accuracy: 100,
    pp: 30,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  GUILLOTINE: {
    id: "GUILLOTINE",
    numericId: 0x0C,
    name: "Guillotine",
    type: "NORMAL",
    power: 0,
    accuracy: 30,
    pp: 5,
    effect: "OHKO",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  RAZOR_WIND: {
    id: "RAZOR_WIND",
    numericId: 0x0D,
    name: "Razor Wind",
    type: "NORMAL",
    power: 80,
    accuracy: 75,
    pp: 10,
    effect: "RAZOR_WIND",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SWORDS_DANCE: {
    id: "SWORDS_DANCE",
    numericId: 0x0E,
    name: "Swords Dance",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "ATTACK_UP_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CUT: {
    id: "CUT",
    numericId: 0x0F,
    name: "Cut",
    type: "NORMAL",
    power: 50,
    accuracy: 95,
    pp: 30,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  GUST: {
    id: "GUST",
    numericId: 0x10,
    name: "Gust",
    type: "FLYING",
    power: 40,
    accuracy: 100,
    pp: 35,
    effect: "GUST",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  WING_ATTACK: {
    id: "WING_ATTACK",
    numericId: 0x11,
    name: "Wing Attack",
    type: "FLYING",
    power: 60,
    accuracy: 100,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  WHIRLWIND: {
    id: "WHIRLWIND",
    numericId: 0x12,
    name: "Whirlwind",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "FORCE_SWITCH",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FLY: {
    id: "FLY",
    numericId: 0x13,
    name: "Fly",
    type: "FLYING",
    power: 70,
    accuracy: 95,
    pp: 15,
    effect: "FLY",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  BIND: {
    id: "BIND",
    numericId: 0x14,
    name: "Bind",
    type: "NORMAL",
    power: 15,
    accuracy: 75,
    pp: 20,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SLAM: {
    id: "SLAM",
    numericId: 0x15,
    name: "Slam",
    type: "NORMAL",
    power: 80,
    accuracy: 75,
    pp: 20,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  VINE_WHIP: {
    id: "VINE_WHIP",
    numericId: 0x16,
    name: "Vine Whip",
    type: "GRASS",
    power: 35,
    accuracy: 100,
    pp: 10,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  STOMP: {
    id: "STOMP",
    numericId: 0x17,
    name: "Stomp",
    type: "NORMAL",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "STOMP",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  DOUBLE_KICK: {
    id: "DOUBLE_KICK",
    numericId: 0x18,
    name: "Double Kick",
    type: "FIGHTING",
    power: 30,
    accuracy: 100,
    pp: 30,
    effect: "DOUBLE_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MEGA_KICK: {
    id: "MEGA_KICK",
    numericId: 0x19,
    name: "Mega Kick",
    type: "NORMAL",
    power: 120,
    accuracy: 75,
    pp: 5,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  JUMP_KICK: {
    id: "JUMP_KICK",
    numericId: 0x1A,
    name: "Jump Kick",
    type: "FIGHTING",
    power: 70,
    accuracy: 95,
    pp: 25,
    effect: "JUMP_KICK",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ROLLING_KICK: {
    id: "ROLLING_KICK",
    numericId: 0x1B,
    name: "Rolling Kick",
    type: "FIGHTING",
    power: 60,
    accuracy: 85,
    pp: 15,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  SAND_ATTACK: {
    id: "SAND_ATTACK",
    numericId: 0x1C,
    name: "Sand Attack",
    type: "GROUND",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "ACCURACY_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  HEADBUTT: {
    id: "HEADBUTT",
    numericId: 0x1D,
    name: "Headbutt",
    type: "NORMAL",
    power: 70,
    accuracy: 100,
    pp: 15,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
    isFieldMove: true,
  },
  HORN_ATTACK: {
    id: "HORN_ATTACK",
    numericId: 0x1E,
    name: "Horn Attack",
    type: "NORMAL",
    power: 65,
    accuracy: 100,
    pp: 25,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FURY_ATTACK: {
    id: "FURY_ATTACK",
    numericId: 0x1F,
    name: "Fury Attack",
    type: "NORMAL",
    power: 15,
    accuracy: 85,
    pp: 20,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  HORN_DRILL: {
    id: "HORN_DRILL",
    numericId: 0x20,
    name: "Horn Drill",
    type: "NORMAL",
    power: 1,
    accuracy: 30,
    pp: 5,
    effect: "OHKO",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  TACKLE: {
    id: "TACKLE",
    numericId: 0x21,
    name: "Tackle",
    type: "NORMAL",
    power: 35,
    accuracy: 95,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BODY_SLAM: {
    id: "BODY_SLAM",
    numericId: 0x22,
    name: "Body Slam",
    type: "NORMAL",
    power: 85,
    accuracy: 100,
    pp: 15,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  WRAP: {
    id: "WRAP",
    numericId: 0x23,
    name: "Wrap",
    type: "NORMAL",
    power: 15,
    accuracy: 85,
    pp: 20,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  TAKE_DOWN: {
    id: "TAKE_DOWN",
    numericId: 0x24,
    name: "Take Down",
    type: "NORMAL",
    power: 90,
    accuracy: 85,
    pp: 20,
    effect: "RECOIL_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  THRASH: {
    id: "THRASH",
    numericId: 0x25,
    name: "Thrash",
    type: "NORMAL",
    power: 90,
    accuracy: 100,
    pp: 20,
    effect: "RAMPAGE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DOUBLE_EDGE: {
    id: "DOUBLE_EDGE",
    numericId: 0x26,
    name: "Double Edge",
    type: "NORMAL",
    power: 120,
    accuracy: 100,
    pp: 15,
    effect: "RECOIL_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  TAIL_WHIP: {
    id: "TAIL_WHIP",
    numericId: 0x27,
    name: "Tail Whip",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  POISON_STING: {
    id: "POISON_STING",
    numericId: 0x28,
    name: "Poison Sting",
    type: "POISON",
    power: 15,
    accuracy: 100,
    pp: 35,
    effect: "POISON_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  TWINEEDLE: {
    id: "TWINEEDLE",
    numericId: 0x29,
    name: "Twineedle",
    type: "BUG",
    power: 25,
    accuracy: 100,
    pp: 20,
    effect: "POISON_MULTI_HIT",
    secondaryEffectChance: 20,
    isFieldMove: false,
  },
  PIN_MISSILE: {
    id: "PIN_MISSILE",
    numericId: 0x2A,
    name: "Pin Missile",
    type: "BUG",
    power: 14,
    accuracy: 85,
    pp: 20,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  LEER: {
    id: "LEER",
    numericId: 0x2B,
    name: "Leer",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BITE: {
    id: "BITE",
    numericId: 0x2C,
    name: "Bite",
    type: "DARK",
    power: 60,
    accuracy: 100,
    pp: 25,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  GROWL: {
    id: "GROWL",
    numericId: 0x2D,
    name: "Growl",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "ATTACK_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ROAR: {
    id: "ROAR",
    numericId: 0x2E,
    name: "Roar",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "FORCE_SWITCH",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SING: {
    id: "SING",
    numericId: 0x2F,
    name: "Sing",
    type: "NORMAL",
    power: 0,
    accuracy: 55,
    pp: 15,
    effect: "SLEEP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SUPERSONIC: {
    id: "SUPERSONIC",
    numericId: 0x30,
    name: "Supersonic",
    type: "NORMAL",
    power: 0,
    accuracy: 55,
    pp: 20,
    effect: "CONFUSE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SONICBOOM: {
    id: "SONICBOOM",
    numericId: 0x31,
    name: "Sonicboom",
    type: "NORMAL",
    power: 20,
    accuracy: 90,
    pp: 20,
    effect: "STATIC_DAMAGE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DISABLE: {
    id: "DISABLE",
    numericId: 0x32,
    name: "Disable",
    type: "NORMAL",
    power: 0,
    accuracy: 55,
    pp: 20,
    effect: "DISABLE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ACID: {
    id: "ACID",
    numericId: 0x33,
    name: "Acid",
    type: "POISON",
    power: 40,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_DOWN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  EMBER: {
    id: "EMBER",
    numericId: 0x34,
    name: "Ember",
    type: "FIRE",
    power: 40,
    accuracy: 100,
    pp: 25,
    effect: "BURN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  FLAMETHROWER: {
    id: "FLAMETHROWER",
    numericId: 0x35,
    name: "Flamethrower",
    type: "FIRE",
    power: 95,
    accuracy: 100,
    pp: 15,
    effect: "BURN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  MIST: {
    id: "MIST",
    numericId: 0x36,
    name: "Mist",
    type: "ICE",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "MIST",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  WATER_GUN: {
    id: "WATER_GUN",
    numericId: 0x37,
    name: "Water Gun",
    type: "WATER",
    power: 40,
    accuracy: 100,
    pp: 25,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  HYDRO_PUMP: {
    id: "HYDRO_PUMP",
    numericId: 0x38,
    name: "Hydro Pump",
    type: "WATER",
    power: 120,
    accuracy: 80,
    pp: 5,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SURF: {
    id: "SURF",
    numericId: 0x39,
    name: "Surf",
    type: "WATER",
    power: 95,
    accuracy: 100,
    pp: 15,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  ICE_BEAM: {
    id: "ICE_BEAM",
    numericId: 0x3A,
    name: "Ice Beam",
    type: "ICE",
    power: 95,
    accuracy: 100,
    pp: 10,
    effect: "FREEZE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  BLIZZARD: {
    id: "BLIZZARD",
    numericId: 0x3B,
    name: "Blizzard",
    type: "ICE",
    power: 120,
    accuracy: 70,
    pp: 5,
    effect: "FREEZE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  PSYBEAM: {
    id: "PSYBEAM",
    numericId: 0x3C,
    name: "Psybeam",
    type: "PSYCHIC",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "CONFUSE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  BUBBLEBEAM: {
    id: "BUBBLEBEAM",
    numericId: 0x3D,
    name: "Bubblebeam",
    type: "WATER",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "SPEED_DOWN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  AURORA_BEAM: {
    id: "AURORA_BEAM",
    numericId: 0x3E,
    name: "Aurora Beam",
    type: "ICE",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "ATTACK_DOWN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  HYPER_BEAM: {
    id: "HYPER_BEAM",
    numericId: 0x3F,
    name: "Hyper Beam",
    type: "NORMAL",
    power: 150,
    accuracy: 90,
    pp: 5,
    effect: "HYPER_BEAM",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  PECK: {
    id: "PECK",
    numericId: 0x40,
    name: "Peck",
    type: "FLYING",
    power: 35,
    accuracy: 100,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DRILL_PECK: {
    id: "DRILL_PECK",
    numericId: 0x41,
    name: "Drill Peck",
    type: "FLYING",
    power: 80,
    accuracy: 100,
    pp: 20,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SUBMISSION: {
    id: "SUBMISSION",
    numericId: 0x42,
    name: "Submission",
    type: "FIGHTING",
    power: 80,
    accuracy: 80,
    pp: 25,
    effect: "RECOIL_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  LOW_KICK: {
    id: "LOW_KICK",
    numericId: 0x43,
    name: "Low Kick",
    type: "FIGHTING",
    power: 50,
    accuracy: 90,
    pp: 20,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  COUNTER: {
    id: "COUNTER",
    numericId: 0x44,
    name: "Counter",
    type: "FIGHTING",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "COUNTER",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SEISMIC_TOSS: {
    id: "SEISMIC_TOSS",
    numericId: 0x45,
    name: "Seismic Toss",
    type: "FIGHTING",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "LEVEL_DAMAGE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  STRENGTH: {
    id: "STRENGTH",
    numericId: 0x46,
    name: "Strength",
    type: "NORMAL",
    power: 80,
    accuracy: 100,
    pp: 15,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  ABSORB: {
    id: "ABSORB",
    numericId: 0x47,
    name: "Absorb",
    type: "GRASS",
    power: 20,
    accuracy: 100,
    pp: 20,
    effect: "LEECH_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MEGA_DRAIN: {
    id: "MEGA_DRAIN",
    numericId: 0x48,
    name: "Mega Drain",
    type: "GRASS",
    power: 40,
    accuracy: 100,
    pp: 10,
    effect: "LEECH_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  LEECH_SEED: {
    id: "LEECH_SEED",
    numericId: 0x49,
    name: "Leech Seed",
    type: "GRASS",
    power: 0,
    accuracy: 90,
    pp: 10,
    effect: "LEECH_SEED",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  GROWTH: {
    id: "GROWTH",
    numericId: 0x4A,
    name: "Growth",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "SP_ATK_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  RAZOR_LEAF: {
    id: "RAZOR_LEAF",
    numericId: 0x4B,
    name: "Razor Leaf",
    type: "GRASS",
    power: 55,
    accuracy: 95,
    pp: 25,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SOLARBEAM: {
    id: "SOLARBEAM",
    numericId: 0x4C,
    name: "Solarbeam",
    type: "GRASS",
    power: 120,
    accuracy: 100,
    pp: 10,
    effect: "SOLARBEAM",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  POISONPOWDER: {
    id: "POISONPOWDER",
    numericId: 0x4D,
    name: "Poisonpowder",
    type: "POISON",
    power: 0,
    accuracy: 75,
    pp: 35,
    effect: "POISON",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  STUN_SPORE: {
    id: "STUN_SPORE",
    numericId: 0x4E,
    name: "Stun Spore",
    type: "GRASS",
    power: 0,
    accuracy: 75,
    pp: 30,
    effect: "PARALYZE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SLEEP_POWDER: {
    id: "SLEEP_POWDER",
    numericId: 0x4F,
    name: "Sleep Powder",
    type: "GRASS",
    power: 0,
    accuracy: 75,
    pp: 15,
    effect: "SLEEP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  PETAL_DANCE: {
    id: "PETAL_DANCE",
    numericId: 0x50,
    name: "Petal Dance",
    type: "GRASS",
    power: 70,
    accuracy: 100,
    pp: 20,
    effect: "RAMPAGE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  STRING_SHOT: {
    id: "STRING_SHOT",
    numericId: 0x51,
    name: "String Shot",
    type: "BUG",
    power: 0,
    accuracy: 95,
    pp: 40,
    effect: "SPEED_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DRAGON_RAGE: {
    id: "DRAGON_RAGE",
    numericId: 0x52,
    name: "Dragon Rage",
    type: "DRAGON",
    power: 40,
    accuracy: 100,
    pp: 10,
    effect: "STATIC_DAMAGE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FIRE_SPIN: {
    id: "FIRE_SPIN",
    numericId: 0x53,
    name: "Fire Spin",
    type: "FIRE",
    power: 15,
    accuracy: 70,
    pp: 15,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  THUNDERSHOCK: {
    id: "THUNDERSHOCK",
    numericId: 0x54,
    name: "Thundershock",
    type: "ELECTRIC",
    power: 40,
    accuracy: 100,
    pp: 30,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  THUNDERBOLT: {
    id: "THUNDERBOLT",
    numericId: 0x55,
    name: "Thunderbolt",
    type: "ELECTRIC",
    power: 95,
    accuracy: 100,
    pp: 15,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  THUNDER_WAVE: {
    id: "THUNDER_WAVE",
    numericId: 0x56,
    name: "Thunder Wave",
    type: "ELECTRIC",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "PARALYZE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  THUNDER: {
    id: "THUNDER",
    numericId: 0x57,
    name: "Thunder",
    type: "ELECTRIC",
    power: 120,
    accuracy: 70,
    pp: 10,
    effect: "THUNDER",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  ROCK_THROW: {
    id: "ROCK_THROW",
    numericId: 0x58,
    name: "Rock Throw",
    type: "ROCK",
    power: 50,
    accuracy: 90,
    pp: 15,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  EARTHQUAKE: {
    id: "EARTHQUAKE",
    numericId: 0x59,
    name: "Earthquake",
    type: "GROUND",
    power: 100,
    accuracy: 100,
    pp: 10,
    effect: "EARTHQUAKE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FISSURE: {
    id: "FISSURE",
    numericId: 0x5A,
    name: "Fissure",
    type: "GROUND",
    power: 1,
    accuracy: 30,
    pp: 5,
    effect: "OHKO",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DIG: {
    id: "DIG",
    numericId: 0x5B,
    name: "Dig",
    type: "GROUND",
    power: 60,
    accuracy: 100,
    pp: 10,
    effect: "FLY",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  TOXIC: {
    id: "TOXIC",
    numericId: 0x5C,
    name: "Toxic",
    type: "POISON",
    power: 0,
    accuracy: 85,
    pp: 10,
    effect: "TOXIC",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CONFUSION: {
    id: "CONFUSION",
    numericId: 0x5D,
    name: "Confusion",
    type: "PSYCHIC",
    power: 50,
    accuracy: 100,
    pp: 25,
    effect: "CONFUSE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  PSYCHIC: {
    id: "PSYCHIC",
    numericId: 0x5E,
    name: "Psychic",
    type: "PSYCHIC",
    power: 90,
    accuracy: 100,
    pp: 10,
    effect: "SP_DEF_DOWN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  HYPNOSIS: {
    id: "HYPNOSIS",
    numericId: 0x5F,
    name: "Hypnosis",
    type: "PSYCHIC",
    power: 0,
    accuracy: 60,
    pp: 20,
    effect: "SLEEP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MEDITATE: {
    id: "MEDITATE",
    numericId: 0x60,
    name: "Meditate",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "ATTACK_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  AGILITY: {
    id: "AGILITY",
    numericId: 0x61,
    name: "Agility",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "SPEED_UP_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  QUICK_ATTACK: {
    id: "QUICK_ATTACK",
    numericId: 0x62,
    name: "Quick Attack",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 30,
    effect: "PRIORITY_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  RAGE: {
    id: "RAGE",
    numericId: 0x63,
    name: "Rage",
    type: "NORMAL",
    power: 20,
    accuracy: 100,
    pp: 20,
    effect: "RAGE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  TELEPORT: {
    id: "TELEPORT",
    numericId: 0x64,
    name: "Teleport",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "TELEPORT",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  NIGHT_SHADE: {
    id: "NIGHT_SHADE",
    numericId: 0x65,
    name: "Night Shade",
    type: "GHOST",
    power: 1,
    accuracy: 100,
    pp: 15,
    effect: "LEVEL_DAMAGE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MIMIC: {
    id: "MIMIC",
    numericId: 0x66,
    name: "Mimic",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "MIMIC",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SCREECH: {
    id: "SCREECH",
    numericId: 0x67,
    name: "Screech",
    type: "NORMAL",
    power: 0,
    accuracy: 85,
    pp: 40,
    effect: "DEFENSE_DOWN_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DOUBLE_TEAM: {
    id: "DOUBLE_TEAM",
    numericId: 0x68,
    name: "Double Team",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "EVASION_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  RECOVER: {
    id: "RECOVER",
    numericId: 0x69,
    name: "Recover",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "HEAL",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  HARDEN: {
    id: "HARDEN",
    numericId: 0x6A,
    name: "Harden",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MINIMIZE: {
    id: "MINIMIZE",
    numericId: 0x6B,
    name: "Minimize",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "EVASION_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SMOKESCREEN: {
    id: "SMOKESCREEN",
    numericId: 0x6C,
    name: "Smokescreen",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "ACCURACY_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CONFUSE_RAY: {
    id: "CONFUSE_RAY",
    numericId: 0x6D,
    name: "Confuse Ray",
    type: "GHOST",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "CONFUSE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  WITHDRAW: {
    id: "WITHDRAW",
    numericId: 0x6E,
    name: "Withdraw",
    type: "WATER",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "DEFENSE_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DEFENSE_CURL: {
    id: "DEFENSE_CURL",
    numericId: 0x6F,
    name: "Defense Curl",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "DEFENSE_CURL",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BARRIER: {
    id: "BARRIER",
    numericId: 0x70,
    name: "Barrier",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_UP_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  LIGHT_SCREEN: {
    id: "LIGHT_SCREEN",
    numericId: 0x71,
    name: "Light Screen",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "LIGHT_SCREEN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  HAZE: {
    id: "HAZE",
    numericId: 0x72,
    name: "Haze",
    type: "ICE",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "RESET_STATS",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  REFLECT: {
    id: "REFLECT",
    numericId: 0x73,
    name: "Reflect",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "REFLECT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FOCUS_ENERGY: {
    id: "FOCUS_ENERGY",
    numericId: 0x74,
    name: "Focus Energy",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "FOCUS_ENERGY",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BIDE: {
    id: "BIDE",
    numericId: 0x75,
    name: "Bide",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "BIDE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  METRONOME: {
    id: "METRONOME",
    numericId: 0x76,
    name: "Metronome",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "METRONOME",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MIRROR_MOVE: {
    id: "MIRROR_MOVE",
    numericId: 0x77,
    name: "Mirror Move",
    type: "FLYING",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "MIRROR_MOVE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SELFDESTRUCT: {
    id: "SELFDESTRUCT",
    numericId: 0x78,
    name: "Selfdestruct",
    type: "NORMAL",
    power: 200,
    accuracy: 100,
    pp: 5,
    effect: "SELFDESTRUCT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  EGG_BOMB: {
    id: "EGG_BOMB",
    numericId: 0x79,
    name: "Egg Bomb",
    type: "NORMAL",
    power: 100,
    accuracy: 75,
    pp: 10,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  LICK: {
    id: "LICK",
    numericId: 0x7A,
    name: "Lick",
    type: "GHOST",
    power: 20,
    accuracy: 100,
    pp: 30,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  SMOG: {
    id: "SMOG",
    numericId: 0x7B,
    name: "Smog",
    type: "POISON",
    power: 20,
    accuracy: 70,
    pp: 20,
    effect: "POISON_HIT",
    secondaryEffectChance: 40,
    isFieldMove: false,
  },
  SLUDGE: {
    id: "SLUDGE",
    numericId: 0x7C,
    name: "Sludge",
    type: "POISON",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "POISON_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  BONE_CLUB: {
    id: "BONE_CLUB",
    numericId: 0x7D,
    name: "Bone Club",
    type: "GROUND",
    power: 65,
    accuracy: 85,
    pp: 20,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  FIRE_BLAST: {
    id: "FIRE_BLAST",
    numericId: 0x7E,
    name: "Fire Blast",
    type: "FIRE",
    power: 120,
    accuracy: 85,
    pp: 5,
    effect: "BURN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  WATERFALL: {
    id: "WATERFALL",
    numericId: 0x7F,
    name: "Waterfall",
    type: "WATER",
    power: 80,
    accuracy: 100,
    pp: 15,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  CLAMP: {
    id: "CLAMP",
    numericId: 0x80,
    name: "Clamp",
    type: "WATER",
    power: 35,
    accuracy: 75,
    pp: 10,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SWIFT: {
    id: "SWIFT",
    numericId: 0x81,
    name: "Swift",
    type: "NORMAL",
    power: 60,
    accuracy: 100,
    pp: 20,
    effect: "ALWAYS_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SKULL_BASH: {
    id: "SKULL_BASH",
    numericId: 0x82,
    name: "Skull Bash",
    type: "NORMAL",
    power: 100,
    accuracy: 100,
    pp: 15,
    effect: "SKULL_BASH",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SPIKE_CANNON: {
    id: "SPIKE_CANNON",
    numericId: 0x83,
    name: "Spike Cannon",
    type: "NORMAL",
    power: 20,
    accuracy: 100,
    pp: 15,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CONSTRICT: {
    id: "CONSTRICT",
    numericId: 0x84,
    name: "Constrict",
    type: "NORMAL",
    power: 10,
    accuracy: 100,
    pp: 35,
    effect: "SPEED_DOWN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  AMNESIA: {
    id: "AMNESIA",
    numericId: 0x85,
    name: "Amnesia",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "SP_DEF_UP_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  KINESIS: {
    id: "KINESIS",
    numericId: 0x86,
    name: "Kinesis",
    type: "PSYCHIC",
    power: 0,
    accuracy: 80,
    pp: 15,
    effect: "ACCURACY_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SOFTBOILED: {
    id: "SOFTBOILED",
    numericId: 0x87,
    name: "Softboiled",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "HEAL",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  HI_JUMP_KICK: {
    id: "HI_JUMP_KICK",
    numericId: 0x88,
    name: "Hi Jump Kick",
    type: "FIGHTING",
    power: 85,
    accuracy: 90,
    pp: 20,
    effect: "JUMP_KICK",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  GLARE: {
    id: "GLARE",
    numericId: 0x89,
    name: "Glare",
    type: "NORMAL",
    power: 0,
    accuracy: 75,
    pp: 30,
    effect: "PARALYZE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DREAM_EATER: {
    id: "DREAM_EATER",
    numericId: 0x8A,
    name: "Dream Eater",
    type: "PSYCHIC",
    power: 100,
    accuracy: 100,
    pp: 15,
    effect: "DREAM_EATER",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  POISON_GAS: {
    id: "POISON_GAS",
    numericId: 0x8B,
    name: "Poison Gas",
    type: "POISON",
    power: 0,
    accuracy: 55,
    pp: 40,
    effect: "POISON",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BARRAGE: {
    id: "BARRAGE",
    numericId: 0x8C,
    name: "Barrage",
    type: "NORMAL",
    power: 15,
    accuracy: 85,
    pp: 20,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  LEECH_LIFE: {
    id: "LEECH_LIFE",
    numericId: 0x8D,
    name: "Leech Life",
    type: "BUG",
    power: 20,
    accuracy: 100,
    pp: 15,
    effect: "LEECH_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  LOVELY_KISS: {
    id: "LOVELY_KISS",
    numericId: 0x8E,
    name: "Lovely Kiss",
    type: "NORMAL",
    power: 0,
    accuracy: 75,
    pp: 10,
    effect: "SLEEP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SKY_ATTACK: {
    id: "SKY_ATTACK",
    numericId: 0x8F,
    name: "Sky Attack",
    type: "FLYING",
    power: 140,
    accuracy: 90,
    pp: 5,
    effect: "SKY_ATTACK",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  TRANSFORM: {
    id: "TRANSFORM",
    numericId: 0x90,
    name: "Transform",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "TRANSFORM",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BUBBLE: {
    id: "BUBBLE",
    numericId: 0x91,
    name: "Bubble",
    type: "WATER",
    power: 20,
    accuracy: 100,
    pp: 30,
    effect: "SPEED_DOWN_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  DIZZY_PUNCH: {
    id: "DIZZY_PUNCH",
    numericId: 0x92,
    name: "Dizzy Punch",
    type: "NORMAL",
    power: 70,
    accuracy: 100,
    pp: 10,
    effect: "CONFUSE_HIT",
    secondaryEffectChance: 20,
    isFieldMove: false,
  },
  SPORE: {
    id: "SPORE",
    numericId: 0x93,
    name: "Spore",
    type: "GRASS",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "SLEEP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FLASH: {
    id: "FLASH",
    numericId: 0x94,
    name: "Flash",
    type: "NORMAL",
    power: 0,
    accuracy: 70,
    pp: 20,
    effect: "ACCURACY_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  PSYWAVE: {
    id: "PSYWAVE",
    numericId: 0x95,
    name: "Psywave",
    type: "PSYCHIC",
    power: 1,
    accuracy: 80,
    pp: 15,
    effect: "PSYWAVE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SPLASH: {
    id: "SPLASH",
    numericId: 0x96,
    name: "Splash",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "SPLASH",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ACID_ARMOR: {
    id: "ACID_ARMOR",
    numericId: 0x97,
    name: "Acid Armor",
    type: "POISON",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "DEFENSE_UP_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CRABHAMMER: {
    id: "CRABHAMMER",
    numericId: 0x98,
    name: "Crabhammer",
    type: "WATER",
    power: 90,
    accuracy: 85,
    pp: 10,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  EXPLOSION: {
    id: "EXPLOSION",
    numericId: 0x99,
    name: "Explosion",
    type: "NORMAL",
    power: 250,
    accuracy: 100,
    pp: 5,
    effect: "SELFDESTRUCT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FURY_SWIPES: {
    id: "FURY_SWIPES",
    numericId: 0x9A,
    name: "Fury Swipes",
    type: "NORMAL",
    power: 18,
    accuracy: 80,
    pp: 15,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BONEMERANG: {
    id: "BONEMERANG",
    numericId: 0x9B,
    name: "Bonemerang",
    type: "GROUND",
    power: 50,
    accuracy: 90,
    pp: 10,
    effect: "DOUBLE_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  REST: {
    id: "REST",
    numericId: 0x9C,
    name: "Rest",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "HEAL",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ROCK_SLIDE: {
    id: "ROCK_SLIDE",
    numericId: 0x9D,
    name: "Rock Slide",
    type: "ROCK",
    power: 75,
    accuracy: 90,
    pp: 10,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  HYPER_FANG: {
    id: "HYPER_FANG",
    numericId: 0x9E,
    name: "Hyper Fang",
    type: "NORMAL",
    power: 80,
    accuracy: 90,
    pp: 15,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  SHARPEN: {
    id: "SHARPEN",
    numericId: 0x9F,
    name: "Sharpen",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "ATTACK_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CONVERSION: {
    id: "CONVERSION",
    numericId: 0xA0,
    name: "Conversion",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "CONVERSION",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  TRI_ATTACK: {
    id: "TRI_ATTACK",
    numericId: 0xA1,
    name: "Tri Attack",
    type: "NORMAL",
    power: 80,
    accuracy: 100,
    pp: 10,
    effect: "TRI_ATTACK",
    secondaryEffectChance: 20,
    isFieldMove: false,
  },
  SUPER_FANG: {
    id: "SUPER_FANG",
    numericId: 0xA2,
    name: "Super Fang",
    type: "NORMAL",
    power: 1,
    accuracy: 90,
    pp: 10,
    effect: "SUPER_FANG",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SLASH: {
    id: "SLASH",
    numericId: 0xA3,
    name: "Slash",
    type: "NORMAL",
    power: 70,
    accuracy: 100,
    pp: 20,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SUBSTITUTE: {
    id: "SUBSTITUTE",
    numericId: 0xA4,
    name: "Substitute",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "SUBSTITUTE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  STRUGGLE: {
    id: "STRUGGLE",
    numericId: 0xA5,
    name: "Struggle",
    type: "NORMAL",
    power: 50,
    accuracy: 100,
    pp: 1,
    effect: "RECOIL_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SKETCH: {
    id: "SKETCH",
    numericId: 0xA6,
    name: "Sketch",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 1,
    effect: "SKETCH",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  TRIPLE_KICK: {
    id: "TRIPLE_KICK",
    numericId: 0xA7,
    name: "Triple Kick",
    type: "FIGHTING",
    power: 10,
    accuracy: 90,
    pp: 10,
    effect: "TRIPLE_KICK",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  THIEF: {
    id: "THIEF",
    numericId: 0xA8,
    name: "Thief",
    type: "DARK",
    power: 40,
    accuracy: 100,
    pp: 10,
    effect: "THIEF",
    secondaryEffectChance: 100,
    isFieldMove: false,
  },
  SPIDER_WEB: {
    id: "SPIDER_WEB",
    numericId: 0xA9,
    name: "Spider Web",
    type: "BUG",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "MEAN_LOOK",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MIND_READER: {
    id: "MIND_READER",
    numericId: 0xAA,
    name: "Mind Reader",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "LOCK_ON",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  NIGHTMARE: {
    id: "NIGHTMARE",
    numericId: 0xAB,
    name: "Nightmare",
    type: "GHOST",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "NIGHTMARE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FLAME_WHEEL: {
    id: "FLAME_WHEEL",
    numericId: 0xAC,
    name: "Flame Wheel",
    type: "FIRE",
    power: 60,
    accuracy: 100,
    pp: 25,
    effect: "FLAME_WHEEL",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  SNORE: {
    id: "SNORE",
    numericId: 0xAD,
    name: "Snore",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 15,
    effect: "SNORE",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  CURSE: {
    id: "CURSE",
    numericId: 0xAE,
    name: "Curse",
    type: "NONE",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "CURSE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FLAIL: {
    id: "FLAIL",
    numericId: 0xAF,
    name: "Flail",
    type: "NORMAL",
    power: 1,
    accuracy: 100,
    pp: 15,
    effect: "REVERSAL",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CONVERSION2: {
    id: "CONVERSION2",
    numericId: 0xB0,
    name: "Conversion2",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "CONVERSION2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  AEROBLAST: {
    id: "AEROBLAST",
    numericId: 0xB1,
    name: "Aeroblast",
    type: "FLYING",
    power: 100,
    accuracy: 95,
    pp: 5,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  COTTON_SPORE: {
    id: "COTTON_SPORE",
    numericId: 0xB2,
    name: "Cotton Spore",
    type: "GRASS",
    power: 0,
    accuracy: 85,
    pp: 40,
    effect: "SPEED_DOWN_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  REVERSAL: {
    id: "REVERSAL",
    numericId: 0xB3,
    name: "Reversal",
    type: "FIGHTING",
    power: 1,
    accuracy: 100,
    pp: 15,
    effect: "REVERSAL",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SPITE: {
    id: "SPITE",
    numericId: 0xB4,
    name: "Spite",
    type: "GHOST",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "SPITE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  POWDER_SNOW: {
    id: "POWDER_SNOW",
    numericId: 0xB5,
    name: "Powder Snow",
    type: "ICE",
    power: 40,
    accuracy: 100,
    pp: 25,
    effect: "FREEZE_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  PROTECT: {
    id: "PROTECT",
    numericId: 0xB6,
    name: "Protect",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "PROTECT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MACH_PUNCH: {
    id: "MACH_PUNCH",
    numericId: 0xB7,
    name: "Mach Punch",
    type: "FIGHTING",
    power: 40,
    accuracy: 100,
    pp: 30,
    effect: "PRIORITY_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SCARY_FACE: {
    id: "SCARY_FACE",
    numericId: 0xB8,
    name: "Scary Face",
    type: "NORMAL",
    power: 0,
    accuracy: 90,
    pp: 10,
    effect: "SPEED_DOWN_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FAINT_ATTACK: {
    id: "FAINT_ATTACK",
    numericId: 0xB9,
    name: "Faint Attack",
    type: "DARK",
    power: 60,
    accuracy: 100,
    pp: 20,
    effect: "ALWAYS_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SWEET_KISS: {
    id: "SWEET_KISS",
    numericId: 0xBA,
    name: "Sweet Kiss",
    type: "NORMAL",
    power: 0,
    accuracy: 75,
    pp: 10,
    effect: "CONFUSE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BELLY_DRUM: {
    id: "BELLY_DRUM",
    numericId: 0xBB,
    name: "Belly Drum",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "BELLY_DRUM",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SLUDGE_BOMB: {
    id: "SLUDGE_BOMB",
    numericId: 0xBC,
    name: "Sludge Bomb",
    type: "POISON",
    power: 90,
    accuracy: 100,
    pp: 10,
    effect: "POISON_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  MUD_SLAP: {
    id: "MUD_SLAP",
    numericId: 0xBD,
    name: "Mud Slap",
    type: "GROUND",
    power: 20,
    accuracy: 100,
    pp: 10,
    effect: "ACCURACY_DOWN_HIT",
    secondaryEffectChance: 100,
    isFieldMove: false,
  },
  OCTAZOOKA: {
    id: "OCTAZOOKA",
    numericId: 0xBE,
    name: "Octazooka",
    type: "WATER",
    power: 65,
    accuracy: 85,
    pp: 10,
    effect: "ACCURACY_DOWN_HIT",
    secondaryEffectChance: 50,
    isFieldMove: false,
  },
  SPIKES: {
    id: "SPIKES",
    numericId: 0xBF,
    name: "Spikes",
    type: "GROUND",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "SPIKES",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ZAP_CANNON: {
    id: "ZAP_CANNON",
    numericId: 0xC0,
    name: "Zap Cannon",
    type: "ELECTRIC",
    power: 100,
    accuracy: 50,
    pp: 5,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 100,
    isFieldMove: false,
  },
  FORESIGHT: {
    id: "FORESIGHT",
    numericId: 0xC1,
    name: "Foresight",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "FORESIGHT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DESTINY_BOND: {
    id: "DESTINY_BOND",
    numericId: 0xC2,
    name: "Destiny Bond",
    type: "GHOST",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "DESTINY_BOND",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  PERISH_SONG: {
    id: "PERISH_SONG",
    numericId: 0xC3,
    name: "Perish Song",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "PERISH_SONG",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ICY_WIND: {
    id: "ICY_WIND",
    numericId: 0xC4,
    name: "Icy Wind",
    type: "ICE",
    power: 55,
    accuracy: 95,
    pp: 15,
    effect: "SPEED_DOWN_HIT",
    secondaryEffectChance: 100,
    isFieldMove: false,
  },
  DETECT: {
    id: "DETECT",
    numericId: 0xC5,
    name: "Detect",
    type: "FIGHTING",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "PROTECT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  BONE_RUSH: {
    id: "BONE_RUSH",
    numericId: 0xC6,
    name: "Bone Rush",
    type: "GROUND",
    power: 25,
    accuracy: 80,
    pp: 10,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  LOCK_ON: {
    id: "LOCK_ON",
    numericId: 0xC7,
    name: "Lock On",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "LOCK_ON",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  OUTRAGE: {
    id: "OUTRAGE",
    numericId: 0xC8,
    name: "Outrage",
    type: "DRAGON",
    power: 90,
    accuracy: 100,
    pp: 15,
    effect: "RAMPAGE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SANDSTORM: {
    id: "SANDSTORM",
    numericId: 0xC9,
    name: "Sandstorm",
    type: "ROCK",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "SANDSTORM",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  GIGA_DRAIN: {
    id: "GIGA_DRAIN",
    numericId: 0xCA,
    name: "Giga Drain",
    type: "GRASS",
    power: 60,
    accuracy: 100,
    pp: 5,
    effect: "LEECH_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ENDURE: {
    id: "ENDURE",
    numericId: 0xCB,
    name: "Endure",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "ENDURE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CHARM: {
    id: "CHARM",
    numericId: 0xCC,
    name: "Charm",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "ATTACK_DOWN_2",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ROLLOUT: {
    id: "ROLLOUT",
    numericId: 0xCD,
    name: "Rollout",
    type: "ROCK",
    power: 30,
    accuracy: 90,
    pp: 20,
    effect: "ROLLOUT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FALSE_SWIPE: {
    id: "FALSE_SWIPE",
    numericId: 0xCE,
    name: "False Swipe",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 40,
    effect: "FALSE_SWIPE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SWAGGER: {
    id: "SWAGGER",
    numericId: 0xCF,
    name: "Swagger",
    type: "NORMAL",
    power: 0,
    accuracy: 90,
    pp: 15,
    effect: "SWAGGER",
    secondaryEffectChance: 100,
    isFieldMove: false,
  },
  MILK_DRINK: {
    id: "MILK_DRINK",
    numericId: 0xD0,
    name: "Milk Drink",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "HEAL",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  SPARK: {
    id: "SPARK",
    numericId: 0xD1,
    name: "Spark",
    type: "ELECTRIC",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  FURY_CUTTER: {
    id: "FURY_CUTTER",
    numericId: 0xD2,
    name: "Fury Cutter",
    type: "BUG",
    power: 10,
    accuracy: 95,
    pp: 20,
    effect: "FURY_CUTTER",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  STEEL_WING: {
    id: "STEEL_WING",
    numericId: 0xD3,
    name: "Steel Wing",
    type: "STEEL",
    power: 70,
    accuracy: 90,
    pp: 25,
    effect: "DEFENSE_UP_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  MEAN_LOOK: {
    id: "MEAN_LOOK",
    numericId: 0xD4,
    name: "Mean Look",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "MEAN_LOOK",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ATTRACT: {
    id: "ATTRACT",
    numericId: 0xD5,
    name: "Attract",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "ATTRACT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SLEEP_TALK: {
    id: "SLEEP_TALK",
    numericId: 0xD6,
    name: "Sleep Talk",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "SLEEP_TALK",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  HEAL_BELL: {
    id: "HEAL_BELL",
    numericId: 0xD7,
    name: "Heal Bell",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "HEAL_BELL",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  RETURN: {
    id: "RETURN",
    numericId: 0xD8,
    name: "Return",
    type: "NORMAL",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "RETURN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  PRESENT: {
    id: "PRESENT",
    numericId: 0xD9,
    name: "Present",
    type: "NORMAL",
    power: 1,
    accuracy: 90,
    pp: 15,
    effect: "PRESENT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  FRUSTRATION: {
    id: "FRUSTRATION",
    numericId: 0xDA,
    name: "Frustration",
    type: "NORMAL",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "FRUSTRATION",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SAFEGUARD: {
    id: "SAFEGUARD",
    numericId: 0xDB,
    name: "Safeguard",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 25,
    effect: "SAFEGUARD",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  PAIN_SPLIT: {
    id: "PAIN_SPLIT",
    numericId: 0xDC,
    name: "Pain Split",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "PAIN_SPLIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SACRED_FIRE: {
    id: "SACRED_FIRE",
    numericId: 0xDD,
    name: "Sacred Fire",
    type: "FIRE",
    power: 100,
    accuracy: 95,
    pp: 5,
    effect: "SACRED_FIRE",
    secondaryEffectChance: 50,
    isFieldMove: false,
  },
  MAGNITUDE: {
    id: "MAGNITUDE",
    numericId: 0xDE,
    name: "Magnitude",
    type: "GROUND",
    power: 1,
    accuracy: 100,
    pp: 30,
    effect: "MAGNITUDE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DYNAMICPUNCH: {
    id: "DYNAMICPUNCH",
    numericId: 0xDF,
    name: "Dynamicpunch",
    type: "FIGHTING",
    power: 100,
    accuracy: 50,
    pp: 5,
    effect: "CONFUSE_HIT",
    secondaryEffectChance: 100,
    isFieldMove: false,
  },
  MEGAHORN: {
    id: "MEGAHORN",
    numericId: 0xE0,
    name: "Megahorn",
    type: "BUG",
    power: 120,
    accuracy: 85,
    pp: 10,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  DRAGONBREATH: {
    id: "DRAGONBREATH",
    numericId: 0xE1,
    name: "Dragonbreath",
    type: "DRAGON",
    power: 60,
    accuracy: 100,
    pp: 20,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  BATON_PASS: {
    id: "BATON_PASS",
    numericId: 0xE2,
    name: "Baton Pass",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "BATON_PASS",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ENCORE: {
    id: "ENCORE",
    numericId: 0xE3,
    name: "Encore",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "ENCORE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  PURSUIT: {
    id: "PURSUIT",
    numericId: 0xE4,
    name: "Pursuit",
    type: "DARK",
    power: 40,
    accuracy: 100,
    pp: 20,
    effect: "PURSUIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  RAPID_SPIN: {
    id: "RAPID_SPIN",
    numericId: 0xE5,
    name: "Rapid Spin",
    type: "NORMAL",
    power: 20,
    accuracy: 100,
    pp: 40,
    effect: "RAPID_SPIN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SWEET_SCENT: {
    id: "SWEET_SCENT",
    numericId: 0xE6,
    name: "Sweet Scent",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "EVASION_DOWN",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  IRON_TAIL: {
    id: "IRON_TAIL",
    numericId: 0xE7,
    name: "Iron Tail",
    type: "STEEL",
    power: 100,
    accuracy: 75,
    pp: 15,
    effect: "DEFENSE_DOWN_HIT",
    secondaryEffectChance: 30,
    isFieldMove: false,
  },
  METAL_CLAW: {
    id: "METAL_CLAW",
    numericId: 0xE8,
    name: "Metal Claw",
    type: "STEEL",
    power: 50,
    accuracy: 95,
    pp: 35,
    effect: "ATTACK_UP_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  VITAL_THROW: {
    id: "VITAL_THROW",
    numericId: 0xE9,
    name: "Vital Throw",
    type: "FIGHTING",
    power: 70,
    accuracy: 100,
    pp: 10,
    effect: "ALWAYS_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MORNING_SUN: {
    id: "MORNING_SUN",
    numericId: 0xEA,
    name: "Morning Sun",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "MORNING_SUN",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SYNTHESIS: {
    id: "SYNTHESIS",
    numericId: 0xEB,
    name: "Synthesis",
    type: "GRASS",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "SYNTHESIS",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  MOONLIGHT: {
    id: "MOONLIGHT",
    numericId: 0xEC,
    name: "Moonlight",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "MOONLIGHT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  HIDDEN_POWER: {
    id: "HIDDEN_POWER",
    numericId: 0xED,
    name: "Hidden Power",
    type: "NORMAL",
    power: 1,
    accuracy: 100,
    pp: 15,
    effect: "HIDDEN_POWER",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CROSS_CHOP: {
    id: "CROSS_CHOP",
    numericId: 0xEE,
    name: "Cross Chop",
    type: "FIGHTING",
    power: 100,
    accuracy: 80,
    pp: 5,
    effect: "HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  TWISTER: {
    id: "TWISTER",
    numericId: 0xEF,
    name: "Twister",
    type: "DRAGON",
    power: 40,
    accuracy: 100,
    pp: 20,
    effect: "TWISTER",
    secondaryEffectChance: 20,
    isFieldMove: false,
  },
  RAIN_DANCE: {
    id: "RAIN_DANCE",
    numericId: 0xF0,
    name: "Rain Dance",
    type: "WATER",
    power: 0,
    accuracy: 90,
    pp: 5,
    effect: "RAIN_DANCE",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  SUNNY_DAY: {
    id: "SUNNY_DAY",
    numericId: 0xF1,
    name: "Sunny Day",
    type: "FIRE",
    power: 0,
    accuracy: 90,
    pp: 5,
    effect: "SUNNY_DAY",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  CRUNCH: {
    id: "CRUNCH",
    numericId: 0xF2,
    name: "Crunch",
    type: "DARK",
    power: 80,
    accuracy: 100,
    pp: 15,
    effect: "SP_DEF_DOWN_HIT",
    secondaryEffectChance: 20,
    isFieldMove: false,
  },
  MIRROR_COAT: {
    id: "MIRROR_COAT",
    numericId: 0xF3,
    name: "Mirror Coat",
    type: "PSYCHIC",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "MIRROR_COAT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  PSYCH_UP: {
    id: "PSYCH_UP",
    numericId: 0xF4,
    name: "Psych Up",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "PSYCH_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  EXTREMESPEED: {
    id: "EXTREMESPEED",
    numericId: 0xF5,
    name: "Extremespeed",
    type: "NORMAL",
    power: 80,
    accuracy: 100,
    pp: 5,
    effect: "PRIORITY_HIT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ANCIENTPOWER: {
    id: "ANCIENTPOWER",
    numericId: 0xF6,
    name: "Ancientpower",
    type: "ROCK",
    power: 60,
    accuracy: 100,
    pp: 5,
    effect: "ALL_UP_HIT",
    secondaryEffectChance: 10,
    isFieldMove: false,
  },
  SHADOW_BALL: {
    id: "SHADOW_BALL",
    numericId: 0xF7,
    name: "Shadow Ball",
    type: "GHOST",
    power: 80,
    accuracy: 100,
    pp: 15,
    effect: "SP_DEF_DOWN_HIT",
    secondaryEffectChance: 20,
    isFieldMove: false,
  },
  FUTURE_SIGHT: {
    id: "FUTURE_SIGHT",
    numericId: 0xF8,
    name: "Future Sight",
    type: "PSYCHIC",
    power: 80,
    accuracy: 90,
    pp: 15,
    effect: "FUTURE_SIGHT",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
  ROCK_SMASH: {
    id: "ROCK_SMASH",
    numericId: 0xF9,
    name: "Rock Smash",
    type: "FIGHTING",
    power: 20,
    accuracy: 100,
    pp: 15,
    effect: "DEFENSE_DOWN_HIT",
    secondaryEffectChance: 50,
    isFieldMove: true,
  },
  WHIRLPOOL: {
    id: "WHIRLPOOL",
    numericId: 0xFA,
    name: "Whirlpool",
    type: "WATER",
    power: 15,
    accuracy: 70,
    pp: 15,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
    isFieldMove: true,
  },
  BEAT_UP: {
    id: "BEAT_UP",
    numericId: 0xFB,
    name: "Beat Up",
    type: "DARK",
    power: 10,
    accuracy: 100,
    pp: 10,
    effect: "BEAT_UP",
    secondaryEffectChance: 0,
    isFieldMove: false,
  },
}