export type Move = {
  id: MoveId,
  hexId: string,
  name: string,
  type: PokemonTypeId,
  power: number,
  accuracy: number,
  pp: number,
  effect: MoveEffectId,
  secondaryEffectChance: number,
}

export const movesList: Move[] = [
  {
    id: "POUND",
    hexId: "01",
    name: "Pound",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "KARATE_CHOP",
    hexId: "02",
    name: "Karate_chop",
    type: "FIGHTING",
    power: 50,
    accuracy: 100,
    pp: 25,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "DOUBLESLAP",
    hexId: "03",
    name: "Doubleslap",
    type: "NORMAL",
    power: 15,
    accuracy: 85,
    pp: 10,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "COMET_PUNCH",
    hexId: "04",
    name: "Comet_punch",
    type: "NORMAL",
    power: 18,
    accuracy: 85,
    pp: 15,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "MEGA_PUNCH",
    hexId: "05",
    name: "Mega_punch",
    type: "NORMAL",
    power: 80,
    accuracy: 85,
    pp: 20,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "PAY_DAY",
    hexId: "06",
    name: "Pay_day",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 20,
    effect: "PAY_DAY",
    secondaryEffectChance: 0,
  },
  {
    id: "FIRE_PUNCH",
    hexId: "07",
    name: "Fire_punch",
    type: "FIRE",
    power: 75,
    accuracy: 100,
    pp: 15,
    effect: "BURN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "ICE_PUNCH",
    hexId: "08",
    name: "Ice_punch",
    type: "ICE",
    power: 75,
    accuracy: 100,
    pp: 15,
    effect: "FREEZE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "THUNDERPUNCH",
    hexId: "09",
    name: "Thunderpunch",
    type: "ELECTRIC",
    power: 75,
    accuracy: 100,
    pp: 15,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "SCRATCH",
    hexId: "0a",
    name: "Scratch",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "VICEGRIP",
    hexId: "0b",
    name: "Vicegrip",
    type: "NORMAL",
    power: 55,
    accuracy: 100,
    pp: 30,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "GUILLOTINE",
    hexId: "0c",
    name: "Guillotine",
    type: "NORMAL",
    power: 0,
    accuracy: 30,
    pp: 5,
    effect: "OHKO",
    secondaryEffectChance: 0,
  },
  {
    id: "RAZOR_WIND",
    hexId: "0d",
    name: "Razor_wind",
    type: "NORMAL",
    power: 80,
    accuracy: 75,
    pp: 10,
    effect: "RAZOR_WIND",
    secondaryEffectChance: 0,
  },
  {
    id: "SWORDS_DANCE",
    hexId: "0e",
    name: "Swords_dance",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "ATTACK_UP_2",
    secondaryEffectChance: 0,
  },
  {
    id: "CUT",
    hexId: "0f",
    name: "Cut",
    type: "NORMAL",
    power: 50,
    accuracy: 95,
    pp: 30,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "GUST",
    hexId: "10",
    name: "Gust",
    type: "FLYING",
    power: 40,
    accuracy: 100,
    pp: 35,
    effect: "GUST",
    secondaryEffectChance: 0,
  },
  {
    id: "WING_ATTACK",
    hexId: "11",
    name: "Wing_attack",
    type: "FLYING",
    power: 60,
    accuracy: 100,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "WHIRLWIND",
    hexId: "12",
    name: "Whirlwind",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "FORCE_SWITCH",
    secondaryEffectChance: 0,
  },
  {
    id: "FLY",
    hexId: "13",
    name: "Fly",
    type: "FLYING",
    power: 70,
    accuracy: 95,
    pp: 15,
    effect: "FLY",
    secondaryEffectChance: 0,
  },
  {
    id: "BIND",
    hexId: "14",
    name: "Bind",
    type: "NORMAL",
    power: 15,
    accuracy: 75,
    pp: 20,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
  },
  {
    id: "SLAM",
    hexId: "15",
    name: "Slam",
    type: "NORMAL",
    power: 80,
    accuracy: 75,
    pp: 20,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "VINE_WHIP",
    hexId: "16",
    name: "Vine_whip",
    type: "GRASS",
    power: 35,
    accuracy: 100,
    pp: 10,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "STOMP",
    hexId: "17",
    name: "Stomp",
    type: "NORMAL",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "STOMP",
    secondaryEffectChance: 30,
  },
  {
    id: "DOUBLE_KICK",
    hexId: "18",
    name: "Double_kick",
    type: "FIGHTING",
    power: 30,
    accuracy: 100,
    pp: 30,
    effect: "DOUBLE_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "MEGA_KICK",
    hexId: "19",
    name: "Mega_kick",
    type: "NORMAL",
    power: 120,
    accuracy: 75,
    pp: 5,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "JUMP_KICK",
    hexId: "1a",
    name: "Jump_kick",
    type: "FIGHTING",
    power: 70,
    accuracy: 95,
    pp: 25,
    effect: "JUMP_KICK",
    secondaryEffectChance: 0,
  },
  {
    id: "ROLLING_KICK",
    hexId: "1b",
    name: "Rolling_kick",
    type: "FIGHTING",
    power: 60,
    accuracy: 85,
    pp: 15,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "SAND_ATTACK",
    hexId: "1c",
    name: "Sand_attack",
    type: "GROUND",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "ACCURACY_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "HEADBUTT",
    hexId: "1d",
    name: "Headbutt",
    type: "NORMAL",
    power: 70,
    accuracy: 100,
    pp: 15,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "HORN_ATTACK",
    hexId: "1e",
    name: "Horn_attack",
    type: "NORMAL",
    power: 65,
    accuracy: 100,
    pp: 25,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "FURY_ATTACK",
    hexId: "1f",
    name: "Fury_attack",
    type: "NORMAL",
    power: 15,
    accuracy: 85,
    pp: 20,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "HORN_DRILL",
    hexId: "20",
    name: "Horn_drill",
    type: "NORMAL",
    power: 1,
    accuracy: 30,
    pp: 5,
    effect: "OHKO",
    secondaryEffectChance: 0,
  },
  {
    id: "TACKLE",
    hexId: "21",
    name: "Tackle",
    type: "NORMAL",
    power: 35,
    accuracy: 95,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "BODY_SLAM",
    hexId: "22",
    name: "Body_slam",
    type: "NORMAL",
    power: 85,
    accuracy: 100,
    pp: 15,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "WRAP",
    hexId: "23",
    name: "Wrap",
    type: "NORMAL",
    power: 15,
    accuracy: 85,
    pp: 20,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
  },
  {
    id: "TAKE_DOWN",
    hexId: "24",
    name: "Take_down",
    type: "NORMAL",
    power: 90,
    accuracy: 85,
    pp: 20,
    effect: "RECOIL_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "THRASH",
    hexId: "25",
    name: "Thrash",
    type: "NORMAL",
    power: 90,
    accuracy: 100,
    pp: 20,
    effect: "RAMPAGE",
    secondaryEffectChance: 0,
  },
  {
    id: "DOUBLE_EDGE",
    hexId: "26",
    name: "Double_edge",
    type: "NORMAL",
    power: 120,
    accuracy: 100,
    pp: 15,
    effect: "RECOIL_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "TAIL_WHIP",
    hexId: "27",
    name: "Tail_whip",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "POISON_STING",
    hexId: "28",
    name: "Poison_sting",
    type: "POISON",
    power: 15,
    accuracy: 100,
    pp: 35,
    effect: "POISON_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "TWINEEDLE",
    hexId: "29",
    name: "Twineedle",
    type: "BUG",
    power: 25,
    accuracy: 100,
    pp: 20,
    effect: "POISON_MULTI_HIT",
    secondaryEffectChance: 20,
  },
  {
    id: "PIN_MISSILE",
    hexId: "2a",
    name: "Pin_missile",
    type: "BUG",
    power: 14,
    accuracy: 85,
    pp: 20,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "LEER",
    hexId: "2b",
    name: "Leer",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "BITE",
    hexId: "2c",
    name: "Bite",
    type: "DARK",
    power: 60,
    accuracy: 100,
    pp: 25,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "GROWL",
    hexId: "2d",
    name: "Growl",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "ATTACK_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "ROAR",
    hexId: "2e",
    name: "Roar",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "FORCE_SWITCH",
    secondaryEffectChance: 0,
  },
  {
    id: "SING",
    hexId: "2f",
    name: "Sing",
    type: "NORMAL",
    power: 0,
    accuracy: 55,
    pp: 15,
    effect: "SLEEP",
    secondaryEffectChance: 0,
  },
  {
    id: "SUPERSONIC",
    hexId: "30",
    name: "Supersonic",
    type: "NORMAL",
    power: 0,
    accuracy: 55,
    pp: 20,
    effect: "CONFUSE",
    secondaryEffectChance: 0,
  },
  {
    id: "SONICBOOM",
    hexId: "31",
    name: "Sonicboom",
    type: "NORMAL",
    power: 20,
    accuracy: 90,
    pp: 20,
    effect: "STATIC_DAMAGE",
    secondaryEffectChance: 0,
  },
  {
    id: "DISABLE",
    hexId: "32",
    name: "Disable",
    type: "NORMAL",
    power: 0,
    accuracy: 55,
    pp: 20,
    effect: "DISABLE",
    secondaryEffectChance: 0,
  },
  {
    id: "ACID",
    hexId: "33",
    name: "Acid",
    type: "POISON",
    power: 40,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_DOWN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "EMBER",
    hexId: "34",
    name: "Ember",
    type: "FIRE",
    power: 40,
    accuracy: 100,
    pp: 25,
    effect: "BURN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "FLAMETHROWER",
    hexId: "35",
    name: "Flamethrower",
    type: "FIRE",
    power: 95,
    accuracy: 100,
    pp: 15,
    effect: "BURN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "MIST",
    hexId: "36",
    name: "Mist",
    type: "ICE",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "MIST",
    secondaryEffectChance: 0,
  },
  {
    id: "WATER_GUN",
    hexId: "37",
    name: "Water_gun",
    type: "WATER",
    power: 40,
    accuracy: 100,
    pp: 25,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "HYDRO_PUMP",
    hexId: "38",
    name: "Hydro_pump",
    type: "WATER",
    power: 120,
    accuracy: 80,
    pp: 5,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SURF",
    hexId: "39",
    name: "Surf",
    type: "WATER",
    power: 95,
    accuracy: 100,
    pp: 15,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "ICE_BEAM",
    hexId: "3a",
    name: "Ice_beam",
    type: "ICE",
    power: 95,
    accuracy: 100,
    pp: 10,
    effect: "FREEZE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "BLIZZARD",
    hexId: "3b",
    name: "Blizzard",
    type: "ICE",
    power: 120,
    accuracy: 70,
    pp: 5,
    effect: "FREEZE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "PSYBEAM",
    hexId: "3c",
    name: "Psybeam",
    type: "PSYCHIC",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "CONFUSE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "BUBBLEBEAM",
    hexId: "3d",
    name: "Bubblebeam",
    type: "WATER",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "SPEED_DOWN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "AURORA_BEAM",
    hexId: "3e",
    name: "Aurora_beam",
    type: "ICE",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "ATTACK_DOWN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "HYPER_BEAM",
    hexId: "3f",
    name: "Hyper_beam",
    type: "NORMAL",
    power: 150,
    accuracy: 90,
    pp: 5,
    effect: "HYPER_BEAM",
    secondaryEffectChance: 0,
  },
  {
    id: "PECK",
    hexId: "40",
    name: "Peck",
    type: "FLYING",
    power: 35,
    accuracy: 100,
    pp: 35,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "DRILL_PECK",
    hexId: "41",
    name: "Drill_peck",
    type: "FLYING",
    power: 80,
    accuracy: 100,
    pp: 20,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SUBMISSION",
    hexId: "42",
    name: "Submission",
    type: "FIGHTING",
    power: 80,
    accuracy: 80,
    pp: 25,
    effect: "RECOIL_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "LOW_KICK",
    hexId: "43",
    name: "Low_kick",
    type: "FIGHTING",
    power: 50,
    accuracy: 90,
    pp: 20,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "COUNTER",
    hexId: "44",
    name: "Counter",
    type: "FIGHTING",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "COUNTER",
    secondaryEffectChance: 0,
  },
  {
    id: "SEISMIC_TOSS",
    hexId: "45",
    name: "Seismic_toss",
    type: "FIGHTING",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "LEVEL_DAMAGE",
    secondaryEffectChance: 0,
  },
  {
    id: "STRENGTH",
    hexId: "46",
    name: "Strength",
    type: "NORMAL",
    power: 80,
    accuracy: 100,
    pp: 15,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "ABSORB",
    hexId: "47",
    name: "Absorb",
    type: "GRASS",
    power: 20,
    accuracy: 100,
    pp: 20,
    effect: "LEECH_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "MEGA_DRAIN",
    hexId: "48",
    name: "Mega_drain",
    type: "GRASS",
    power: 40,
    accuracy: 100,
    pp: 10,
    effect: "LEECH_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "LEECH_SEED",
    hexId: "49",
    name: "Leech_seed",
    type: "GRASS",
    power: 0,
    accuracy: 90,
    pp: 10,
    effect: "LEECH_SEED",
    secondaryEffectChance: 0,
  },
  {
    id: "GROWTH",
    hexId: "4a",
    name: "Growth",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "SP_ATK_UP",
    secondaryEffectChance: 0,
  },
  {
    id: "RAZOR_LEAF",
    hexId: "4b",
    name: "Razor_leaf",
    type: "GRASS",
    power: 55,
    accuracy: 95,
    pp: 25,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SOLARBEAM",
    hexId: "4c",
    name: "Solarbeam",
    type: "GRASS",
    power: 120,
    accuracy: 100,
    pp: 10,
    effect: "SOLARBEAM",
    secondaryEffectChance: 0,
  },
  {
    id: "POISONPOWDER",
    hexId: "4d",
    name: "Poisonpowder",
    type: "POISON",
    power: 0,
    accuracy: 75,
    pp: 35,
    effect: "POISON",
    secondaryEffectChance: 0,
  },
  {
    id: "STUN_SPORE",
    hexId: "4e",
    name: "Stun_spore",
    type: "GRASS",
    power: 0,
    accuracy: 75,
    pp: 30,
    effect: "PARALYZE",
    secondaryEffectChance: 0,
  },
  {
    id: "SLEEP_POWDER",
    hexId: "4f",
    name: "Sleep_powder",
    type: "GRASS",
    power: 0,
    accuracy: 75,
    pp: 15,
    effect: "SLEEP",
    secondaryEffectChance: 0,
  },
  {
    id: "PETAL_DANCE",
    hexId: "50",
    name: "Petal_dance",
    type: "GRASS",
    power: 70,
    accuracy: 100,
    pp: 20,
    effect: "RAMPAGE",
    secondaryEffectChance: 0,
  },
  {
    id: "STRING_SHOT",
    hexId: "51",
    name: "String_shot",
    type: "BUG",
    power: 0,
    accuracy: 95,
    pp: 40,
    effect: "SPEED_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "DRAGON_RAGE",
    hexId: "52",
    name: "Dragon_rage",
    type: "DRAGON",
    power: 40,
    accuracy: 100,
    pp: 10,
    effect: "STATIC_DAMAGE",
    secondaryEffectChance: 0,
  },
  {
    id: "FIRE_SPIN",
    hexId: "53",
    name: "Fire_spin",
    type: "FIRE",
    power: 15,
    accuracy: 70,
    pp: 15,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
  },
  {
    id: "THUNDERSHOCK",
    hexId: "54",
    name: "Thundershock",
    type: "ELECTRIC",
    power: 40,
    accuracy: 100,
    pp: 30,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "THUNDERBOLT",
    hexId: "55",
    name: "Thunderbolt",
    type: "ELECTRIC",
    power: 95,
    accuracy: 100,
    pp: 15,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "THUNDER_WAVE",
    hexId: "56",
    name: "Thunder_wave",
    type: "ELECTRIC",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "PARALYZE",
    secondaryEffectChance: 0,
  },
  {
    id: "THUNDER",
    hexId: "57",
    name: "Thunder",
    type: "ELECTRIC",
    power: 120,
    accuracy: 70,
    pp: 10,
    effect: "THUNDER",
    secondaryEffectChance: 30,
  },
  {
    id: "ROCK_THROW",
    hexId: "58",
    name: "Rock_throw",
    type: "ROCK",
    power: 50,
    accuracy: 90,
    pp: 15,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "EARTHQUAKE",
    hexId: "59",
    name: "Earthquake",
    type: "GROUND",
    power: 100,
    accuracy: 100,
    pp: 10,
    effect: "EARTHQUAKE",
    secondaryEffectChance: 0,
  },
  {
    id: "FISSURE",
    hexId: "5a",
    name: "Fissure",
    type: "GROUND",
    power: 1,
    accuracy: 30,
    pp: 5,
    effect: "OHKO",
    secondaryEffectChance: 0,
  },
  {
    id: "DIG",
    hexId: "5b",
    name: "Dig",
    type: "GROUND",
    power: 60,
    accuracy: 100,
    pp: 10,
    effect: "FLY",
    secondaryEffectChance: 0,
  },
  {
    id: "TOXIC",
    hexId: "5c",
    name: "Toxic",
    type: "POISON",
    power: 0,
    accuracy: 85,
    pp: 10,
    effect: "TOXIC",
    secondaryEffectChance: 0,
  },
  {
    id: "CONFUSION",
    hexId: "5d",
    name: "Confusion",
    type: "PSYCHIC",
    power: 50,
    accuracy: 100,
    pp: 25,
    effect: "CONFUSE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "PSYCHIC",
    hexId: "5e",
    name: "Psychic",
    type: "PSYCHIC",
    power: 90,
    accuracy: 100,
    pp: 10,
    effect: "SP_DEF_DOWN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "HYPNOSIS",
    hexId: "5f",
    name: "Hypnosis",
    type: "PSYCHIC",
    power: 0,
    accuracy: 60,
    pp: 20,
    effect: "SLEEP",
    secondaryEffectChance: 0,
  },
  {
    id: "MEDITATE",
    hexId: "60",
    name: "Meditate",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "ATTACK_UP",
    secondaryEffectChance: 0,
  },
  {
    id: "AGILITY",
    hexId: "61",
    name: "Agility",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "SPEED_UP_2",
    secondaryEffectChance: 0,
  },
  {
    id: "QUICK_ATTACK",
    hexId: "62",
    name: "Quick_attack",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 30,
    effect: "PRIORITY_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "RAGE",
    hexId: "63",
    name: "Rage",
    type: "NORMAL",
    power: 20,
    accuracy: 100,
    pp: 20,
    effect: "RAGE",
    secondaryEffectChance: 0,
  },
  {
    id: "TELEPORT",
    hexId: "64",
    name: "Teleport",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "TELEPORT",
    secondaryEffectChance: 0,
  },
  {
    id: "NIGHT_SHADE",
    hexId: "65",
    name: "Night_shade",
    type: "GHOST",
    power: 1,
    accuracy: 100,
    pp: 15,
    effect: "LEVEL_DAMAGE",
    secondaryEffectChance: 0,
  },
  {
    id: "MIMIC",
    hexId: "66",
    name: "Mimic",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "MIMIC",
    secondaryEffectChance: 0,
  },
  {
    id: "SCREECH",
    hexId: "67",
    name: "Screech",
    type: "NORMAL",
    power: 0,
    accuracy: 85,
    pp: 40,
    effect: "DEFENSE_DOWN_2",
    secondaryEffectChance: 0,
  },
  {
    id: "DOUBLE_TEAM",
    hexId: "68",
    name: "Double_team",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "EVASION_UP",
    secondaryEffectChance: 0,
  },
  {
    id: "RECOVER",
    hexId: "69",
    name: "Recover",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "HEAL",
    secondaryEffectChance: 0,
  },
  {
    id: "HARDEN",
    hexId: "6a",
    name: "Harden",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_UP",
    secondaryEffectChance: 0,
  },
  {
    id: "MINIMIZE",
    hexId: "6b",
    name: "Minimize",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "EVASION_UP",
    secondaryEffectChance: 0,
  },
  {
    id: "SMOKESCREEN",
    hexId: "6c",
    name: "Smokescreen",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "ACCURACY_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "CONFUSE_RAY",
    hexId: "6d",
    name: "Confuse_ray",
    type: "GHOST",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "CONFUSE",
    secondaryEffectChance: 0,
  },
  {
    id: "WITHDRAW",
    hexId: "6e",
    name: "Withdraw",
    type: "WATER",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "DEFENSE_UP",
    secondaryEffectChance: 0,
  },
  {
    id: "DEFENSE_CURL",
    hexId: "6f",
    name: "Defense_curl",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "DEFENSE_CURL",
    secondaryEffectChance: 0,
  },
  {
    id: "BARRIER",
    hexId: "70",
    name: "Barrier",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "DEFENSE_UP_2",
    secondaryEffectChance: 0,
  },
  {
    id: "LIGHT_SCREEN",
    hexId: "71",
    name: "Light_screen",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "LIGHT_SCREEN",
    secondaryEffectChance: 0,
  },
  {
    id: "HAZE",
    hexId: "72",
    name: "Haze",
    type: "ICE",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "RESET_STATS",
    secondaryEffectChance: 0,
  },
  {
    id: "REFLECT",
    hexId: "73",
    name: "Reflect",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "REFLECT",
    secondaryEffectChance: 0,
  },
  {
    id: "FOCUS_ENERGY",
    hexId: "74",
    name: "Focus_energy",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "FOCUS_ENERGY",
    secondaryEffectChance: 0,
  },
  {
    id: "BIDE",
    hexId: "75",
    name: "Bide",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "BIDE",
    secondaryEffectChance: 0,
  },
  {
    id: "METRONOME",
    hexId: "76",
    name: "Metronome",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "METRONOME",
    secondaryEffectChance: 0,
  },
  {
    id: "MIRROR_MOVE",
    hexId: "77",
    name: "Mirror_move",
    type: "FLYING",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "MIRROR_MOVE",
    secondaryEffectChance: 0,
  },
  {
    id: "SELFDESTRUCT",
    hexId: "78",
    name: "Selfdestruct",
    type: "NORMAL",
    power: 200,
    accuracy: 100,
    pp: 5,
    effect: "SELFDESTRUCT",
    secondaryEffectChance: 0,
  },
  {
    id: "EGG_BOMB",
    hexId: "79",
    name: "Egg_bomb",
    type: "NORMAL",
    power: 100,
    accuracy: 75,
    pp: 10,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "LICK",
    hexId: "7a",
    name: "Lick",
    type: "GHOST",
    power: 20,
    accuracy: 100,
    pp: 30,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "SMOG",
    hexId: "7b",
    name: "Smog",
    type: "POISON",
    power: 20,
    accuracy: 70,
    pp: 20,
    effect: "POISON_HIT",
    secondaryEffectChance: 40,
  },
  {
    id: "SLUDGE",
    hexId: "7c",
    name: "Sludge",
    type: "POISON",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "POISON_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "BONE_CLUB",
    hexId: "7d",
    name: "Bone_club",
    type: "GROUND",
    power: 65,
    accuracy: 85,
    pp: 20,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "FIRE_BLAST",
    hexId: "7e",
    name: "Fire_blast",
    type: "FIRE",
    power: 120,
    accuracy: 85,
    pp: 5,
    effect: "BURN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "WATERFALL",
    hexId: "7f",
    name: "Waterfall",
    type: "WATER",
    power: 80,
    accuracy: 100,
    pp: 15,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "CLAMP",
    hexId: "80",
    name: "Clamp",
    type: "WATER",
    power: 35,
    accuracy: 75,
    pp: 10,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
  },
  {
    id: "SWIFT",
    hexId: "81",
    name: "Swift",
    type: "NORMAL",
    power: 60,
    accuracy: 100,
    pp: 20,
    effect: "ALWAYS_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SKULL_BASH",
    hexId: "82",
    name: "Skull_bash",
    type: "NORMAL",
    power: 100,
    accuracy: 100,
    pp: 15,
    effect: "SKULL_BASH",
    secondaryEffectChance: 0,
  },
  {
    id: "SPIKE_CANNON",
    hexId: "83",
    name: "Spike_cannon",
    type: "NORMAL",
    power: 20,
    accuracy: 100,
    pp: 15,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "CONSTRICT",
    hexId: "84",
    name: "Constrict",
    type: "NORMAL",
    power: 10,
    accuracy: 100,
    pp: 35,
    effect: "SPEED_DOWN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "AMNESIA",
    hexId: "85",
    name: "Amnesia",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "SP_DEF_UP_2",
    secondaryEffectChance: 0,
  },
  {
    id: "KINESIS",
    hexId: "86",
    name: "Kinesis",
    type: "PSYCHIC",
    power: 0,
    accuracy: 80,
    pp: 15,
    effect: "ACCURACY_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "SOFTBOILED",
    hexId: "87",
    name: "Softboiled",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "HEAL",
    secondaryEffectChance: 0,
  },
  {
    id: "HI_JUMP_KICK",
    hexId: "88",
    name: "Hi_jump_kick",
    type: "FIGHTING",
    power: 85,
    accuracy: 90,
    pp: 20,
    effect: "JUMP_KICK",
    secondaryEffectChance: 0,
  },
  {
    id: "GLARE",
    hexId: "89",
    name: "Glare",
    type: "NORMAL",
    power: 0,
    accuracy: 75,
    pp: 30,
    effect: "PARALYZE",
    secondaryEffectChance: 0,
  },
  {
    id: "DREAM_EATER",
    hexId: "8a",
    name: "Dream_eater",
    type: "PSYCHIC",
    power: 100,
    accuracy: 100,
    pp: 15,
    effect: "DREAM_EATER",
    secondaryEffectChance: 0,
  },
  {
    id: "POISON_GAS",
    hexId: "8b",
    name: "Poison_gas",
    type: "POISON",
    power: 0,
    accuracy: 55,
    pp: 40,
    effect: "POISON",
    secondaryEffectChance: 0,
  },
  {
    id: "BARRAGE",
    hexId: "8c",
    name: "Barrage",
    type: "NORMAL",
    power: 15,
    accuracy: 85,
    pp: 20,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "LEECH_LIFE",
    hexId: "8d",
    name: "Leech_life",
    type: "BUG",
    power: 20,
    accuracy: 100,
    pp: 15,
    effect: "LEECH_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "LOVELY_KISS",
    hexId: "8e",
    name: "Lovely_kiss",
    type: "NORMAL",
    power: 0,
    accuracy: 75,
    pp: 10,
    effect: "SLEEP",
    secondaryEffectChance: 0,
  },
  {
    id: "SKY_ATTACK",
    hexId: "8f",
    name: "Sky_attack",
    type: "FLYING",
    power: 140,
    accuracy: 90,
    pp: 5,
    effect: "SKY_ATTACK",
    secondaryEffectChance: 0,
  },
  {
    id: "TRANSFORM",
    hexId: "90",
    name: "Transform",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "TRANSFORM",
    secondaryEffectChance: 0,
  },
  {
    id: "BUBBLE",
    hexId: "91",
    name: "Bubble",
    type: "WATER",
    power: 20,
    accuracy: 100,
    pp: 30,
    effect: "SPEED_DOWN_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "DIZZY_PUNCH",
    hexId: "92",
    name: "Dizzy_punch",
    type: "NORMAL",
    power: 70,
    accuracy: 100,
    pp: 10,
    effect: "CONFUSE_HIT",
    secondaryEffectChance: 20,
  },
  {
    id: "SPORE",
    hexId: "93",
    name: "Spore",
    type: "GRASS",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "SLEEP",
    secondaryEffectChance: 0,
  },
  {
    id: "FLASH",
    hexId: "94",
    name: "Flash",
    type: "NORMAL",
    power: 0,
    accuracy: 70,
    pp: 20,
    effect: "ACCURACY_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "PSYWAVE",
    hexId: "95",
    name: "Psywave",
    type: "PSYCHIC",
    power: 1,
    accuracy: 80,
    pp: 15,
    effect: "PSYWAVE",
    secondaryEffectChance: 0,
  },
  {
    id: "SPLASH",
    hexId: "96",
    name: "Splash",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "SPLASH",
    secondaryEffectChance: 0,
  },
  {
    id: "ACID_ARMOR",
    hexId: "97",
    name: "Acid_armor",
    type: "POISON",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "DEFENSE_UP_2",
    secondaryEffectChance: 0,
  },
  {
    id: "CRABHAMMER",
    hexId: "98",
    name: "Crabhammer",
    type: "WATER",
    power: 90,
    accuracy: 85,
    pp: 10,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "EXPLOSION",
    hexId: "99",
    name: "Explosion",
    type: "NORMAL",
    power: 250,
    accuracy: 100,
    pp: 5,
    effect: "SELFDESTRUCT",
    secondaryEffectChance: 0,
  },
  {
    id: "FURY_SWIPES",
    hexId: "9a",
    name: "Fury_swipes",
    type: "NORMAL",
    power: 18,
    accuracy: 80,
    pp: 15,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "BONEMERANG",
    hexId: "9b",
    name: "Bonemerang",
    type: "GROUND",
    power: 50,
    accuracy: 90,
    pp: 10,
    effect: "DOUBLE_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "REST",
    hexId: "9c",
    name: "Rest",
    type: "PSYCHIC",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "HEAL",
    secondaryEffectChance: 0,
  },
  {
    id: "ROCK_SLIDE",
    hexId: "9d",
    name: "Rock_slide",
    type: "ROCK",
    power: 75,
    accuracy: 90,
    pp: 10,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "HYPER_FANG",
    hexId: "9e",
    name: "Hyper_fang",
    type: "NORMAL",
    power: 80,
    accuracy: 90,
    pp: 15,
    effect: "FLINCH_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "SHARPEN",
    hexId: "9f",
    name: "Sharpen",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "ATTACK_UP",
    secondaryEffectChance: 0,
  },
  {
    id: "CONVERSION",
    hexId: "a0",
    name: "Conversion",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "CONVERSION",
    secondaryEffectChance: 0,
  },
  {
    id: "TRI_ATTACK",
    hexId: "a1",
    name: "Tri_attack",
    type: "NORMAL",
    power: 80,
    accuracy: 100,
    pp: 10,
    effect: "TRI_ATTACK",
    secondaryEffectChance: 20,
  },
  {
    id: "SUPER_FANG",
    hexId: "a2",
    name: "Super_fang",
    type: "NORMAL",
    power: 1,
    accuracy: 90,
    pp: 10,
    effect: "SUPER_FANG",
    secondaryEffectChance: 0,
  },
  {
    id: "SLASH",
    hexId: "a3",
    name: "Slash",
    type: "NORMAL",
    power: 70,
    accuracy: 100,
    pp: 20,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SUBSTITUTE",
    hexId: "a4",
    name: "Substitute",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "SUBSTITUTE",
    secondaryEffectChance: 0,
  },
  {
    id: "STRUGGLE",
    hexId: "a5",
    name: "Struggle",
    type: "NORMAL",
    power: 50,
    accuracy: 100,
    pp: 1,
    effect: "RECOIL_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SKETCH",
    hexId: "a6",
    name: "Sketch",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 1,
    effect: "SKETCH",
    secondaryEffectChance: 0,
  },
  {
    id: "TRIPLE_KICK",
    hexId: "a7",
    name: "Triple_kick",
    type: "FIGHTING",
    power: 10,
    accuracy: 90,
    pp: 10,
    effect: "TRIPLE_KICK",
    secondaryEffectChance: 0,
  },
  {
    id: "THIEF",
    hexId: "a8",
    name: "Thief",
    type: "DARK",
    power: 40,
    accuracy: 100,
    pp: 10,
    effect: "THIEF",
    secondaryEffectChance: 100,
  },
  {
    id: "SPIDER_WEB",
    hexId: "a9",
    name: "Spider_web",
    type: "BUG",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "MEAN_LOOK",
    secondaryEffectChance: 0,
  },
  {
    id: "MIND_READER",
    hexId: "aa",
    name: "Mind_reader",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "LOCK_ON",
    secondaryEffectChance: 0,
  },
  {
    id: "NIGHTMARE",
    hexId: "ab",
    name: "Nightmare",
    type: "GHOST",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "NIGHTMARE",
    secondaryEffectChance: 0,
  },
  {
    id: "FLAME_WHEEL",
    hexId: "ac",
    name: "Flame_wheel",
    type: "FIRE",
    power: 60,
    accuracy: 100,
    pp: 25,
    effect: "FLAME_WHEEL",
    secondaryEffectChance: 10,
  },
  {
    id: "SNORE",
    hexId: "ad",
    name: "Snore",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 15,
    effect: "SNORE",
    secondaryEffectChance: 30,
  },
  {
    id: "CURSE",
    hexId: "ae",
    name: "Curse",
    type: "NONE",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "CURSE",
    secondaryEffectChance: 0,
  },
  {
    id: "FLAIL",
    hexId: "af",
    name: "Flail",
    type: "NORMAL",
    power: 1,
    accuracy: 100,
    pp: 15,
    effect: "REVERSAL",
    secondaryEffectChance: 0,
  },
  {
    id: "CONVERSION2",
    hexId: "b0",
    name: "Conversion2",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 30,
    effect: "CONVERSION2",
    secondaryEffectChance: 0,
  },
  {
    id: "AEROBLAST",
    hexId: "b1",
    name: "Aeroblast",
    type: "FLYING",
    power: 100,
    accuracy: 95,
    pp: 5,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "COTTON_SPORE",
    hexId: "b2",
    name: "Cotton_spore",
    type: "GRASS",
    power: 0,
    accuracy: 85,
    pp: 40,
    effect: "SPEED_DOWN_2",
    secondaryEffectChance: 0,
  },
  {
    id: "REVERSAL",
    hexId: "b3",
    name: "Reversal",
    type: "FIGHTING",
    power: 1,
    accuracy: 100,
    pp: 15,
    effect: "REVERSAL",
    secondaryEffectChance: 0,
  },
  {
    id: "SPITE",
    hexId: "b4",
    name: "Spite",
    type: "GHOST",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "SPITE",
    secondaryEffectChance: 0,
  },
  {
    id: "POWDER_SNOW",
    hexId: "b5",
    name: "Powder_snow",
    type: "ICE",
    power: 40,
    accuracy: 100,
    pp: 25,
    effect: "FREEZE_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "PROTECT",
    hexId: "b6",
    name: "Protect",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "PROTECT",
    secondaryEffectChance: 0,
  },
  {
    id: "MACH_PUNCH",
    hexId: "b7",
    name: "Mach_punch",
    type: "FIGHTING",
    power: 40,
    accuracy: 100,
    pp: 30,
    effect: "PRIORITY_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SCARY_FACE",
    hexId: "b8",
    name: "Scary_face",
    type: "NORMAL",
    power: 0,
    accuracy: 90,
    pp: 10,
    effect: "SPEED_DOWN_2",
    secondaryEffectChance: 0,
  },
  {
    id: "FAINT_ATTACK",
    hexId: "b9",
    name: "Faint_attack",
    type: "DARK",
    power: 60,
    accuracy: 100,
    pp: 20,
    effect: "ALWAYS_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SWEET_KISS",
    hexId: "ba",
    name: "Sweet_kiss",
    type: "NORMAL",
    power: 0,
    accuracy: 75,
    pp: 10,
    effect: "CONFUSE",
    secondaryEffectChance: 0,
  },
  {
    id: "BELLY_DRUM",
    hexId: "bb",
    name: "Belly_drum",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "BELLY_DRUM",
    secondaryEffectChance: 0,
  },
  {
    id: "SLUDGE_BOMB",
    hexId: "bc",
    name: "Sludge_bomb",
    type: "POISON",
    power: 90,
    accuracy: 100,
    pp: 10,
    effect: "POISON_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "MUD_SLAP",
    hexId: "bd",
    name: "Mud_slap",
    type: "GROUND",
    power: 20,
    accuracy: 100,
    pp: 10,
    effect: "ACCURACY_DOWN_HIT",
    secondaryEffectChance: 100,
  },
  {
    id: "OCTAZOOKA",
    hexId: "be",
    name: "Octazooka",
    type: "WATER",
    power: 65,
    accuracy: 85,
    pp: 10,
    effect: "ACCURACY_DOWN_HIT",
    secondaryEffectChance: 50,
  },
  {
    id: "SPIKES",
    hexId: "bf",
    name: "Spikes",
    type: "GROUND",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "SPIKES",
    secondaryEffectChance: 0,
  },
  {
    id: "ZAP_CANNON",
    hexId: "c0",
    name: "Zap_cannon",
    type: "ELECTRIC",
    power: 100,
    accuracy: 50,
    pp: 5,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 100,
  },
  {
    id: "FORESIGHT",
    hexId: "c1",
    name: "Foresight",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "FORESIGHT",
    secondaryEffectChance: 0,
  },
  {
    id: "DESTINY_BOND",
    hexId: "c2",
    name: "Destiny_bond",
    type: "GHOST",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "DESTINY_BOND",
    secondaryEffectChance: 0,
  },
  {
    id: "PERISH_SONG",
    hexId: "c3",
    name: "Perish_song",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "PERISH_SONG",
    secondaryEffectChance: 0,
  },
  {
    id: "ICY_WIND",
    hexId: "c4",
    name: "Icy_wind",
    type: "ICE",
    power: 55,
    accuracy: 95,
    pp: 15,
    effect: "SPEED_DOWN_HIT",
    secondaryEffectChance: 100,
  },
  {
    id: "DETECT",
    hexId: "c5",
    name: "Detect",
    type: "FIGHTING",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "PROTECT",
    secondaryEffectChance: 0,
  },
  {
    id: "BONE_RUSH",
    hexId: "c6",
    name: "Bone_rush",
    type: "GROUND",
    power: 25,
    accuracy: 80,
    pp: 10,
    effect: "MULTI_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "LOCK_ON",
    hexId: "c7",
    name: "Lock_on",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "LOCK_ON",
    secondaryEffectChance: 0,
  },
  {
    id: "OUTRAGE",
    hexId: "c8",
    name: "Outrage",
    type: "DRAGON",
    power: 90,
    accuracy: 100,
    pp: 15,
    effect: "RAMPAGE",
    secondaryEffectChance: 0,
  },
  {
    id: "SANDSTORM",
    hexId: "c9",
    name: "Sandstorm",
    type: "ROCK",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "SANDSTORM",
    secondaryEffectChance: 0,
  },
  {
    id: "GIGA_DRAIN",
    hexId: "ca",
    name: "Giga_drain",
    type: "GRASS",
    power: 60,
    accuracy: 100,
    pp: 5,
    effect: "LEECH_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "ENDURE",
    hexId: "cb",
    name: "Endure",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "ENDURE",
    secondaryEffectChance: 0,
  },
  {
    id: "CHARM",
    hexId: "cc",
    name: "Charm",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "ATTACK_DOWN_2",
    secondaryEffectChance: 0,
  },
  {
    id: "ROLLOUT",
    hexId: "cd",
    name: "Rollout",
    type: "ROCK",
    power: 30,
    accuracy: 90,
    pp: 20,
    effect: "ROLLOUT",
    secondaryEffectChance: 0,
  },
  {
    id: "FALSE_SWIPE",
    hexId: "ce",
    name: "False_swipe",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 40,
    effect: "FALSE_SWIPE",
    secondaryEffectChance: 0,
  },
  {
    id: "SWAGGER",
    hexId: "cf",
    name: "Swagger",
    type: "NORMAL",
    power: 0,
    accuracy: 90,
    pp: 15,
    effect: "SWAGGER",
    secondaryEffectChance: 100,
  },
  {
    id: "MILK_DRINK",
    hexId: "d0",
    name: "Milk_drink",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "HEAL",
    secondaryEffectChance: 0,
  },
  {
    id: "SPARK",
    hexId: "d1",
    name: "Spark",
    type: "ELECTRIC",
    power: 65,
    accuracy: 100,
    pp: 20,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "FURY_CUTTER",
    hexId: "d2",
    name: "Fury_cutter",
    type: "BUG",
    power: 10,
    accuracy: 95,
    pp: 20,
    effect: "FURY_CUTTER",
    secondaryEffectChance: 0,
  },
  {
    id: "STEEL_WING",
    hexId: "d3",
    name: "Steel_wing",
    type: "STEEL",
    power: 70,
    accuracy: 90,
    pp: 25,
    effect: "DEFENSE_UP_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "MEAN_LOOK",
    hexId: "d4",
    name: "Mean_look",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "MEAN_LOOK",
    secondaryEffectChance: 0,
  },
  {
    id: "ATTRACT",
    hexId: "d5",
    name: "Attract",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 15,
    effect: "ATTRACT",
    secondaryEffectChance: 0,
  },
  {
    id: "SLEEP_TALK",
    hexId: "d6",
    name: "Sleep_talk",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "SLEEP_TALK",
    secondaryEffectChance: 0,
  },
  {
    id: "HEAL_BELL",
    hexId: "d7",
    name: "Heal_bell",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "HEAL_BELL",
    secondaryEffectChance: 0,
  },
  {
    id: "RETURN",
    hexId: "d8",
    name: "Return",
    type: "NORMAL",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "RETURN",
    secondaryEffectChance: 0,
  },
  {
    id: "PRESENT",
    hexId: "d9",
    name: "Present",
    type: "NORMAL",
    power: 1,
    accuracy: 90,
    pp: 15,
    effect: "PRESENT",
    secondaryEffectChance: 0,
  },
  {
    id: "FRUSTRATION",
    hexId: "da",
    name: "Frustration",
    type: "NORMAL",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "FRUSTRATION",
    secondaryEffectChance: 0,
  },
  {
    id: "SAFEGUARD",
    hexId: "db",
    name: "Safeguard",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 25,
    effect: "SAFEGUARD",
    secondaryEffectChance: 0,
  },
  {
    id: "PAIN_SPLIT",
    hexId: "dc",
    name: "Pain_split",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "PAIN_SPLIT",
    secondaryEffectChance: 0,
  },
  {
    id: "SACRED_FIRE",
    hexId: "dd",
    name: "Sacred_fire",
    type: "FIRE",
    power: 100,
    accuracy: 95,
    pp: 5,
    effect: "SACRED_FIRE",
    secondaryEffectChance: 50,
  },
  {
    id: "MAGNITUDE",
    hexId: "de",
    name: "Magnitude",
    type: "GROUND",
    power: 1,
    accuracy: 100,
    pp: 30,
    effect: "MAGNITUDE",
    secondaryEffectChance: 0,
  },
  {
    id: "DYNAMICPUNCH",
    hexId: "df",
    name: "Dynamicpunch",
    type: "FIGHTING",
    power: 100,
    accuracy: 50,
    pp: 5,
    effect: "CONFUSE_HIT",
    secondaryEffectChance: 100,
  },
  {
    id: "MEGAHORN",
    hexId: "e0",
    name: "Megahorn",
    type: "BUG",
    power: 120,
    accuracy: 85,
    pp: 10,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "DRAGONBREATH",
    hexId: "e1",
    name: "Dragonbreath",
    type: "DRAGON",
    power: 60,
    accuracy: 100,
    pp: 20,
    effect: "PARALYZE_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "BATON_PASS",
    hexId: "e2",
    name: "Baton_pass",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 40,
    effect: "BATON_PASS",
    secondaryEffectChance: 0,
  },
  {
    id: "ENCORE",
    hexId: "e3",
    name: "Encore",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "ENCORE",
    secondaryEffectChance: 0,
  },
  {
    id: "PURSUIT",
    hexId: "e4",
    name: "Pursuit",
    type: "DARK",
    power: 40,
    accuracy: 100,
    pp: 20,
    effect: "PURSUIT",
    secondaryEffectChance: 0,
  },
  {
    id: "RAPID_SPIN",
    hexId: "e5",
    name: "Rapid_spin",
    type: "NORMAL",
    power: 20,
    accuracy: 100,
    pp: 40,
    effect: "RAPID_SPIN",
    secondaryEffectChance: 0,
  },
  {
    id: "SWEET_SCENT",
    hexId: "e6",
    name: "Sweet_scent",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 20,
    effect: "EVASION_DOWN",
    secondaryEffectChance: 0,
  },
  {
    id: "IRON_TAIL",
    hexId: "e7",
    name: "Iron_tail",
    type: "STEEL",
    power: 100,
    accuracy: 75,
    pp: 15,
    effect: "DEFENSE_DOWN_HIT",
    secondaryEffectChance: 30,
  },
  {
    id: "METAL_CLAW",
    hexId: "e8",
    name: "Metal_claw",
    type: "STEEL",
    power: 50,
    accuracy: 95,
    pp: 35,
    effect: "ATTACK_UP_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "VITAL_THROW",
    hexId: "e9",
    name: "Vital_throw",
    type: "FIGHTING",
    power: 70,
    accuracy: 100,
    pp: 10,
    effect: "ALWAYS_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "MORNING_SUN",
    hexId: "ea",
    name: "Morning_sun",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "MORNING_SUN",
    secondaryEffectChance: 0,
  },
  {
    id: "SYNTHESIS",
    hexId: "eb",
    name: "Synthesis",
    type: "GRASS",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "SYNTHESIS",
    secondaryEffectChance: 0,
  },
  {
    id: "MOONLIGHT",
    hexId: "ec",
    name: "Moonlight",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 5,
    effect: "MOONLIGHT",
    secondaryEffectChance: 0,
  },
  {
    id: "HIDDEN_POWER",
    hexId: "ed",
    name: "Hidden_power",
    type: "NORMAL",
    power: 1,
    accuracy: 100,
    pp: 15,
    effect: "HIDDEN_POWER",
    secondaryEffectChance: 0,
  },
  {
    id: "CROSS_CHOP",
    hexId: "ee",
    name: "Cross_chop",
    type: "FIGHTING",
    power: 100,
    accuracy: 80,
    pp: 5,
    effect: "HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "TWISTER",
    hexId: "ef",
    name: "Twister",
    type: "DRAGON",
    power: 40,
    accuracy: 100,
    pp: 20,
    effect: "TWISTER",
    secondaryEffectChance: 20,
  },
  {
    id: "RAIN_DANCE",
    hexId: "f0",
    name: "Rain_dance",
    type: "WATER",
    power: 0,
    accuracy: 90,
    pp: 5,
    effect: "RAIN_DANCE",
    secondaryEffectChance: 0,
  },
  {
    id: "SUNNY_DAY",
    hexId: "f1",
    name: "Sunny_day",
    type: "FIRE",
    power: 0,
    accuracy: 90,
    pp: 5,
    effect: "SUNNY_DAY",
    secondaryEffectChance: 0,
  },
  {
    id: "CRUNCH",
    hexId: "f2",
    name: "Crunch",
    type: "DARK",
    power: 80,
    accuracy: 100,
    pp: 15,
    effect: "SP_DEF_DOWN_HIT",
    secondaryEffectChance: 20,
  },
  {
    id: "MIRROR_COAT",
    hexId: "f3",
    name: "Mirror_coat",
    type: "PSYCHIC",
    power: 1,
    accuracy: 100,
    pp: 20,
    effect: "MIRROR_COAT",
    secondaryEffectChance: 0,
  },
  {
    id: "PSYCH_UP",
    hexId: "f4",
    name: "Psych_up",
    type: "NORMAL",
    power: 0,
    accuracy: 100,
    pp: 10,
    effect: "PSYCH_UP",
    secondaryEffectChance: 0,
  },
  {
    id: "EXTREMESPEED",
    hexId: "f5",
    name: "Extremespeed",
    type: "NORMAL",
    power: 80,
    accuracy: 100,
    pp: 5,
    effect: "PRIORITY_HIT",
    secondaryEffectChance: 0,
  },
  {
    id: "ANCIENTPOWER",
    hexId: "f6",
    name: "Ancientpower",
    type: "ROCK",
    power: 60,
    accuracy: 100,
    pp: 5,
    effect: "ALL_UP_HIT",
    secondaryEffectChance: 10,
  },
  {
    id: "SHADOW_BALL",
    hexId: "f7",
    name: "Shadow_ball",
    type: "GHOST",
    power: 80,
    accuracy: 100,
    pp: 15,
    effect: "SP_DEF_DOWN_HIT",
    secondaryEffectChance: 20,
  },
  {
    id: "FUTURE_SIGHT",
    hexId: "f8",
    name: "Future_sight",
    type: "PSYCHIC",
    power: 80,
    accuracy: 90,
    pp: 15,
    effect: "FUTURE_SIGHT",
    secondaryEffectChance: 0,
  },
  {
    id: "ROCK_SMASH",
    hexId: "f9",
    name: "Rock_smash",
    type: "FIGHTING",
    power: 20,
    accuracy: 100,
    pp: 15,
    effect: "DEFENSE_DOWN_HIT",
    secondaryEffectChance: 50,
  },
  {
    id: "WHIRLPOOL",
    hexId: "fa",
    name: "Whirlpool",
    type: "WATER",
    power: 15,
    accuracy: 70,
    pp: 15,
    effect: "TRAP_TARGET",
    secondaryEffectChance: 0,
  },
  {
    id: "BEAT_UP",
    hexId: "fb",
    name: "Beat_up",
    type: "DARK",
    power: 10,
    accuracy: 100,
    pp: 10,
    effect: "BEAT_UP",
    secondaryEffectChance: 0,
  },
]