import type { OddEgg } from "@shared/types/gameData/oddEgg"

export const oddEggs: OddEgg[] = [
  {
    pokemonId: "PICHU",
    moves: [
      {
        id: "THUNDERSHOCK",
        pp: 30,
      },
      {
        id: "CHARM",
        pp: 20,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 2048,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 17,
      attack: 9,
      defence: 6,
      speed: 11,
      specialAttack: 8,
      specialDefence: 8,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "PICHU",
    moves: [
      {
        id: "THUNDERSHOCK",
        pp: 30,
      },
      {
        id: "CHARM",
        pp: 20,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 256,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 2,
      defence: 10,
      speed: 10,
      special: 10,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 17,
      attack: 9,
      defence: 7,
      speed: 12,
      specialAttack: 9,
      specialDefence: 9,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "CLEFFA",
    moves: [
      {
        id: "POUND",
        pp: 35,
      },
      {
        id: "CHARM",
        pp: 20,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 4096,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 20,
      attack: 7,
      defence: 7,
      speed: 6,
      specialAttack: 9,
      specialDefence: 10,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "CLEFFA",
    moves: [
      {
        id: "POUND",
        pp: 35,
      },
      {
        id: "CHARM",
        pp: 20,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 768,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 2,
      defence: 10,
      speed: 10,
      special: 10,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 20,
      attack: 7,
      defence: 8,
      speed: 7,
      specialAttack: 10,
      specialDefence: 11,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "IGGLYBUFF",
    moves: [
      {
        id: "SING",
        pp: 15,
      },
      {
        id: "CHARM",
        pp: 20,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 4096,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 24,
      attack: 8,
      defence: 6,
      speed: 6,
      specialAttack: 9,
      specialDefence: 7,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "IGGLYBUFF",
    moves: [
      {
        id: "SING",
        pp: 15,
      },
      {
        id: "CHARM",
        pp: 20,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 768,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 2,
      defence: 10,
      speed: 10,
      special: 10,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 24,
      attack: 8,
      defence: 7,
      speed: 7,
      specialAttack: 10,
      specialDefence: 8,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "SMOOCHUM",
    moves: [
      {
        id: "POUND",
        pp: 35,
      },
      {
        id: "LICK",
        pp: 30,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 3584,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 19,
      attack: 8,
      defence: 6,
      speed: 11,
      specialAttack: 13,
      specialDefence: 11,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "SMOOCHUM",
    moves: [
      {
        id: "POUND",
        pp: 35,
      },
      {
        id: "LICK",
        pp: 30,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 512,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 2,
      defence: 10,
      speed: 10,
      special: 10,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 19,
      attack: 8,
      defence: 7,
      speed: 12,
      specialAttack: 14,
      specialDefence: 12,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "MAGBY",
    moves: [
      {
        id: "EMBER",
        pp: 25,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 2560,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 19,
      attack: 12,
      defence: 8,
      speed: 13,
      specialAttack: 12,
      specialDefence: 10,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "MAGBY",
    moves: [
      {
        id: "EMBER",
        pp: 25,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 512,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 2,
      defence: 10,
      speed: 10,
      special: 10,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 19,
      attack: 12,
      defence: 9,
      speed: 14,
      specialAttack: 13,
      specialDefence: 11,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "ELEKID",
    moves: [
      {
        id: "QUICK_ATTACK",
        pp: 30,
      },
      {
        id: "LEER",
        pp: 30,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 3072,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 19,
      attack: 11,
      defence: 8,
      speed: 14,
      specialAttack: 11,
      specialDefence: 10,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "ELEKID",
    moves: [
      {
        id: "QUICK_ATTACK",
        pp: 30,
      },
      {
        id: "LEER",
        pp: 30,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 512,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 2,
      defence: 10,
      speed: 10,
      special: 10,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 19,
      attack: 11,
      defence: 9,
      speed: 15,
      specialAttack: 12,
      specialDefence: 11,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "TYROGUE",
    moves: [
      {
        id: "TACKLE",
        pp: 35,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 2560,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 18,
      attack: 8,
      defence: 8,
      speed: 8,
      specialAttack: 8,
      specialDefence: 8,
    },
    name: "EGG@@@@@@@@",
  },
  {
    pokemonId: "TYROGUE",
    moves: [
      {
        id: "TACKLE",
        pp: 35,
      },
      {
        id: "DIZZY_PUNCH",
        pp: 10,
      },
    ],
    ot: 256,
    experience: 125,
    statExperience: {
      hp: 0,
      attack: 0,
      defence: 0,
      speed: 0,
      special: 0,
    },
    dvs: {
      attack: 2,
      defence: 10,
      speed: 10,
      special: 10,
    },
    hatchCyclesRemaining: 20,
    level: 5,
    stats: {
      hp: 18,
      attack: 8,
      defence: 9,
      speed: 9,
      specialAttack: 9,
      specialDefence: 9,
    },
    name: "EGG@@@@@@@@",
  },
] as const