import type { TeachableMove } from "@shared/types/gameData/teachableMove"
import type { TeachableMoveId } from "@shared/types/gameDataIds/teachableMoves"

export const teachableMovesMap: IdMap<TeachableMoveId, TeachableMove> = {
  TM01: {
    id: "TM01",
    type: "TM",
    moveId: "DYNAMICPUNCH",
    byteIndex: 0,
    bitIndex: 0,
  },
  TM02: {
    id: "TM02",
    type: "TM",
    moveId: "HEADBUTT",
    byteIndex: 0,
    bitIndex: 1,
  },
  TM03: {
    id: "TM03",
    type: "TM",
    moveId: "CURSE",
    byteIndex: 0,
    bitIndex: 2,
  },
  TM04: {
    id: "TM04",
    type: "TM",
    moveId: "ROLLOUT",
    byteIndex: 0,
    bitIndex: 3,
  },
  TM05: {
    id: "TM05",
    type: "TM",
    moveId: "ROAR",
    byteIndex: 0,
    bitIndex: 4,
  },
  TM06: {
    id: "TM06",
    type: "TM",
    moveId: "TOXIC",
    byteIndex: 0,
    bitIndex: 5,
  },
  TM07: {
    id: "TM07",
    type: "TM",
    moveId: "ZAP_CANNON",
    byteIndex: 0,
    bitIndex: 6,
  },
  TM08: {
    id: "TM08",
    type: "TM",
    moveId: "ROCK_SMASH",
    byteIndex: 0,
    bitIndex: 7,
  },
  TM09: {
    id: "TM09",
    type: "TM",
    moveId: "PSYCH_UP",
    byteIndex: 1,
    bitIndex: 0,
  },
  TM10: {
    id: "TM10",
    type: "TM",
    moveId: "HIDDEN_POWER",
    byteIndex: 1,
    bitIndex: 1,
  },
  TM11: {
    id: "TM11",
    type: "TM",
    moveId: "SUNNY_DAY",
    byteIndex: 1,
    bitIndex: 2,
  },
  TM12: {
    id: "TM12",
    type: "TM",
    moveId: "SWEET_SCENT",
    byteIndex: 1,
    bitIndex: 3,
  },
  TM13: {
    id: "TM13",
    type: "TM",
    moveId: "SNORE",
    byteIndex: 1,
    bitIndex: 4,
  },
  TM14: {
    id: "TM14",
    type: "TM",
    moveId: "BLIZZARD",
    byteIndex: 1,
    bitIndex: 5,
  },
  TM15: {
    id: "TM15",
    type: "TM",
    moveId: "HYPER_BEAM",
    byteIndex: 1,
    bitIndex: 6,
  },
  TM16: {
    id: "TM16",
    type: "TM",
    moveId: "ICY_WIND",
    byteIndex: 1,
    bitIndex: 7,
  },
  TM17: {
    id: "TM17",
    type: "TM",
    moveId: "PROTECT",
    byteIndex: 2,
    bitIndex: 0,
  },
  TM18: {
    id: "TM18",
    type: "TM",
    moveId: "RAIN_DANCE",
    byteIndex: 2,
    bitIndex: 1,
  },
  TM19: {
    id: "TM19",
    type: "TM",
    moveId: "GIGA_DRAIN",
    byteIndex: 2,
    bitIndex: 2,
  },
  TM20: {
    id: "TM20",
    type: "TM",
    moveId: "ENDURE",
    byteIndex: 2,
    bitIndex: 3,
  },
  TM21: {
    id: "TM21",
    type: "TM",
    moveId: "FRUSTRATION",
    byteIndex: 2,
    bitIndex: 4,
  },
  TM22: {
    id: "TM22",
    type: "TM",
    moveId: "SOLARBEAM",
    byteIndex: 2,
    bitIndex: 5,
  },
  TM23: {
    id: "TM23",
    type: "TM",
    moveId: "IRON_TAIL",
    byteIndex: 2,
    bitIndex: 6,
  },
  TM24: {
    id: "TM24",
    type: "TM",
    moveId: "DRAGONBREATH",
    byteIndex: 2,
    bitIndex: 7,
  },
  TM25: {
    id: "TM25",
    type: "TM",
    moveId: "THUNDER",
    byteIndex: 3,
    bitIndex: 0,
  },
  TM26: {
    id: "TM26",
    type: "TM",
    moveId: "EARTHQUAKE",
    byteIndex: 3,
    bitIndex: 1,
  },
  TM27: {
    id: "TM27",
    type: "TM",
    moveId: "RETURN",
    byteIndex: 3,
    bitIndex: 2,
  },
  TM28: {
    id: "TM28",
    type: "TM",
    moveId: "DIG",
    byteIndex: 3,
    bitIndex: 3,
  },
  TM29: {
    id: "TM29",
    type: "TM",
    moveId: "PSYCHIC",
    byteIndex: 3,
    bitIndex: 4,
  },
  TM30: {
    id: "TM30",
    type: "TM",
    moveId: "SHADOW_BALL",
    byteIndex: 3,
    bitIndex: 5,
  },
  TM31: {
    id: "TM31",
    type: "TM",
    moveId: "MUD_SLAP",
    byteIndex: 3,
    bitIndex: 6,
  },
  TM32: {
    id: "TM32",
    type: "TM",
    moveId: "DOUBLE_TEAM",
    byteIndex: 3,
    bitIndex: 7,
  },
  TM33: {
    id: "TM33",
    type: "TM",
    moveId: "ICE_PUNCH",
    byteIndex: 4,
    bitIndex: 0,
  },
  TM34: {
    id: "TM34",
    type: "TM",
    moveId: "SWAGGER",
    byteIndex: 4,
    bitIndex: 1,
  },
  TM35: {
    id: "TM35",
    type: "TM",
    moveId: "SLEEP_TALK",
    byteIndex: 4,
    bitIndex: 2,
  },
  TM36: {
    id: "TM36",
    type: "TM",
    moveId: "SLUDGE_BOMB",
    byteIndex: 4,
    bitIndex: 3,
  },
  TM37: {
    id: "TM37",
    type: "TM",
    moveId: "SANDSTORM",
    byteIndex: 4,
    bitIndex: 4,
  },
  TM38: {
    id: "TM38",
    type: "TM",
    moveId: "FIRE_BLAST",
    byteIndex: 4,
    bitIndex: 5,
  },
  TM39: {
    id: "TM39",
    type: "TM",
    moveId: "SWIFT",
    byteIndex: 4,
    bitIndex: 6,
  },
  TM40: {
    id: "TM40",
    type: "TM",
    moveId: "DEFENSE_CURL",
    byteIndex: 4,
    bitIndex: 7,
  },
  TM41: {
    id: "TM41",
    type: "TM",
    moveId: "THUNDERPUNCH",
    byteIndex: 5,
    bitIndex: 0,
  },
  TM42: {
    id: "TM42",
    type: "TM",
    moveId: "DREAM_EATER",
    byteIndex: 5,
    bitIndex: 1,
  },
  TM43: {
    id: "TM43",
    type: "TM",
    moveId: "DETECT",
    byteIndex: 5,
    bitIndex: 2,
  },
  TM44: {
    id: "TM44",
    type: "TM",
    moveId: "REST",
    byteIndex: 5,
    bitIndex: 3,
  },
  TM45: {
    id: "TM45",
    type: "TM",
    moveId: "ATTRACT",
    byteIndex: 5,
    bitIndex: 4,
  },
  TM46: {
    id: "TM46",
    type: "TM",
    moveId: "THIEF",
    byteIndex: 5,
    bitIndex: 5,
  },
  TM47: {
    id: "TM47",
    type: "TM",
    moveId: "STEEL_WING",
    byteIndex: 5,
    bitIndex: 6,
  },
  TM48: {
    id: "TM48",
    type: "TM",
    moveId: "FIRE_PUNCH",
    byteIndex: 5,
    bitIndex: 7,
  },
  TM49: {
    id: "TM49",
    type: "TM",
    moveId: "FURY_CUTTER",
    byteIndex: 6,
    bitIndex: 0,
  },
  TM50: {
    id: "TM50",
    type: "TM",
    moveId: "NIGHTMARE",
    byteIndex: 6,
    bitIndex: 1,
  },
  HM01: {
    id: "HM01",
    type: "HM",
    moveId: "CUT",
    byteIndex: 6,
    bitIndex: 2,
  },
  HM02: {
    id: "HM02",
    type: "HM",
    moveId: "FLY",
    byteIndex: 6,
    bitIndex: 3,
  },
  HM03: {
    id: "HM03",
    type: "HM",
    moveId: "SURF",
    byteIndex: 6,
    bitIndex: 4,
  },
  HM04: {
    id: "HM04",
    type: "HM",
    moveId: "STRENGTH",
    byteIndex: 6,
    bitIndex: 5,
  },
  HM05: {
    id: "HM05",
    type: "HM",
    moveId: "FLASH",
    byteIndex: 6,
    bitIndex: 6,
  },
  HM06: {
    id: "HM06",
    type: "HM",
    moveId: "WHIRLPOOL",
    byteIndex: 6,
    bitIndex: 7,
  },
  HM07: {
    id: "HM07",
    type: "HM",
    moveId: "WATERFALL",
    byteIndex: 7,
    bitIndex: 0,
  },
  MOVE_TUTOR_1: {
    id: "MOVE_TUTOR_1",
    type: "MOVE_TUTOR",
    moveId: "FLAMETHROWER",
    byteIndex: 7,
    bitIndex: 1,
  },
  MOVE_TUTOR_2: {
    id: "MOVE_TUTOR_2",
    type: "MOVE_TUTOR",
    moveId: "THUNDERBOLT",
    byteIndex: 7,
    bitIndex: 2,
  },
  MOVE_TUTOR_3: {
    id: "MOVE_TUTOR_3",
    type: "MOVE_TUTOR",
    moveId: "ICE_BEAM",
    byteIndex: 7,
    bitIndex: 3,
  },
} as const