import type { Trade } from "@shared/types/gameData/trade"
import type { TradeId } from "@shared/types/gameDataIds/trades"

export const tradesMap: IdMap<TradeId, Trade> = {
  MIKE: {
    id: "MIKE",
    mapId: "GOLDENROD_DEPT_STORE_1F",
    dialogSetId: "COLLECTOR",
    requestedPokémonId: "ABRA",
    offeredPokemonId: "MACHOP",
    nickname: "MUSCLE",
    dvs: 0x6637,
    heldItemId: "GOLD_BERRY",
    originalTrainerId: 37460,
    originalTrainerName: "MIKE",
    genderId: "ANY",
  },
  KYLE: {
    id: "KYLE",
    mapId: "VIOLET_KYLES_HOUSE",
    dialogSetId: "COLLECTOR",
    requestedPokémonId: "BELLSPROUT",
    offeredPokemonId: "ONIX",
    nickname: "ROCKY",
    dvs: 0x6696,
    heldItemId: "BITTER_BERRY",
    originalTrainerId: 48926,
    originalTrainerName: "KYLE",
    genderId: "ANY",
  },
  TIM: {
    id: "TIM",
    mapId: "OLIVINE_TIMS_HOUSE",
    dialogSetId: "HAPPY",
    requestedPokémonId: "KRABBY",
    offeredPokemonId: "VOLTORB",
    nickname: "VOLTY",
    dvs: 0x8898,
    heldItemId: "PRZCUREBERRY",
    originalTrainerId: 29189,
    originalTrainerName: "TIM",
    genderId: "ANY",
  },
  EMY: {
    id: "EMY",
    mapId: "BLACKTHORN_EMYS_HOUSE",
    dialogSetId: "GIRL",
    requestedPokémonId: "DRAGONAIR",
    offeredPokemonId: "DODRIO",
    nickname: "DORIS",
    dvs: 0x6677,
    heldItemId: "SMOKE_BALL",
    originalTrainerId: 283,
    originalTrainerName: "EMY",
    genderId: "FEMALE",
  },
  CHRIS: {
    id: "CHRIS",
    mapId: "PEWTER_POKECENTER_1F",
    dialogSetId: "NEWBIE",
    requestedPokémonId: "HAUNTER",
    offeredPokemonId: "XATU",
    nickname: "PAUL",
    dvs: 0x8696,
    heldItemId: "MYSTERYBERRY",
    originalTrainerId: 15616,
    originalTrainerName: "CHRIS",
    genderId: "ANY",
  },
  KIM: {
    id: "KIM",
    mapId: "ROUTE_14",
    dialogSetId: "GIRL",
    requestedPokémonId: "CHANSEY",
    offeredPokemonId: "AERODACTYL",
    nickname: "AEROY",
    dvs: 0x6696,
    heldItemId: "GOLD_BERRY",
    originalTrainerId: 26491,
    originalTrainerName: "KIM",
    genderId: "ANY",
  },
  FOREST: {
    id: "FOREST",
    mapId: "POWER_PLANT",
    dialogSetId: "COLLECTOR",
    requestedPokémonId: "DUGTRIO",
    offeredPokemonId: "MAGNETON",
    nickname: "MAGGIE",
    dvs: 0x6696,
    heldItemId: "METAL_COAT",
    originalTrainerId: 50082,
    originalTrainerName: "FOREST",
    genderId: "ANY",
  },
}